export interface MLQuestion {
  id: string
  level: 'soft' | 'hard'
  text: string
}

export const ML_QUESTIONS: MLQuestion[] = [
  // ─── SOFT (100) ────────────────────────────────────────────────────────────

  // Flemme légendaire
  { id: 'ml_soft_1',  level: 'soft', text: 'Qui pourrait commander un Uber pour faire moins de 300 mètres ?' },
  { id: 'ml_soft_2',  level: 'soft', text: 'Qui pourrait envoyer un message vocal de 4 minutes plutôt que de rappeler ?' },
  { id: 'ml_soft_3',  level: 'soft', text: 'Qui pourrait payer plus cher juste pour ne pas avoir à chercher une place de parking ?' },
  { id: 'ml_soft_4',  level: 'soft', text: 'Qui pourrait laisser sa valise non rangée pendant une semaine après être rentré de vacances ?' },
  { id: 'ml_soft_5',  level: 'soft', text: 'Qui pourrait lire un message sans répondre et l\'oublier pendant 3 jours ?' },
  { id: 'ml_soft_6',  level: 'soft', text: 'Qui pourrait regarder un film en 4 fois parce qu\'il s\'endort à chaque fois ?' },
  { id: 'ml_soft_7',  level: 'soft', text: 'Qui pourrait mettre sa tenue du lendemain sur sa chaise de bureau depuis l\'enfance ?' },
  { id: 'ml_soft_8',  level: 'soft', text: 'Qui pourrait faire 5 allers-retours dans sa cuisine parce qu\'il oublie ce qu\'il est venu chercher ?' },
  { id: 'ml_soft_9',  level: 'soft', text: 'Qui pourrait laisser le linge dans le tambour de la machine pendant 2 jours ?' },
  { id: 'ml_soft_10', level: 'soft', text: 'Qui pourrait repousser sa sonnerie de réveil 7 fois avant de se lever ?' },

  // Étourderies & bourdes
  { id: 'ml_soft_11', level: 'soft', text: 'Qui pourrait essayer de rentrer chez lui avec les clés de sa voiture dans sa porte d\'entrée ?' },
  { id: 'ml_soft_12', level: 'soft', text: 'Qui pourrait mettre ses lunettes pour chercher ses lunettes ?' },
  { id: 'ml_soft_13', level: 'soft', text: 'Qui pourrait passer 10 minutes à chercher son téléphone alors qu\'il est en train de chercher dessus ?' },
  { id: 'ml_soft_14', level: 'soft', text: 'Qui pourrait oublier son code de carte bleue au moment de payer l\'addition ?' },
  { id: 'ml_soft_15', level: 'soft', text: 'Qui pourrait envoyer un message à la mauvaise personne et paniquer ?' },
  { id: 'ml_soft_16', level: 'soft', text: 'Qui pourrait sortir en ayant mis son pull à l\'envers sans s\'en rendre compte ?' },
  { id: 'ml_soft_17', level: 'soft', text: 'Qui pourrait arriver à une réunion un jour trop tôt ?' },
  { id: 'ml_soft_18', level: 'soft', text: 'Qui pourrait appeler quelqu\'un "maman" par accident ?' },
  { id: 'ml_soft_19', level: 'soft', text: 'Qui pourrait verser son café dans son verre d\'eau parce qu\'il est pas réveillé ?' },
  { id: 'ml_soft_20', level: 'soft', text: 'Qui pourrait confondre sel et sucre et servir ça à des invités sans s\'en apercevoir ?' },

  // Réseaux sociaux & téléphone
  { id: 'ml_soft_21', level: 'soft', text: 'Qui pourrait liker accidentellement une vieille photo en faisant du stalking ?' },
  { id: 'ml_soft_22', level: 'soft', text: 'Qui pourrait regarder les stories Insta de quelqu\'un tous les jours sans jamais lui parler ?' },
  { id: 'ml_soft_23', level: 'soft', text: 'Qui pourrait passer 2h sur TikTok en pensant en avoir passé 15 minutes ?' },
  { id: 'ml_soft_24', level: 'soft', text: 'Qui pourrait suivre un inconnu par erreur et le désabonner 3 secondes après ?' },
  { id: 'ml_soft_25', level: 'soft', text: 'Qui pourrait poster une photo puis la supprimer parce qu\'elle n\'a pas assez de likes ?' },
  { id: 'ml_soft_26', level: 'soft', text: 'Qui pourrait répondre "ça va et toi ?" sans attendre la réponse ?' },
  { id: 'ml_soft_27', level: 'soft', text: 'Qui pourrait avoir plus de 1000 notifications non lues ?' },
  { id: 'ml_soft_28', level: 'soft', text: 'Qui pourrait mettre en sourdine un groupe WhatsApp et ne jamais le sortir de sourdine ?' },
  { id: 'ml_soft_29', level: 'soft', text: 'Qui pourrait écrire un long message, tout effacer et envoyer juste "ok" ?' },
  { id: 'ml_soft_30', level: 'soft', text: 'Qui pourrait rechercher ses propres photos pour voir comment il apparaît dans les recherches ?' },

  // Comportements en société
  { id: 'ml_soft_31', level: 'soft', text: 'Qui pourrait dire "c\'est pas loin" et marcher 40 minutes ?' },
  { id: 'ml_soft_32', level: 'soft', text: 'Qui pourrait oublier le prénom de quelqu\'un au milieu d\'une présentation ?' },
  { id: 'ml_soft_33', level: 'soft', text: 'Qui pourrait inventer un rendez-vous pour partir d\'une soirée ennuyeuse ?' },
  { id: 'ml_soft_34', level: 'soft', text: 'Qui pourrait rire très fort à une blague qu\'il n\'a pas comprise ?' },
  { id: 'ml_soft_35', level: 'soft', text: 'Qui pourrait répondre "avec plaisir" au lieu de "merci" ?' },
  { id: 'ml_soft_36', level: 'soft', text: 'Qui pourrait se faire rembarrer en essayant d\'être drôle ?' },
  { id: 'ml_soft_37', level: 'soft', text: 'Qui pourrait passer au rouge parce qu\'il n\'a pas entendu ce qu\'on lui a dit ?' },
  { id: 'ml_soft_38', level: 'soft', text: 'Qui pourrait dire "moi pareil" alors que c\'est totalement faux ?' },
  { id: 'ml_soft_39', level: 'soft', text: 'Qui pourrait donner une poignée de main à quelqu\'un qui voulait faire la bise ?' },
  { id: 'ml_soft_40', level: 'soft', text: 'Qui pourrait claquer la bise dans le vide parce qu\'il ne sait pas combien en faire ?' },

  // Alimentation & cuisine
  { id: 'ml_soft_41', level: 'soft', text: 'Qui pourrait manger les restes du frigo froid parce qu\'il est trop flemmard pour chauffer ?' },
  { id: 'ml_soft_42', level: 'soft', text: 'Qui pourrait appeler la livraison 3 soirs de suite au même endroit ?' },
  { id: 'ml_soft_43', level: 'soft', text: 'Qui pourrait brûler de l\'eau en faisant une recette "simple" ?' },
  { id: 'ml_soft_44', level: 'soft', text: 'Qui pourrait manger directement dans la casserole pour éviter de faire la vaisselle ?' },
  { id: 'ml_soft_45', level: 'soft', text: 'Qui pourrait commander une entrée + plat + dessert et regretter dès l\'entrée ?' },
  { id: 'ml_soft_46', level: 'soft', text: 'Qui pourrait finir l\'assiette de tout le monde "pour ne pas gâcher" ?' },
  { id: 'ml_soft_47', level: 'soft', text: 'Qui pourrait refuser un plat dans un restaurant et commander le même chez lui via Uber Eats 1h après ?' },
  { id: 'ml_soft_48', level: 'soft', text: 'Qui pourrait snacker en faisant les courses et ne pas déclarer tout à la caisse ?' },
  { id: 'ml_soft_49', level: 'soft', text: 'Qui pourrait faire croire qu\'il a cuisiné alors qu\'il a juste réchauffé un plat préparé ?' },
  { id: 'ml_soft_50', level: 'soft', text: 'Qui pourrait avoir un placard entier de nourriture et déclarer "ya rien à manger" ?' },

  // Travail & études
  { id: 'ml_soft_51', level: 'soft', text: 'Qui pourrait s\'endormir en réunion et faire semblant de prendre des notes ?' },
  { id: 'ml_soft_52', level: 'soft', text: 'Qui pourrait remettre un devoir/rapport à la dernière seconde littéralement ?' },
  { id: 'ml_soft_53', level: 'soft', text: 'Qui pourrait "travailler depuis chez lui" en faisant 30 minutes de boulot sur 8 heures ?' },
  { id: 'ml_soft_54', level: 'soft', text: 'Qui pourrait oublier qu\'il a un exam/entretien le lendemain ?' },
  { id: 'ml_soft_55', level: 'soft', text: 'Qui pourrait arriver systématiquement en retard à tout, sauf aux apéros ?' },
  { id: 'ml_soft_56', level: 'soft', text: 'Qui pourrait demander à ChatGPT de rédiger un email "professionnel" de 2 lignes ?' },
  { id: 'ml_soft_57', level: 'soft', text: 'Qui pourrait mentir sur ce qu\'il a fait le week-end pour paraître plus intéressant au bureau ?' },
  { id: 'ml_soft_58', level: 'soft', text: 'Qui pourrait gérer toute sa to-do list en "déplaçant" chaque tâche au lendemain ?' },
  { id: 'ml_soft_59', level: 'soft', text: 'Qui pourrait passer 1h à organiser son bureau plutôt que de travailler ?' },
  { id: 'ml_soft_60', level: 'soft', text: 'Qui pourrait avoir son bureau avec 47 onglets ouverts dont il n\'a utilisé aucun ?' },

  // Habitudes bizarres
  { id: 'ml_soft_61', level: 'soft', text: 'Qui pourrait parler à ses plantes ou à ses animaux comme si c\'était des humains ?' },
  { id: 'ml_soft_62', level: 'soft', text: 'Qui pourrait garder des emballages de cadeaux "au cas où" depuis 5 ans ?' },
  { id: 'ml_soft_63', level: 'soft', text: 'Qui pourrait réécouter la même chanson en boucle pendant 3 jours ?' },
  { id: 'ml_soft_64', level: 'soft', text: 'Qui pourrait pleurer devant un film qu\'il a déjà vu 5 fois ?' },
  { id: 'ml_soft_65', level: 'soft', text: 'Qui pourrait chanter faux à tue-tête dans sa voiture et s\'arrêter net quand il voit quelqu\'un ?' },
  { id: 'ml_soft_66', level: 'soft', text: 'Qui pourrait avoir une peluche ou un objet fétiche qu\'il cache à tout le monde ?' },
  { id: 'ml_soft_67', level: 'soft', text: 'Qui pourrait se parler à voix haute quand il est seul chez lui ?' },
  { id: 'ml_soft_68', level: 'soft', text: 'Qui pourrait faire un plan détaillé pour rien faire et s\'en sentir fier ?' },
  { id: 'ml_soft_69', level: 'soft', text: 'Qui pourrait googler les symptômes d\'un rhume et conclure qu\'il a une maladie grave ?' },
  { id: 'ml_soft_70', level: 'soft', text: 'Qui pourrait refuser d\'admettre être perdu et continuer dans la mauvaise direction ?' },

  // En société & sorties
  { id: 'ml_soft_71', level: 'soft', text: 'Qui pourrait s\'endormir le premier en pleine soirée ?' },
  { id: 'ml_soft_72', level: 'soft', text: 'Qui pourrait commander au resto et demander ensuite ce qu\'il a commandé ?' },
  { id: 'ml_soft_73', level: 'soft', text: 'Qui pourrait changer d\'avis sur le restaurant après 20 minutes de trajet ?' },
  { id: 'ml_soft_74', level: 'soft', text: 'Qui pourrait toujours arriver en retard mais avoir une excuse différente à chaque fois ?' },
  { id: 'ml_soft_75', level: 'soft', text: 'Qui pourrait prétendre avoir déjà vu un film qu\'il n\'a jamais vu pour pas avoir l\'air largué ?' },
  { id: 'ml_soft_76', level: 'soft', text: 'Qui pourrait zapper le film que tout le monde avait choisi parce qu\'il le trouvait mauvais ?' },
  { id: 'ml_soft_77', level: 'soft', text: 'Qui pourrait s\'ajouter lui-même dans un groupe WhatsApp qu\'il avait quitté ?' },
  { id: 'ml_soft_78', level: 'soft', text: 'Qui pourrait emprunter un truc sans le rendre et le garder comme le sien ?' },
  { id: 'ml_soft_79', level: 'soft', text: 'Qui pourrait faire semblant de chercher son portefeuille pour que quelqu\'un d\'autre paye ?' },
  { id: 'ml_soft_80', level: 'soft', text: 'Qui pourrait se vanter d\'un régime qu\'il abandonne le soir même ?' },

  // Caractère & ego
  { id: 'ml_soft_81', level: 'soft', text: 'Qui pourrait googler son propre nom pour voir ce qui sort ?' },
  { id: 'ml_soft_82', level: 'soft', text: 'Qui pourrait refaire une photo 20 fois pour avoir "l\'air naturel" ?' },
  { id: 'ml_soft_83', level: 'soft', text: 'Qui pourrait relire sa propre conversation après l\'avoir envoyée pour voir si elle est bien ?' },
  { id: 'ml_soft_84', level: 'soft', text: 'Qui pourrait toujours commencer ses phrases par "moi, j\'aurais fait autrement" ?' },
  { id: 'ml_soft_85', level: 'soft', text: 'Qui pourrait préparer un discours imaginaire pour un conflit qui n\'aura probablement jamais lieu ?' },
  { id: 'ml_soft_86', level: 'soft', text: 'Qui pourrait passer 1 heure sur une caption Instagram de 3 mots ?' },
  { id: 'ml_soft_87', level: 'soft', text: 'Qui pourrait se trouver moins bien en photo que dans la vraie vie ?' },
  { id: 'ml_soft_88', level: 'soft', text: 'Qui pourrait s\'énerver tout seul en rejouant une dispute passée dans sa tête ?' },
  { id: 'ml_soft_89', level: 'soft', text: 'Qui pourrait acheter un truc qu\'il avait déjà mais avait oublié ?' },
  { id: 'ml_soft_90', level: 'soft', text: 'Qui pourrait mentionner son régime/sport dans toutes les conversations ?' },

  // Divers & inclassables
  { id: 'ml_soft_91', level: 'soft', text: 'Qui pourrait lire la fin d\'un livre avant de le finir pour savoir si ça vaut le coup ?' },
  { id: 'ml_soft_92', level: 'soft', text: 'Qui pourrait regarder le prix sur la carte et commander "en fonction" ?' },
  { id: 'ml_soft_93', level: 'soft', text: 'Qui pourrait demander à tout le monde son avis et finalement faire ce qu\'il voulait dès le départ ?' },
  { id: 'ml_soft_94', level: 'soft', text: 'Qui pourrait s\'énerver contre la télé ou un jeu vidéo en criant ?' },
  { id: 'ml_soft_95', level: 'soft', text: 'Qui pourrait payer un abonnement de salle de sport sans jamais y aller ?' },
  { id: 'ml_soft_96', level: 'soft', text: 'Qui pourrait voir un chat dans la rue et lui parler en faisant des bruits bizarres ?' },
  { id: 'ml_soft_97', level: 'soft', text: 'Qui pourrait acheter 3 mêmes t-shirts noirs en pensant que c\'est différent ?' },
  { id: 'ml_soft_98', level: 'soft', text: 'Qui pourrait oublier qu\'il avait mis quelque chose dans le four ?' },
  { id: 'ml_soft_99', level: 'soft', text: 'Qui pourrait faire semblant de ne pas voir quelqu\'un dans la rue pour éviter la conversation ?' },
  { id: 'ml_soft_100', level: 'soft', text: 'Qui pourrait pleurer plus fort si quelqu\'un vient le consoler ?' },

  // ─── HARD (150) ────────────────────────────────────────────────────────────

  // Alcool & soirées
  { id: 'ml_hard_1',  level: 'hard', text: 'Qui pourrait appeler son ex en pleurant après 3 verres de trop ?' },
  { id: 'ml_hard_2',  level: 'hard', text: 'Qui pourrait être le premier à vomir après un concours de shots ?' },
  { id: 'ml_hard_3',  level: 'hard', text: 'Qui pourrait finir la soirée en train de danser sur les tables (ou finir torse nu) ?' },
  { id: 'ml_hard_4',  level: 'hard', text: 'Qui pourrait se réveiller dans une ville inconnue sans savoir comment il est arrivé là ?' },
  { id: 'ml_hard_5',  level: 'hard', text: 'Qui pourrait boire dans le verre de tout le monde sans demander ?' },
  { id: 'ml_hard_6',  level: 'hard', text: 'Qui pourrait commander une bouteille entière "pour le groupe" et la finir presque seul ?' },
  { id: 'ml_hard_7',  level: 'hard', text: 'Qui pourrait perdre ses chaussures en soirée et continuer pieds nus ?' },
  { id: 'ml_hard_8',  level: 'hard', text: 'Qui pourrait s\'endormir dans les toilettes d\'un bar ?' },
  { id: 'ml_hard_9',  level: 'hard', text: 'Qui pourrait passer du "je bois rien ce soir" à "c\'est moi le plus bourré" en 1 heure ?' },
  { id: 'ml_hard_10', level: 'hard', text: 'Qui pourrait se retrouver à chialer à 3h du mat en disant "vous comprenez pas ma vie" ?' },
  { id: 'ml_hard_11', level: 'hard', text: 'Qui pourrait faire le mort dans son canapé pour éviter de rentrer ?' },
  { id: 'ml_hard_12', level: 'hard', text: 'Qui pourrait mélanger tous les alcools et prétendre que "ça va aller" ?' },
  { id: 'ml_hard_13', level: 'hard', text: 'Qui pourrait commander des shots que personne n\'a demandé "pour tout le monde" ?' },
  { id: 'ml_hard_14', level: 'hard', text: 'Qui pourrait faire une chute mémorable sur la piste de danse ?' },
  { id: 'ml_hard_15', level: 'hard', text: 'Qui pourrait se réveiller avec des photos dans son téléphone dont il n\'a aucun souvenir ?' },

  // Comportements en soirée
  { id: 'ml_hard_16', level: 'hard', text: 'Qui pourrait draguer quelqu\'un qui est clairement venu avec un/une partenaire ?' },
  { id: 'ml_hard_17', level: 'hard', text: 'Qui pourrait passer toute la soirée sur son téléphone à texter quelqu\'un qui n\'est pas là ?' },
  { id: 'ml_hard_18', level: 'hard', text: 'Qui pourrait ramener quelqu\'un chez lui que personne n\'avait jamais vu avant ?' },
  { id: 'ml_hard_19', level: 'hard', text: 'Qui pourrait lancer un ragot et faire semblant d\'être étonné quand ça fait le tour ?' },
  { id: 'ml_hard_20', level: 'hard', text: 'Qui pourrait disparaître de la soirée sans prévenir personne ?' },
  { id: 'ml_hard_21', level: 'hard', text: 'Qui pourrait faire un discours non demandé qui met tout le monde mal à l\'aise ?' },
  { id: 'ml_hard_22', level: 'hard', text: 'Qui pourrait monopoliser l\'enceinte bluetooth et ne passer que ses sons ?' },
  { id: 'ml_hard_23', level: 'hard', text: 'Qui pourrait commencer une bagarre verbale pour une raison stupide ?' },
  { id: 'ml_hard_24', level: 'hard', text: 'Qui pourrait être encore debout à 7h du mat alors que tout le monde est parti ?' },
  { id: 'ml_hard_25', level: 'hard', text: 'Qui pourrait casser ou abîmer quelque chose chez son hôte et ne pas le dire ?' },

  // Drague & vie amoureuse
  { id: 'ml_hard_26', level: 'hard', text: 'Qui pourrait mentir sur son âge ou son métier pour draguer en soirée ?' },
  { id: 'ml_hard_27', level: 'hard', text: 'Qui pourrait envoyer un texto de "t\'es rentré bien ?" en espérant clairement autre chose ?' },
  { id: 'ml_hard_28', level: 'hard', text: 'Qui pourrait embrasser quelqu\'un et prétendre le lendemain que c\'était "l\'alcool" ?' },
  { id: 'ml_hard_29', level: 'hard', text: 'Qui pourrait avoir un crush sur quelqu\'un dans ce groupe sans jamais l\'avoir dit ?' },
  { id: 'ml_hard_30', level: 'hard', text: 'Qui pourrait garder des textos d\'ex "au cas où" alors qu\'il est en couple ?' },
  { id: 'ml_hard_31', level: 'hard', text: 'Qui pourrait se lancer dans un make-out session dans un coin de soirée ?' },
  { id: 'ml_hard_32', level: 'hard', text: 'Qui pourrait envoyer un vocal très compromettant à la mauvaise personne ?' },
  { id: 'ml_hard_33', level: 'hard', text: 'Qui pourrait stalker l\'ex de son ex pour "savoir" ?' },
  { id: 'ml_hard_34', level: 'hard', text: 'Qui pourrait revenir avec un ex juste parce qu\'il s\'ennuyait ?' },
  { id: 'ml_hard_35', level: 'hard', text: 'Qui pourrait se retrouver coincé dans un plan à deux non désiré parce qu\'il a trop bien été gentil ?' },
  { id: 'ml_hard_36', level: 'hard', text: 'Qui pourrait bloquer quelqu\'un sur tous les réseaux plutôt que d\'avoir la conversation ?' },
  { id: 'ml_hard_37', level: 'hard', text: 'Qui pourrait ghosting total quelqu\'un après 3 semaines de flirt ?' },
  { id: 'ml_hard_38', level: 'hard', text: 'Qui pourrait envoyer "tu penses à moi ?" en sachant très bien que la réponse sera oui ?' },
  { id: 'ml_hard_39', level: 'hard', text: 'Qui pourrait utiliser "j\'ai besoin d\'aide pour un truc" comme excuse pour voir quelqu\'un qu\'il drague ?' },
  { id: 'ml_hard_40', level: 'hard', text: 'Qui pourrait vérifier si son/sa ex est passé(e) en ligne après l\'avoir bloqué ?' },

  // Dossiers & comportements douteux
  { id: 'ml_hard_41', level: 'hard', text: 'Qui pourrait secrètement juger les goûts vestimentaires de tout le monde ici ?' },
  { id: 'ml_hard_42', level: 'hard', text: 'Qui pourrait avoir fouillé dans le téléphone de quelqu\'un sans permission ?' },
  { id: 'ml_hard_43', level: 'hard', text: 'Qui pourrait avoir inventé une maladie pour ne pas aller quelque part ?' },
  { id: 'ml_hard_44', level: 'hard', text: 'Qui pourrait avoir menti sur son salaire, en plus ou en moins, selon l\'interlocuteur ?' },
  { id: 'ml_hard_45', level: 'hard', text: 'Qui pourrait rapporter une conversation privée à quelqu\'un qui ne devait pas la connaître ?' },
  { id: 'ml_hard_46', level: 'hard', text: 'Qui pourrait se mettre en mode "j\'entends tout" dans les conversations des autres sans participer ?' },
  { id: 'ml_hard_47', level: 'hard', text: 'Qui pourrait savoir un secret de quelqu\'un dans ce groupe et le garder pour ce soir ?' },
  { id: 'ml_hard_48', level: 'hard', text: 'Qui pourrait avoir fait une chose dont il/elle ne serait pas fier(e) si ses parents le savaient ?' },
  { id: 'ml_hard_49', level: 'hard', text: 'Qui pourrait prendre le crédit d\'une idée ou d\'un travail de quelqu\'un d\'autre ?' },
  { id: 'ml_hard_50', level: 'hard', text: 'Qui pourrait inventer une histoire pour paraître plus intéressant en soirée ?' },

  // Choix moraux & situations limites
  { id: 'ml_hard_51', level: 'hard', text: 'Qui pourrait choisir l\'argent plutôt que l\'amitié si les deux entraient en conflit ?' },
  { id: 'ml_hard_52', level: 'hard', text: 'Qui pourrait lire les messages de son/sa partenaire s\'il/elle en avait l\'occasion ?' },
  { id: 'ml_hard_53', level: 'hard', text: 'Qui pourrait sortir avec quelqu\'un juste pour ses invitations et ses bons restos ?' },
  { id: 'ml_hard_54', level: 'hard', text: 'Qui pourrait simuler une urgence pour sortir d\'un mauvais date ?' },
  { id: 'ml_hard_55', level: 'hard', text: 'Qui pourrait accepter une faveur et ne jamais la rendre ?' },
  { id: 'ml_hard_56', level: 'hard', text: 'Qui pourrait avoir participé à un ragot qu\'il savait faux ?' },
  { id: 'ml_hard_57', level: 'hard', text: 'Qui pourrait avoir pris une décision importante sous l\'influence de quelqu\'un d\'autre ?' },
  { id: 'ml_hard_58', level: 'hard', text: 'Qui pourrait trahir une confidence si ça l\'arrangeait vraiment ?' },
  { id: 'ml_hard_59', level: 'hard', text: 'Qui pourrait avoir dit du mal d\'une personne absente à cette soirée ?' },
  { id: 'ml_hard_60', level: 'hard', text: 'Qui pourrait avoir fait un choix honteux qu\'il a caché pendant des mois ?' },

  // Le croustillant pur
  { id: 'ml_hard_61', level: 'hard', text: 'Qui pourrait avoir eu un plan cul qu\'il a gardé secret de tout le groupe ?' },
  { id: 'ml_hard_62', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un le soir même de leur rencontre ?' },
  { id: 'ml_hard_63', level: 'hard', text: 'Qui pourrait avoir eu un crush sur un ami en couple sans jamais rien dire ?' },
  { id: 'ml_hard_64', level: 'hard', text: 'Qui pourrait avoir embrassé deux personnes différentes dans la même soirée ?' },
  { id: 'ml_hard_65', level: 'hard', text: 'Qui pourrait avoir utilisé quelqu\'un juste pour ne pas être seul(e) ?' },
  { id: 'ml_hard_66', level: 'hard', text: 'Qui pourrait avoir kiffé quelqu\'un dans ce groupe à un moment donné ?' },
  { id: 'ml_hard_67', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un qu\'il/elle n\'aurait jamais avoué ?' },
  { id: 'ml_hard_68', level: 'hard', text: 'Qui pourrait avoir flirté avec quelqu\'un juste pour voir jusqu\'où ça allait aller ?' },
  { id: 'ml_hard_69', level: 'hard', text: 'Qui pourrait avoir envoyé un nude et regretté instantanément ?' },
  { id: 'ml_hard_70', level: 'hard', text: 'Qui pourrait avoir fait semblant d\'être plus sage qu\'il/elle ne l\'est vraiment ?' },

  // Le passé & les dossiers
  { id: 'ml_hard_71', level: 'hard', text: 'Qui pourrait avoir une phase de sa vie dont il/elle ne parle jamais et qui serait gênante à révéler ?' },
  { id: 'ml_hard_72', level: 'hard', text: 'Qui pourrait avoir une photo ou une vidéo embarrassante de lui/elle quelque part sur internet ?' },
  { id: 'ml_hard_73', level: 'hard', text: 'Qui pourrait avoir eu un pseudo ou une phase emo/cosplay/autre qu\'il renie aujourd\'hui ?' },
  { id: 'ml_hard_74', level: 'hard', text: 'Qui pourrait avoir fait une erreur de jugement monumentale dont il a mis longtemps à se remettre ?' },
  { id: 'ml_hard_75', level: 'hard', text: 'Qui pourrait avoir eu un comportement dont il/elle a honte si on lui remontrait en vidéo ?' },
  { id: 'ml_hard_76', level: 'hard', text: 'Qui pourrait avoir eu un plan à trois (ou plus) ?' },
  { id: 'ml_hard_77', level: 'hard', text: 'Qui pourrait avoir dragué le/la meilleur(e) ami(e) de son/sa ex ?' },
  { id: 'ml_hard_78', level: 'hard', text: 'Qui pourrait avoir eu un surnom honteux au lycée ?' },
  { id: 'ml_hard_79', level: 'hard', text: 'Qui pourrait avoir fait quelque chose d\'illégal et ne s\'être jamais fait prendre ?' },
  { id: 'ml_hard_80', level: 'hard', text: 'Qui pourrait avoir passé une nuit en garde à vue ou s\'en être approché de peu ?' },

  // Confessions & vérités
  { id: 'ml_hard_81', level: 'hard', text: 'Qui pourrait avoir une dépendance secrète (sucre, shopping, réseaux...) qu\'il cache bien ?' },
  { id: 'ml_hard_82', level: 'hard', text: 'Qui pourrait avoir dépensé une somme qu\'il regrette encore pour une personne qui ne le méritait pas ?' },
  { id: 'ml_hard_83', level: 'hard', text: 'Qui pourrait avoir pleuré en regardant un match de foot ou un film qu\'il trouvait nul ?' },
  { id: 'ml_hard_84', level: 'hard', text: 'Qui pourrait avoir abandonné un ami dans une mauvaise situation pour éviter les ennuis ?' },
  { id: 'ml_hard_85', level: 'hard', text: 'Qui pourrait avoir fait croire qu\'il était occupé juste pour éviter une personne du groupe ?' },
  { id: 'ml_hard_86', level: 'hard', text: 'Qui pourrait avoir caché une relation parce qu\'il avait honte de la personne ?' },
  { id: 'ml_hard_87', level: 'hard', text: 'Qui pourrait avoir trompé quelqu\'un (même à moitié) et ne l\'avoir jamais dit ?' },
  { id: 'ml_hard_88', level: 'hard', text: 'Qui pourrait avoir été la raison d\'une rupture sans le dire ?' },
  { id: 'ml_hard_89', level: 'hard', text: 'Qui pourrait avoir fait une chose pour rendre quelqu\'un jaloux alors qu\'il n\'en avait rien à faire de lui ?' },
  { id: 'ml_hard_90', level: 'hard', text: 'Qui pourrait avoir dit "je t\'aime" sans vraiment le penser ?' },

  // Finance & deals
  { id: 'ml_hard_91', level: 'hard', text: 'Qui pourrait avoir "oublié" de rembourser une dette à un ami ?' },
  { id: 'ml_hard_92', level: 'hard', text: 'Qui pourrait avoir emprunté de l\'argent sans jamais avoir l\'intention de le rendre ?' },
  { id: 'ml_hard_93', level: 'hard', text: 'Qui pourrait avoir déclaré moins que ce qu\'il gagne pour bénéficier d\'un avantage ?' },
  { id: 'ml_hard_94', level: 'hard', text: 'Qui pourrait avoir fait un retour frauduleux pour récupérer son argent ?' },
  { id: 'ml_hard_95', level: 'hard', text: 'Qui pourrait avoir profité d\'une erreur en sa faveur sans la signaler ?' },
  { id: 'ml_hard_96', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de payer pour lui avec une excuse bidon ?' },
  { id: 'ml_hard_97', level: 'hard', text: 'Qui pourrait avoir dépensé son loyer dans une soirée ?' },
  { id: 'ml_hard_98', level: 'hard', text: 'Qui pourrait avoir misé de l\'argent sur quelque chose de stupide et perdu ?' },
  { id: 'ml_hard_99', level: 'hard', text: 'Qui pourrait avoir fait du cashback ou un bon plan limite légal pour s\'en sortir ?' },
  { id: 'ml_hard_100', level: 'hard', text: 'Qui pourrait avoir menti à ses parents sur où partait l\'argent qu\'ils lui donnaient ?' },

  // Honte & situations catastrophiques
  { id: 'ml_hard_101', level: 'hard', text: 'Qui pourrait avoir fait une scène dans un lieu public ?' },
  { id: 'ml_hard_102', level: 'hard', text: 'Qui pourrait avoir insulté quelqu\'un puis fait semblant que c\'était une blague ?' },
  { id: 'ml_hard_103', level: 'hard', text: 'Qui pourrait avoir été viré, plaqué ou mis à la porte en moins de 3 minutes ?' },
  { id: 'ml_hard_104', level: 'hard', text: 'Qui pourrait avoir échoué un examen ou entretien à cause d\'une gueule de bois ?' },
  { id: 'ml_hard_105', level: 'hard', text: 'Qui pourrait avoir manqué un avion, un train ou un RDV important par flemme ?' },
  { id: 'ml_hard_106', level: 'hard', text: 'Qui pourrait avoir volé la scène lors d\'une soirée organisée par quelqu\'un d\'autre ?' },
  { id: 'ml_hard_107', level: 'hard', text: 'Qui pourrait avoir fait une chose en soirée dont il/elle n\'a parlé à personne depuis ?' },
  { id: 'ml_hard_108', level: 'hard', text: 'Qui pourrait avoir pris la mauvaise décision de sa vie sous l\'influence d\'un groupe ?' },
  { id: 'ml_hard_109', level: 'hard', text: 'Qui pourrait avoir été expulsé d\'un lieu (bar, club, hôtel, transport...) ?' },
  { id: 'ml_hard_110', level: 'hard', text: 'Qui pourrait avoir accidentellement mis le feu (ou failli) à quelque chose ?' },

  // Séduction & manipulation
  { id: 'ml_hard_111', level: 'hard', text: 'Qui pourrait jouer la carte "j\'ai besoin de toi" pour attirer l\'attention de quelqu\'un ?' },
  { id: 'ml_hard_112', level: 'hard', text: 'Qui pourrait avoir utilisé quelqu\'un comme plan B en cas de plan A raté ?' },
  { id: 'ml_hard_113', level: 'hard', text: 'Qui pourrait donner de faux espoirs sans jamais avoir l\'intention de concrétiser ?' },
  { id: 'ml_hard_114', level: 'hard', text: 'Qui pourrait utiliser la jalousie comme arme de séduction ?' },
  { id: 'ml_hard_115', level: 'hard', text: 'Qui pourrait avoir entretenu une ambiguïté avec quelqu\'un juste pour son égo ?' },
  { id: 'ml_hard_116', level: 'hard', text: 'Qui pourrait flirter avec les ami(e)s de son/sa partenaire "juste pour voir" ?' },
  { id: 'ml_hard_117', level: 'hard', text: 'Qui pourrait avoir gardé un/une ex "en attente" pendant qu\'il/elle explorrait d\'autres options ?' },
  { id: 'ml_hard_118', level: 'hard', text: 'Qui pourrait avoir fait semblant d\'être plus intéressé qu\'il/elle ne l\'est pour ne pas blesser ?' },
  { id: 'ml_hard_119', level: 'hard', text: 'Qui pourrait avoir profité de quelqu\'un qui avait clairement un faible pour lui/elle ?' },
  { id: 'ml_hard_120', level: 'hard', text: 'Qui pourrait avoir fait revenir un/une ex et recommencer à l\'éviter juste après ?' },

  // Comportements en groupe
  { id: 'ml_hard_121', level: 'hard', text: 'Qui pourrait toujours rentrer chez lui avec quelqu\'un à la fin de la soirée ?' },
  { id: 'ml_hard_122', level: 'hard', text: 'Qui pourrait saboter un plan de groupe parce que ça ne l\'arrangeait pas ?' },
  { id: 'ml_hard_123', level: 'hard', text: 'Qui pourrait être le premier à "balance" un pote quand ça l\'arrange ?' },
  { id: 'ml_hard_124', level: 'hard', text: 'Qui pourrait avoir fait une chose honteuse en groupe dont il a maintenant une photo compromettante ?' },
  { id: 'ml_hard_125', level: 'hard', text: 'Qui pourrait écouter et participer à une conversation qu\'il n\'était pas censé entendre ?' },
  { id: 'ml_hard_126', level: 'hard', text: 'Qui pourrait avoir mis un ami dans l\'embarras pour faire rire les autres ?' },
  { id: 'ml_hard_127', level: 'hard', text: 'Qui pourrait avoir raconté des secrets d\'un pote sous couvert d\'anecdote ?' },
  { id: 'ml_hard_128', level: 'hard', text: 'Qui pourrait avoir joué double jeu entre deux groupes d\'amis ?' },
  { id: 'ml_hard_129', level: 'hard', text: 'Qui pourrait parler différemment selon les personnes à qui il/elle s\'adresse ?' },
  { id: 'ml_hard_130', level: 'hard', text: 'Qui pourrait avoir retourné un groupe contre quelqu\'un pour une raison égoïste ?' },

  // Vie numérique & excès
  { id: 'ml_hard_131', level: 'hard', text: 'Qui pourrait avoir créé un faux profil pour voir ce que les gens disaient de lui ?' },
  { id: 'ml_hard_132', level: 'hard', text: 'Qui pourrait avoir stalké quelqu\'un jusqu\'à retrouver l\'endroit exact sur une photo ?' },
  { id: 'ml_hard_133', level: 'hard', text: 'Qui pourrait avoir screenshotté une conversation privée et la montrer à quelqu\'un ?' },
  { id: 'ml_hard_134', level: 'hard', text: 'Qui pourrait avoir fait du catfishing, même une seule fois "pour rigoler" ?' },
  { id: 'ml_hard_135', level: 'hard', text: 'Qui pourrait avoir posté quelque chose en soirée et le regretter le lendemain matin ?' },
  { id: 'ml_hard_136', level: 'hard', text: 'Qui pourrait avoir un double compte Instagram que personne ne connaît ?' },
  { id: 'ml_hard_137', level: 'hard', text: 'Qui pourrait avoir scrollé les réseaux d\'un ex jusqu\'à remonter 3 ans en arrière ?' },
  { id: 'ml_hard_138', level: 'hard', text: 'Qui pourrait avoir répondu à une story de quelqu\'un juste pour ouvrir la porte à une conversation ?' },
  { id: 'ml_hard_139', level: 'hard', text: 'Qui pourrait avoir bloqué quelqu\'un puis créé un faux compte pour continuer à le/la surveiller ?' },
  { id: 'ml_hard_140', level: 'hard', text: 'Qui pourrait avoir exagéré sa vie sur les réseaux jusqu\'à y croire lui-même ?' },

  // Les défis ultimes
  { id: 'ml_hard_141', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un d\'un groupe d\'amis et ne jamais l\'avoir dit ?' },
  { id: 'ml_hard_142', level: 'hard', text: 'Qui pourrait avoir fait un truc en soirée qui lui coûterait sa réputation s\'il était filmé ?' },
  { id: 'ml_hard_143', level: 'hard', text: 'Qui pourrait avoir dansé de façon totalement indécente en pensant que personne ne regardait ?' },
  { id: 'ml_hard_144', level: 'hard', text: 'Qui pourrait avoir eu une aventure lors d\'un séjour ou d\'un voyage de groupe ?' },
  { id: 'ml_hard_145', level: 'hard', text: 'Qui pourrait avoir besoin d\'une soirée entière pour raconter tout ce qu\'il a fait ?' },
  { id: 'ml_hard_146', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de faire quelque chose de stupide juste pour le film ?' },
  { id: 'ml_hard_147', level: 'hard', text: 'Qui pourrait avoir une histoire de soirée tellement folle qu\'il refuse encore d\'en parler ?' },
  { id: 'ml_hard_148', level: 'hard', text: 'Qui pourrait avoir pris une photo ou une vidéo de quelqu\'un sans consentement ?' },
  { id: 'ml_hard_149', level: 'hard', text: 'Qui pourrait avoir eu un pari ou un défi qui a mal tourné et gardé ça pour lui ?' },
  { id: 'ml_hard_150', level: 'hard', text: 'Qui pourrait avoir fait le plus de dégâts dans une soirée et s\'en être sorti sans punition ?' },

  // ─── VAGUE 2 — SOFT (101–200) ──────────────────────────────────────────────

  // Transports & conduite
  { id: 'ml_soft_101', level: 'soft', text: 'Qui pourrait conduire 20 minutes dans la mauvaise direction parce qu\'il refuse d\'admettre que le GPS a raison ?' },
  { id: 'ml_soft_102', level: 'soft', text: 'Qui pourrait tourner en rond 30 minutes plutôt que de payer un parking ?' },
  { id: 'ml_soft_103', level: 'soft', text: 'Qui pourrait s\'endormir dans les transports en commun et rater son arrêt de 5 stations ?' },
  { id: 'ml_soft_104', level: 'soft', text: 'Qui pourrait oublier où il a garé sa voiture et appeler la fourrière avant de la retrouver ?' },
  { id: 'ml_soft_105', level: 'soft', text: 'Qui pourrait klaxonner un conducteur et réaliser que c\'est quelqu\'un qu\'il connaît ?' },
  { id: 'ml_soft_106', level: 'soft', text: 'Qui pourrait griller un feu rouge en jurant que "c\'était vraiment orange" ?' },
  { id: 'ml_soft_107', level: 'soft', text: 'Qui pourrait promettre de venir chercher quelqu\'un et arriver 45 minutes en retard ?' },
  { id: 'ml_soft_108', level: 'soft', text: 'Qui pourrait monter dans le mauvais bus et faire tout le trajet avant de s\'en rendre compte ?' },
  { id: 'ml_soft_109', level: 'soft', text: 'Qui pourrait avoir une série de petites bosses et rayures sur sa voiture dont il ne se souvient pas ?' },
  { id: 'ml_soft_110', level: 'soft', text: 'Qui pourrait rater l\'embarquement d\'un avion à cause d\'un truc complètement évitable ?' },

  // Shopping & achats impulsifs
  { id: 'ml_soft_111', level: 'soft', text: 'Qui pourrait acheter un truc en soldes dont il n\'a absolument pas besoin juste parce que c\'est "une bonne affaire" ?' },
  { id: 'ml_soft_112', level: 'soft', text: 'Qui pourrait passer 2h à comparer les prix pour finalement acheter le premier truc qu\'il avait vu ?' },
  { id: 'ml_soft_113', level: 'soft', text: 'Qui pourrait retourner un article en prétendant qu\'il a un défaut alors qu\'il a juste changé d\'avis ?' },
  { id: 'ml_soft_114', level: 'soft', text: 'Qui pourrait acheter le même article deux fois parce qu\'il avait oublié qu\'il l\'avait déjà ?' },
  { id: 'ml_soft_115', level: 'soft', text: 'Qui pourrait commander en ligne puis aller au magasin acheter la même chose parce qu\'il est pas patient ?' },
  { id: 'ml_soft_116', level: 'soft', text: 'Qui pourrait avoir des vêtements avec les étiquettes encore dessus depuis 6 mois ?' },
  { id: 'ml_soft_117', level: 'soft', text: 'Qui pourrait se faire embarquer par un vendeur et acheter un truc 3× plus cher que prévu ?' },
  { id: 'ml_soft_118', level: 'soft', text: 'Qui pourrait acheter un livre, le lire 5 pages, et ne plus jamais le toucher ?' },
  { id: 'ml_soft_119', level: 'soft', text: 'Qui pourrait claquer son budget "courses" en n\'achetant que de la nourriture plaisir ?' },
  { id: 'ml_soft_120', level: 'soft', text: 'Qui pourrait justifier chaque achat impulsif avec une logique irréfutable sur le moment ?' },

  // Famille & entourage
  { id: 'ml_soft_121', level: 'soft', text: 'Qui pourrait décrocher l\'appel de ses parents en pilote automatique et regretter immédiatement ?' },
  { id: 'ml_soft_122', level: 'soft', text: 'Qui pourrait passer 20 minutes à écouter les conseils de sa famille pour faire exactement l\'inverse ?' },
  { id: 'ml_soft_123', level: 'soft', text: 'Qui pourrait avoir un surnom de famille ridicule que personne dans cette salle ne connaît ?' },
  { id: 'ml_soft_124', level: 'soft', text: 'Qui pourrait faire appel à ses parents pour régler un problème qu\'un adulte devrait gérer seul ?' },
  { id: 'ml_soft_125', level: 'soft', text: 'Qui pourrait éviter les appels familiaux jusqu\'à ce que ça devienne urgent ?' },
  { id: 'ml_soft_126', level: 'soft', text: 'Qui pourrait prétexer être malade pour éviter un repas de famille ?' },
  { id: 'ml_soft_127', level: 'soft', text: 'Qui pourrait avoir encore ses parents qui font sa lessive quand il passe les voir ?' },
  { id: 'ml_soft_128', level: 'soft', text: 'Qui pourrait se plaindre de sa famille à tout le monde mais la défendre dès que quelqu\'un la critique ?' },
  { id: 'ml_soft_129', level: 'soft', text: 'Qui pourrait rappeler ses parents uniquement quand il a besoin de quelque chose ?' },
  { id: 'ml_soft_130', level: 'soft', text: 'Qui pourrait régaler tout le monde de sa dernière dispute familiale comme si c\'était un feuilleton ?' },

  // Santé & sport au quotidien
  { id: 'ml_soft_131', level: 'soft', text: 'Qui pourrait s\'inscrire à un défi sportif, commencer 3 jours, et abandonner silencieusement ?' },
  { id: 'ml_soft_132', level: 'soft', text: 'Qui pourrait se lever pour faire du sport, regarder son lit et décider que ça peut attendre demain ?' },
  { id: 'ml_soft_133', level: 'soft', text: 'Qui pourrait acheter du matériel de sport qui décore maintenant son appartement ?' },
  { id: 'ml_soft_134', level: 'soft', text: 'Qui pourrait "courir" un trajet de 200m pour se compter un effort physique ?' },
  { id: 'ml_soft_135', level: 'soft', text: 'Qui pourrait manger sainement toute la semaine et tout compenser en un seul repas du week-end ?' },
  { id: 'ml_soft_136', level: 'soft', text: 'Qui pourrait se soigner à base de "ça va passer" jusqu\'à ce que ça empire vraiment ?' },
  { id: 'ml_soft_137', level: 'soft', text: 'Qui pourrait porter des vêtements de sport toute la journée sans jamais faire de sport ?' },
  { id: 'ml_soft_138', level: 'soft', text: 'Qui pourrait calculer les calories d\'un repas pour ensuite prendre deux desserts ?' },
  { id: 'ml_soft_139', level: 'soft', text: 'Qui pourrait se fixer des objectifs sportifs de janvier à janvier sans jamais les tenir ?' },
  { id: 'ml_soft_140', level: 'soft', text: 'Qui pourrait se plaindre d\'une douleur imaginaire jusqu\'à ce qu\'on s\'inquiète vraiment pour lui ?' },

  // Musique & culture coupable
  { id: 'ml_soft_141', level: 'soft', text: 'Qui pourrait chanter les paroles complètement fausses d\'une chanson avec une totale confiance ?' },
  { id: 'ml_soft_142', level: 'soft', text: 'Qui pourrait être fan honteux d\'un artiste qu\'il critique ouvertement en public ?' },
  { id: 'ml_soft_143', level: 'soft', text: 'Qui pourrait danser seul chez lui avec une chorégraphie qu\'il n\'oserait jamais faire en société ?' },
  { id: 'ml_soft_144', level: 'soft', text: 'Qui pourrait pleurer devant un clip ou une chanson "sans raison particulière" ?' },
  { id: 'ml_soft_145', level: 'soft', text: 'Qui pourrait encore écouter des sons de son adolescence en secret ?' },
  { id: 'ml_soft_146', level: 'soft', text: 'Qui pourrait regarder une émission de télé-réalité en prétendant que "c\'est juste pour le bruit de fond" ?' },
  { id: 'ml_soft_147', level: 'soft', text: 'Qui pourrait fredonner une pub pendant une heure sans s\'en rendre compte ?' },
  { id: 'ml_soft_148', level: 'soft', text: 'Qui pourrait défendre bec et ongles un film objectivement mauvais parce qu\'il l\'aime trop ?' },
  { id: 'ml_soft_149', level: 'soft', text: 'Qui pourrait savoir par cœur tous les dialogues d\'un film qu\'il "n\'a vu qu\'une fois" ?' },
  { id: 'ml_soft_150', level: 'soft', text: 'Qui pourrait suivre les paroles d\'une chanson en langue étrangère avec son propre charabia inventé ?' },

  // Jeux vidéo & tech
  { id: 'ml_soft_151', level: 'soft', text: 'Qui pourrait rage-quit un jeu et revenir 2 minutes après faire comme si rien ne s\'était passé ?' },
  { id: 'ml_soft_152', level: 'soft', text: 'Qui pourrait avoir une bibliothèque de jeux dont 90 % n\'ont jamais été lancés ?' },
  { id: 'ml_soft_153', level: 'soft', text: 'Qui pourrait passer une heure à paramétrer un personnage puis jouer 5 minutes ?' },
  { id: 'ml_soft_154', level: 'soft', text: 'Qui pourrait parler à son ordi ou sa console quand ça marche pas, comme si ça allait changer quelque chose ?' },
  { id: 'ml_soft_155', level: 'soft', text: 'Qui pourrait avoir une batterie externe et ne jamais l\'avoir sur lui quand il en a besoin ?' },
  { id: 'ml_soft_156', level: 'soft', text: 'Qui pourrait regarder des vidéos "comment faire" quelque chose sans jamais le faire ?' },
  { id: 'ml_soft_157', level: 'soft', text: 'Qui pourrait "redémarrer" son ordi comme solution universelle à n\'importe quel problème technique ?' },
  { id: 'ml_soft_158', level: 'soft', text: 'Qui pourrait avoir des câbles en vrac dans un tiroir dont il ne sait plus à quoi servent la moitié ?' },
  { id: 'ml_soft_159', level: 'soft', text: 'Qui pourrait demander à quelqu\'un de regarder une "vidéo rapide" de 25 minutes ?' },
  { id: 'ml_soft_160', level: 'soft', text: 'Qui pourrait avoir téléchargé une appli, l\'utiliser une fois et ne jamais la désinstaller ?' },

  // Voyages & vacances
  { id: 'ml_soft_161', level: 'soft', text: 'Qui pourrait faire une valise la veille et y mettre 3× trop de choses "au cas où" ?' },
  { id: 'ml_soft_162', level: 'soft', text: 'Qui pourrait arriver à l\'aéroport 4 heures à l\'avance "pour être sûr" ?' },
  { id: 'ml_soft_163', level: 'soft', text: 'Qui pourrait visiter une ville et passer la moitié du temps dans des chaînes qu\'il connaît déjà ?' },
  { id: 'ml_soft_164', level: 'soft', text: 'Qui pourrait rentrer de vacances plus fatigué qu\'avant de partir ?' },
  { id: 'ml_soft_165', level: 'soft', text: 'Qui pourrait acheter des souvenirs et les offrir à la mauvaise personne ?' },
  { id: 'ml_soft_166', level: 'soft', text: 'Qui pourrait prendre des centaines de photos en voyage et ne jamais les regarder après ?' },
  { id: 'ml_soft_167', level: 'soft', text: 'Qui pourrait se perdre dans une ville étrangère et refuser de demander son chemin ?' },
  { id: 'ml_soft_168', level: 'soft', text: 'Qui pourrait passer ses vacances à envoyer des stories depuis la plage plutôt qu\'à profiter ?' },
  { id: 'ml_soft_169', level: 'soft', text: 'Qui pourrait rentrer d\'un voyage et passer la semaine à dire à tout le monde combien c\'était mieux là-bas ?' },
  { id: 'ml_soft_170', level: 'soft', text: 'Qui pourrait avoir un guide de voyage jamais ouvert acheté "pour chaque fois que j\'irai" ?' },

  // Mensonges blancs sociaux
  { id: 'ml_soft_171', level: 'soft', text: 'Qui pourrait dire "j\'arrive dans 5 minutes" en n\'étant pas encore habillé chez lui ?' },
  { id: 'ml_soft_172', level: 'soft', text: 'Qui pourrait prétendre avoir lu/vu quelque chose dont tout le monde parle pour ne pas passer pour un ignare ?' },
  { id: 'ml_soft_173', level: 'soft', text: 'Qui pourrait sourire et acquiescer lors d\'une conversation qu\'il n\'a pas suivie du tout ?' },
  { id: 'ml_soft_174', level: 'soft', text: 'Qui pourrait inventer un compliment sur quelque chose qu\'il trouve vraiment nul ?' },
  { id: 'ml_soft_175', level: 'soft', text: 'Qui pourrait prétendre trouver quelqu\'un drôle pendant 1h entière par pure politesse ?' },
  { id: 'ml_soft_176', level: 'soft', text: 'Qui pourrait accepter une invitation qu\'il sait très bien qu\'il n\'honorera jamais ?' },
  { id: 'ml_soft_177', level: 'soft', text: 'Qui pourrait dire "je le ferai ce week-end" depuis plusieurs mois pour la même chose ?' },
  { id: 'ml_soft_178', level: 'soft', text: 'Qui pourrait promettre de rappeler quelqu\'un "dans 2 minutes" et ne le rappeler jamais ?' },
  { id: 'ml_soft_179', level: 'soft', text: 'Qui pourrait prétendre avoir une intolérance alimentaire pour éviter un plat qu\'il n\'aime pas ?' },
  { id: 'ml_soft_180', level: 'soft', text: 'Qui pourrait dire "bien sûr que je suis disponible" et se décommander 2 heures avant ?' },

  // Organisation & espace perso
  { id: 'ml_soft_181', level: 'soft', text: 'Qui pourrait vivre dans un chaos total et savoir exactement où est chaque truc dans ce chaos ?' },
  { id: 'ml_soft_182', level: 'soft', text: 'Qui pourrait empiler les affaires à côté du tiroir plutôt que de les ranger dedans ?' },
  { id: 'ml_soft_183', level: 'soft', text: 'Qui pourrait avoir un tiroir "fourre-tout" qui grossit d\'année en année sans jamais être vidé ?' },
  { id: 'ml_soft_184', level: 'soft', text: 'Qui pourrait passer 30 minutes à "ranger" en cachant tout sous le lit avant une visite ?' },
  { id: 'ml_soft_185', level: 'soft', text: 'Qui pourrait perdre un objet, en racheter un, et retrouver l\'original le lendemain ?' },
  { id: 'ml_soft_186', level: 'soft', text: 'Qui pourrait avoir 15 stylos qui ne marchent pas et les garder quand même "au cas où" ?' },
  { id: 'ml_soft_187', level: 'soft', text: 'Qui pourrait ranger quelque chose "à un endroit sûr" et ne plus jamais retrouver cet endroit ?' },
  { id: 'ml_soft_188', level: 'soft', text: 'Qui pourrait nettoyer son appartement uniquement quand quelqu\'un vient le voir ?' },
  { id: 'ml_soft_189', level: 'soft', text: 'Qui pourrait avoir une boîte mail à 4000 mails non lus et s\'en foutre complètement ?' },
  { id: 'ml_soft_190', level: 'soft', text: 'Qui pourrait avoir un "système de classement" qui ne fait sens qu\'à lui et à personne d\'autre ?' },

  // Divers manies restantes
  { id: 'ml_soft_191', level: 'soft', text: 'Qui pourrait toujours commander la même chose dans tous les restos par peur d\'être déçu ?' },
  { id: 'ml_soft_192', level: 'soft', text: 'Qui pourrait arriver à une soirée costumée sans costume et dire que "l\'ironie c\'est son costume" ?' },
  { id: 'ml_soft_193', level: 'soft', text: 'Qui pourrait rater un épisode d\'une série et la recommencer depuis le début plutôt que de continuer ?' },
  { id: 'ml_soft_194', level: 'soft', text: 'Qui pourrait passer plus de temps à choisir quoi regarder qu\'à regarder quelque chose ?' },
  { id: 'ml_soft_195', level: 'soft', text: 'Qui pourrait utiliser "j\'ai pas dormi" pour justifier toutes ses mauvaises décisions de la journée ?' },
  { id: 'ml_soft_196', level: 'soft', text: 'Qui pourrait inventer des règles de jeu à son avantage quand il est en train de perdre ?' },
  { id: 'ml_soft_197', level: 'soft', text: 'Qui pourrait toujours trouver une logique pour justifier un achat complètement impulsif ?' },
  { id: 'ml_soft_198', level: 'soft', text: 'Qui pourrait mettre des rappels sur son téléphone, les ignorer systématiquement et quand même les garder ?' },
  { id: 'ml_soft_199', level: 'soft', text: 'Qui pourrait toujours promettre "la prochaine fois c\'est moi qui régale" sans que ça arrive jamais ?' },
  { id: 'ml_soft_200', level: 'soft', text: 'Qui pourrait avoir un journal commencé et abandonné après 3 entrées, pour la 5ème fois ?' },

  // ─── VAGUE 2 — HARD (151–350) ──────────────────────────────────────────────

  // Relations toxiques & red flags
  { id: 'ml_hard_151', level: 'hard', text: 'Qui pourrait nier les faits face à quelqu\'un qu\'il a blessé jusqu\'à ce que l\'autre doute lui-même de sa propre mémoire ?' },
  { id: 'ml_hard_152', level: 'hard', text: 'Qui pourrait couper le contact avec quelqu\'un sans explication et trouver ça tout à fait normal ?' },
  { id: 'ml_hard_153', level: 'hard', text: 'Qui pourrait love-bomber quelqu\'un au début puis devenir froid une fois l\'intérêt obtenu ?' },
  { id: 'ml_hard_154', level: 'hard', text: 'Qui pourrait toujours se retrouver "victime" dans chaque histoire qu\'il raconte ?' },
  { id: 'ml_hard_155', level: 'hard', text: 'Qui pourrait surveiller l\'activité de son/sa partenaire sous couvert de "s\'inquiéter pour lui/elle" ?' },
  { id: 'ml_hard_156', level: 'hard', text: 'Qui pourrait utiliser les erreurs passées d\'un proche pour garder le dessus sur lui/elle ?' },
  { id: 'ml_hard_157', level: 'hard', text: 'Qui pourrait faire sentir à quelqu\'un qu\'il doit mériter son attention ?' },
  { id: 'ml_hard_158', level: 'hard', text: 'Qui pourrait minimiser les ressentis des autres en disant "t\'exagères" ou "t\'es trop sensible" ?' },
  { id: 'ml_hard_159', level: 'hard', text: 'Qui pourrait ne jamais s\'excuser en premier et toujours retourner la situation à son avantage ?' },
  { id: 'ml_hard_160', level: 'hard', text: 'Qui pourrait "tester" ses proches pour vérifier leur loyauté sans jamais leur dire qu\'il le fait ?' },
  { id: 'ml_hard_161', level: 'hard', text: 'Qui pourrait comparer son/sa partenaire à son ex en faisant croire que c\'est un compliment ?' },
  { id: 'ml_hard_162', level: 'hard', text: 'Qui pourrait faire la tête pendant des jours en attendant que l\'autre vienne s\'expliquer en premier ?' },
  { id: 'ml_hard_163', level: 'hard', text: 'Qui pourrait être adorable en public et très différent en privé avec les mêmes personnes ?' },
  { id: 'ml_hard_164', level: 'hard', text: 'Qui pourrait avoir tendance à se venger subtilement quand quelqu\'un le blesse ?' },
  { id: 'ml_hard_165', level: 'hard', text: 'Qui pourrait avoir une liste mentale des "dettes" de chaque ami qu\'il consulte au moment opportun ?' },

  // Trahisons & ruptures
  { id: 'ml_hard_166', level: 'hard', text: 'Qui pourrait avoir largué quelqu\'un uniquement par message ou vocal ?' },
  { id: 'ml_hard_167', level: 'hard', text: 'Qui pourrait avoir quitté quelqu\'un qui était vraiment amoureux juste parce qu\'il s\'ennuyait ?' },
  { id: 'ml_hard_168', level: 'hard', text: 'Qui pourrait avoir profité de la gentillesse de quelqu\'un qui l\'aimait sans jamais le lui rendre ?' },
  { id: 'ml_hard_169', level: 'hard', text: 'Qui pourrait avoir brisé une amitié pour une relation amoureuse qui n\'a pas duré 3 mois ?' },
  { id: 'ml_hard_170', level: 'hard', text: 'Qui pourrait avoir révélé le secret d\'un ex après la rupture par vengeance ?' },
  { id: 'ml_hard_171', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un le soir même de sa rupture pour "aller mieux" ?' },
  { id: 'ml_hard_172', level: 'hard', text: 'Qui pourrait avoir menti à un ami pour couvrir une infidélité — la sienne ou celle d\'un autre ?' },
  { id: 'ml_hard_173', level: 'hard', text: 'Qui pourrait avoir utilisé une rupture difficile comme excuse pendant plus d\'un an ?' },
  { id: 'ml_hard_174', level: 'hard', text: 'Qui pourrait avoir brisé la confiance de quelqu\'un dans ce groupe à un moment donné ?' },
  { id: 'ml_hard_175', level: 'hard', text: 'Qui pourrait avoir dit "c\'est lui/elle qui a rompu" alors que la vérité complète était bien plus nuancée ?' },
  { id: 'ml_hard_176', level: 'hard', text: 'Qui pourrait être encore ami avec quelqu\'un uniquement pour l\'accès qu\'il/elle lui procure ?' },
  { id: 'ml_hard_177', level: 'hard', text: 'Qui pourrait avoir joué avec les sentiments de quelqu\'un en sachant très bien ce qu\'il faisait ?' },
  { id: 'ml_hard_178', level: 'hard', text: 'Qui pourrait avoir refusé une réconciliation sincère par orgueil pur ?' },
  { id: 'ml_hard_179', level: 'hard', text: 'Qui pourrait avoir coupé contact avec quelqu\'un uniquement parce qu\'il avait rencontré quelqu\'un d\'autre ?' },
  { id: 'ml_hard_180', level: 'hard', text: 'Qui pourrait avoir gardé une relation beaucoup plus longtemps que nécessaire pour ne pas être seul(e) ?' },

  // Jalousie & compétition
  { id: 'ml_hard_181', level: 'hard', text: 'Qui pourrait avoir saboté un projet d\'un(e) ami(e) parce qu\'il avait peur d\'être dépassé ?' },
  { id: 'ml_hard_182', level: 'hard', text: 'Qui pourrait être plus content quand les autres ne réussissent pas que quand il réussit lui-même ?' },
  { id: 'ml_hard_183', level: 'hard', text: 'Qui pourrait avoir minimisé les succès des autres devant eux, par jalousie à peine voilée ?' },
  { id: 'ml_hard_184', level: 'hard', text: 'Qui pourrait ressentir un soulagement secret quand la relation d\'un ami se termine mal ?' },
  { id: 'ml_hard_185', level: 'hard', text: 'Qui pourrait dénigrer les choix de vie des autres pour se sentir mieux dans ses propres choix ?' },
  { id: 'ml_hard_186', level: 'hard', text: 'Qui pourrait avoir copié le style, l\'idée ou le projet d\'un ami et fait comme si ça venait de lui ?' },
  { id: 'ml_hard_187', level: 'hard', text: 'Qui pourrait suivre les réussites de son ex pour vérifier s\'il/elle fait mieux ou moins bien ?' },
  { id: 'ml_hard_188', level: 'hard', text: 'Qui pourrait avoir déjà pensé "ça lui apprendra" face au malheur de quelqu\'un qu\'il/elle envie ?' },
  { id: 'ml_hard_189', level: 'hard', text: 'Qui pourrait mentir sur ses accomplissements pour paraître au même niveau que son entourage ?' },
  { id: 'ml_hard_190', level: 'hard', text: 'Qui pourrait avoir besoin d\'avoir raison plus que d\'avoir une bonne conversation ?' },
  { id: 'ml_hard_191', level: 'hard', text: 'Qui pourrait ne jamais reconnaître qu\'un autre a eu une meilleure idée que lui ?' },
  { id: 'ml_hard_192', level: 'hard', text: 'Qui pourrait avoir changé d\'ambition uniquement parce qu\'un ami avait le même projet avant lui ?' },
  { id: 'ml_hard_193', level: 'hard', text: 'Qui pourrait avoir tout fait pour gagner un jeu de société alors qu\'il était censé être fun pour tout le monde ?' },
  { id: 'ml_hard_194', level: 'hard', text: 'Qui pourrait comparer son salaire à celui des autres et se placer "juste en dessous" pour susciter la sympathie ?' },
  { id: 'ml_hard_195', level: 'hard', text: 'Qui pourrait avoir travaillé à sa propre promotion en faisant croire qu\'il aidait quelqu\'un d\'autre ?' },

  // Comportements en couple
  { id: 'ml_hard_196', level: 'hard', text: 'Qui pourrait continuer à parler à un ex "en ami" en sachant très bien ce que ça sous-entend ?' },
  { id: 'ml_hard_197', level: 'hard', text: 'Qui pourrait avoir fait une chose que son/sa partenaire lui a expressément demandé de ne pas faire ?' },
  { id: 'ml_hard_198', level: 'hard', text: 'Qui pourrait avoir maintenu une relation plus longtemps que nécessaire pour ne pas être seul(e) ?' },
  { id: 'ml_hard_199', level: 'hard', text: 'Qui pourrait avoir trompé émotionnellement quelqu\'un (sans passer à l\'acte) pendant une relation ?' },
  { id: 'ml_hard_200', level: 'hard', text: 'Qui pourrait avoir des conversations avec quelqu\'un qu\'il/elle n\'oserait pas montrer à son/sa partenaire ?' },
  { id: 'ml_hard_201', level: 'hard', text: 'Qui pourrait avoir prétendu être d\'accord avec son/sa partenaire en public en pensant l\'inverse en privé ?' },
  { id: 'ml_hard_202', level: 'hard', text: 'Qui pourrait avoir utilisé une dispute pour justifier une nuit ailleurs ?' },
  { id: 'ml_hard_203', level: 'hard', text: 'Qui pourrait avoir fait croire à quelqu\'un qu\'il/elle était exclusif(ve) tout en voyant quelqu\'un d\'autre ?' },
  { id: 'ml_hard_204', level: 'hard', text: 'Qui pourrait avoir gardé une relation secrète de son cercle d\'amis pendant plus de 3 mois ?' },
  { id: 'ml_hard_205', level: 'hard', text: 'Qui pourrait avoir brisé une promesse fondamentale dans une relation et fait comme si de rien n\'était ?' },
  { id: 'ml_hard_206', level: 'hard', text: 'Qui pourrait avoir planifié une sortie en couple pour en réalité voir quelqu\'un d\'autre ?' },
  { id: 'ml_hard_207', level: 'hard', text: 'Qui pourrait avoir profité d\'un moment de vulnérabilité de son/sa partenaire pour obtenir quelque chose ?' },
  { id: 'ml_hard_208', level: 'hard', text: 'Qui pourrait avoir eu une relation parallèle "juste pour voir" en espérant ne jamais se faire prendre ?' },
  { id: 'ml_hard_209', level: 'hard', text: 'Qui pourrait avoir mis fin à une relation par message puis "rétracté" le lendemain ?' },
  { id: 'ml_hard_210', level: 'hard', text: 'Qui pourrait avoir cherché une excuse pour sortir le soir sans dire où il/elle allait vraiment ?' },

  // Fantasmes & attirances inavouables
  { id: 'ml_hard_211', level: 'hard', text: 'Qui pourrait avoir eu une attirance pour quelqu\'un de ce groupe et fait semblant de ne pas l\'avoir ?' },
  { id: 'ml_hard_212', level: 'hard', text: 'Qui pourrait avoir fantasmé sérieusement sur quelqu\'un d\'inaccessible (prof, patron, ami marié...) ?' },
  { id: 'ml_hard_213', level: 'hard', text: 'Qui pourrait avoir envoyé un message à quelqu\'un "par accident" alors que c\'était clairement intentionnel ?' },
  { id: 'ml_hard_214', level: 'hard', text: 'Qui pourrait avoir un faible secret pour un type de personne qu\'il critique ouvertement en société ?' },
  { id: 'ml_hard_215', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un uniquement par curiosité et ne jamais l\'avoir admis ?' },
  { id: 'ml_hard_216', level: 'hard', text: 'Qui pourrait avoir attiré quelqu\'un vers lui/elle sans avoir l\'intention d\'aller plus loin, juste pour voir ?' },
  { id: 'ml_hard_217', level: 'hard', text: 'Qui pourrait avoir eu le béguin pour le/la partenaire d\'un(e) ami(e) sans jamais rien dire ?' },
  { id: 'ml_hard_218', level: 'hard', text: 'Qui pourrait avoir gardé contact avec quelqu\'un "en amitié" alors que c\'était de l\'attirance des deux côtés ?' },
  { id: 'ml_hard_219', level: 'hard', text: 'Qui pourrait avoir des archives de photos ou de conversations d\'un crush qu\'il n\'a jamais avoué ?' },
  { id: 'ml_hard_220', level: 'hard', text: 'Qui pourrait avoir menti sur son niveau d\'intérêt pour éviter de paraître trop intense ?' },
  { id: 'ml_hard_221', level: 'hard', text: 'Qui pourrait avoir joué la carte "on est juste amis" à quelqu\'un qui savait parfaitement que c\'était faux ?' },
  { id: 'ml_hard_222', level: 'hard', text: 'Qui pourrait avoir initié un rapprochement physique "innocent" en sachant très bien où ça menait ?' },
  { id: 'ml_hard_223', level: 'hard', text: 'Qui pourrait avoir des DMs avec quelqu\'un qu\'il/elle ferait disparaître si son/sa partenaire regardait ?' },
  { id: 'ml_hard_224', level: 'hard', text: 'Qui pourrait avoir flirté avec quelqu\'un juste pour tester son pouvoir de séduction, sans aucune intention ?' },
  { id: 'ml_hard_225', level: 'hard', text: 'Qui pourrait avoir entretenu une ambiguïté avec deux personnes en même temps sans en dire mot à aucune ?' },

  // Travail & carrière sombres
  { id: 'ml_hard_226', level: 'hard', text: 'Qui pourrait avoir présenté l\'idée d\'un collègue comme la sienne lors d\'une réunion importante ?' },
  { id: 'ml_hard_227', level: 'hard', text: 'Qui pourrait avoir menti sur son CV ou son expérience pour obtenir un poste ?' },
  { id: 'ml_hard_228', level: 'hard', text: 'Qui pourrait avoir utilisé du piston tout en faisant semblant d\'être 100 % autodidacte ?' },
  { id: 'ml_hard_229', level: 'hard', text: 'Qui pourrait avoir dénoncé un(e) collègue anonymement pour une raison pas vraiment professionnelle ?' },
  { id: 'ml_hard_230', level: 'hard', text: 'Qui pourrait avoir saboté subtilement le travail d\'un(e) rival(e) pour le/la faire mal paraître ?' },
  { id: 'ml_hard_231', level: 'hard', text: 'Qui pourrait avoir rendu un travail bâclé après une journée entière sur les réseaux en disant qu\'il s\'était défoncé ?' },
  { id: 'ml_hard_232', level: 'hard', text: 'Qui pourrait avoir pris le crédit d\'un projet collectif lors d\'une présentation au grand patron ?' },
  { id: 'ml_hard_233', level: 'hard', text: 'Qui pourrait avoir gonflé des données ou un reporting qu\'il n\'avait pas réellement fait ?' },
  { id: 'ml_hard_234', level: 'hard', text: 'Qui pourrait avoir utilisé les ressources de son employeur pour des projets perso ?' },
  { id: 'ml_hard_235', level: 'hard', text: 'Qui pourrait avoir négocié un salaire en inventant une offre concurrente qu\'il n\'avait pas vraiment ?' },
  { id: 'ml_hard_236', level: 'hard', text: 'Qui pourrait avoir quitté un emploi en laissant délibérément un dossier incomplet pour compliquer la tâche de son successeur ?' },
  { id: 'ml_hard_237', level: 'hard', text: 'Qui pourrait avoir gonflé sa note de frais professionnels de façon significative ?' },
  { id: 'ml_hard_238', level: 'hard', text: 'Qui pourrait avoir passé des heures à "paraître occupé" en réunion sans jamais contribuer à rien ?' },
  { id: 'ml_hard_239', level: 'hard', text: 'Qui pourrait avoir géré deux jobs ou deux clients en concurrence directe sans le dire à aucun des deux ?' },
  { id: 'ml_hard_240', level: 'hard', text: 'Qui pourrait avoir obtenu une promotion grâce à de la politique d\'entreprise plutôt qu\'à la compétence ?' },

  // Famille & dossiers parentaux
  { id: 'ml_hard_241', level: 'hard', text: 'Qui pourrait avoir eu une relation sérieuse que ses parents ignorent encore totalement ?' },
  { id: 'ml_hard_242', level: 'hard', text: 'Qui pourrait avoir menti à ses parents sur un aspect fondamental de sa vie depuis des années ?' },
  { id: 'ml_hard_243', level: 'hard', text: 'Qui pourrait avoir utilisé ses parents comme alibi pour une nuit dont ils ne sauront jamais rien ?' },
  { id: 'ml_hard_244', level: 'hard', text: 'Qui pourrait avoir fait une chose dont il sait que ça briserait le cœur de ses parents s\'ils le savaient ?' },
  { id: 'ml_hard_245', level: 'hard', text: 'Qui pourrait avoir pris de l\'argent à ses parents sans jamais le rendre, en sachant qu\'ils ne demanderaient pas ?' },
  { id: 'ml_hard_246', level: 'hard', text: 'Qui pourrait avoir manipulé un parent pour obtenir quelque chose tout en sachant que c\'était une manipulation ?' },
  { id: 'ml_hard_247', level: 'hard', text: 'Qui pourrait avoir dit du mal de quelqu\'un de sa famille à des amis et leur avoir présenté ensuite comme si tout allait bien ?' },
  { id: 'ml_hard_248', level: 'hard', text: 'Qui pourrait cacher une partie de sa vie amoureuse à sa famille par peur de leur jugement plus que par pudeur ?' },
  { id: 'ml_hard_249', level: 'hard', text: 'Qui pourrait avoir hérité d\'un avantage familial sans le mentionner pour que ses amis ne voient pas les choses différemment ?' },
  { id: 'ml_hard_250', level: 'hard', text: 'Qui pourrait avoir été la vraie cause d\'une grande dispute familiale et laissé quelqu\'un d\'autre en prendre la responsabilité ?' },

  // Voyages de groupe catastrophiques
  { id: 'ml_hard_251', level: 'hard', text: 'Qui pourrait avoir failli faire louper le vol ou le bus à tout le groupe par sa faute ?' },
  { id: 'ml_hard_252', level: 'hard', text: 'Qui pourrait avoir organisé un "voyage de groupe" qui correspondait exactement à ce qu\'il voulait faire seul ?' },
  { id: 'ml_hard_253', level: 'hard', text: 'Qui pourrait avoir disparu pendant un voyage de groupe et être revenu sans explication ?' },
  { id: 'ml_hard_254', level: 'hard', text: 'Qui pourrait avoir eu une aventure lors d\'un voyage de groupe avec quelqu\'un censé être "juste un ami" ?' },
  { id: 'ml_hard_255', level: 'hard', text: 'Qui pourrait avoir dépensé 3× le budget prévu et fait passer la note à tout le groupe ?' },
  { id: 'ml_hard_256', level: 'hard', text: 'Qui pourrait avoir ramené quelqu\'un d\'étranger dans une chambre partagée sans prévenir ses co-vacanciers ?' },
  { id: 'ml_hard_257', level: 'hard', text: 'Qui pourrait avoir créé une tension dans un groupe en vacances parce qu\'il/elle n\'arrivait pas à lâcher prise ?' },
  { id: 'ml_hard_258', level: 'hard', text: 'Qui pourrait avoir failli créer un incident diplomatique lors d\'un voyage à l\'étranger ?' },
  { id: 'ml_hard_259', level: 'hard', text: 'Qui pourrait avoir perdu passeport, valise ou argent lors d\'un voyage collectif et tout ralenti ?' },
  { id: 'ml_hard_260', level: 'hard', text: 'Qui pourrait avoir pleuré dans un aéroport à cause d\'un drame personnel pendant un voyage de groupe ?' },

  // Grandes descentes en soirée — niveau 2
  { id: 'ml_hard_261', level: 'hard', text: 'Qui pourrait avoir pris le téléphone de quelqu\'un en soirée pour écrire à son/sa partenaire ?' },
  { id: 'ml_hard_262', level: 'hard', text: 'Qui pourrait avoir déclenché une bagarre (même verbale) entre des gens qui se connaissaient à peine ?' },
  { id: 'ml_hard_263', level: 'hard', text: 'Qui pourrait avoir utilisé une soirée pour régler un compte personnel de façon très peu subtile ?' },
  { id: 'ml_hard_264', level: 'hard', text: 'Qui pourrait avoir abandonné un(e) ami(e) bourré(e) avec des inconnus pour rentrer avec quelqu\'un d\'intéressant ?' },
  { id: 'ml_hard_265', level: 'hard', text: 'Qui pourrait avoir dit quelque chose d\'irréparable en soirée et fait semblant de n\'en avoir aucun souvenir le lendemain ?' },
  { id: 'ml_hard_266', level: 'hard', text: 'Qui pourrait avoir planté quelqu\'un au dernier moment parce qu\'une meilleure option s\'était présentée ?' },
  { id: 'ml_hard_267', level: 'hard', text: 'Qui pourrait avoir fait une confession en soirée que les gens autour de lui n\'étaient pas censés entendre ?' },
  { id: 'ml_hard_268', level: 'hard', text: 'Qui pourrait avoir joué les cupidons entre deux personnes juste pour avoir un dossier sur les deux ensuite ?' },
  { id: 'ml_hard_269', level: 'hard', text: 'Qui pourrait avoir pris des photos compromettantes de quelqu\'un en soirée et les avoir gardées "au cas où" ?' },
  { id: 'ml_hard_270', level: 'hard', text: 'Qui pourrait avoir renversé quelque chose de coûteux chez son hôte et fait comme si c\'était quelqu\'un d\'autre ?' },
  { id: 'ml_hard_271', level: 'hard', text: 'Qui pourrait avoir inventé une urgence pour quitter une soirée parce qu\'une personne présente lui déplaisait ?' },
  { id: 'ml_hard_272', level: 'hard', text: 'Qui pourrait avoir participé à une rumeur de soirée pour qu\'on parle de lui/elle indirectement ?' },
  { id: 'ml_hard_273', level: 'hard', text: 'Qui pourrait avoir emprunté les habits ou affaires de quelqu\'un lors d\'un séjour sans demander ?' },
  { id: 'ml_hard_274', level: 'hard', text: 'Qui pourrait avoir utilisé un soirée pour tenter de récupérer un/une ex devant ses nouveaux amis ?' },
  { id: 'ml_hard_275', level: 'hard', text: 'Qui pourrait avoir fait une proposition gênante à quelqu\'un en sachant très bien que le contexte ne s\'y prêtait pas ?' },

  // Argent & escroqueries — niveau 2
  { id: 'ml_hard_276', level: 'hard', text: 'Qui pourrait avoir organisé une cagnotte pour un cadeau collectif et gardé le reste pour lui ?' },
  { id: 'ml_hard_277', level: 'hard', text: 'Qui pourrait avoir emprunté un article et dit l\'avoir "perdu" plutôt que de le rendre cassé ?' },
  { id: 'ml_hard_278', level: 'hard', text: 'Qui pourrait avoir accepté de partager un abonnement et ne jamais payer sa part ?' },
  { id: 'ml_hard_279', level: 'hard', text: 'Qui pourrait avoir "oublié" sa CB pour que quelqu\'un d\'autre paye, au moins 3 fois avec la même personne ?' },
  { id: 'ml_hard_280', level: 'hard', text: 'Qui pourrait avoir fait un faux avis négatif sur un concurrent ou un faux positif sur lui-même ?' },
  { id: 'ml_hard_281', level: 'hard', text: 'Qui pourrait avoir vendu quelque chose en cachant un défaut majeur qu\'il connaissait parfaitement ?' },
  { id: 'ml_hard_282', level: 'hard', text: 'Qui pourrait avoir utilisé l\'argent d\'une cagnotte de groupe pour autre chose que ce qui était prévu ?' },
  { id: 'ml_hard_283', level: 'hard', text: 'Qui pourrait avoir profité d\'une erreur de remboursement double sans rien signaler ?' },
  { id: 'ml_hard_284', level: 'hard', text: 'Qui pourrait avoir utilisé Vinted ou Leboncoin pour vendre quelque chose qu\'il avait emprunté à quelqu\'un d\'autre ?' },
  { id: 'ml_hard_285', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de payer sa part en lui faisant croire que ce serait "géré plus tard" depuis 6 mois ?' },

  // Manipulation & gaslighting
  { id: 'ml_hard_286', level: 'hard', text: 'Qui pourrait faire pleurer quelqu\'un et finir par se faire consoler par cette même personne ?' },
  { id: 'ml_hard_287', level: 'hard', text: 'Qui pourrait changer de version des faits selon son interlocuteur jusqu\'à ne plus savoir lui-même ce qui s\'est passé ?' },
  { id: 'ml_hard_288', level: 'hard', text: 'Qui pourrait se servir des informations confiées pour prendre l\'avantage dans une discussion future ?' },
  { id: 'ml_hard_289', level: 'hard', text: 'Qui pourrait prétendre "ne pas comprendre" une chose qu\'il comprend très bien pour éviter de s\'y conformer ?' },
  { id: 'ml_hard_290', level: 'hard', text: 'Qui pourrait faire sentir à quelqu\'un qu\'il/elle est "chanceux(se) de l\'avoir" dans sa vie ?' },
  { id: 'ml_hard_291', level: 'hard', text: 'Qui pourrait retourner une discussion en faisant passer l\'autre pour l\'agresseur alors qu\'il était à l\'origine du problème ?' },
  { id: 'ml_hard_292', level: 'hard', text: 'Qui pourrait pratiquer le silence radio stratégique jusqu\'à obtenir la réaction qu\'il cherchait ?' },
  { id: 'ml_hard_293', level: 'hard', text: 'Qui pourrait avoir fait culpabiliser quelqu\'un de quelque chose qui ne lui incombait pas du tout ?' },
  { id: 'ml_hard_294', level: 'hard', text: 'Qui pourrait avoir inventé ou exagéré une souffrance pour obtenir quelque chose d\'un proche ?' },
  { id: 'ml_hard_295', level: 'hard', text: 'Qui pourrait avoir dit "tu sais très bien ce que tu as fait" sans jamais expliquer quoi ?' },
  { id: 'ml_hard_296', level: 'hard', text: 'Qui pourrait avoir rendu quelqu\'un dépendant de son approbation puis retiré cette approbation dès l\'objectif atteint ?' },
  { id: 'ml_hard_297', level: 'hard', text: 'Qui pourrait avoir présenté deux personnes en sachant qu\'elles se disputeraient, juste pour voir ?' },
  { id: 'ml_hard_298', level: 'hard', text: 'Qui pourrait avoir fait savoir à quelqu\'un qu\'il/elle était remplaçable pour le/la garder sous pression ?' },
  { id: 'ml_hard_299', level: 'hard', text: 'Qui pourrait avoir utilisé les insécurités de quelqu\'un contre lui/elle lors d\'une dispute ?' },
  { id: 'ml_hard_300', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de prendre une décision qui lui profitait à lui plutôt qu\'à cette personne ?' },

  // Secrets de groupe & trahisons
  { id: 'ml_hard_301', level: 'hard', text: 'Qui pourrait connaître un secret de couple dans ce groupe et s\'en servir selon les circonstances ?' },
  { id: 'ml_hard_302', level: 'hard', text: 'Qui pourrait avoir dit à un groupe quelque chose de privé qu\'on lui avait confié en aparté ?' },
  { id: 'ml_hard_303', level: 'hard', text: 'Qui pourrait avoir monté deux amis l\'un contre l\'autre et joué au médiateur ensuite ?' },
  { id: 'ml_hard_304', level: 'hard', text: 'Qui pourrait avoir fait partie d\'un sous-groupe de discussion qui parlait de quelqu\'un présent ici ?' },
  { id: 'ml_hard_305', level: 'hard', text: 'Qui pourrait avoir gardé une information cruciale pour lui parce que ça ne l\'arrangeait pas de la partager ?' },
  { id: 'ml_hard_306', level: 'hard', text: 'Qui pourrait avoir utilisé la confidence d\'un ami comme moyen de pression lors d\'un désaccord ?' },
  { id: 'ml_hard_307', level: 'hard', text: 'Qui pourrait avoir soutenu quelqu\'un en face de lui et l\'avoir critiqué dans son dos le lendemain ?' },
  { id: 'ml_hard_308', level: 'hard', text: 'Qui pourrait avoir participé à une décision de groupe visant à exclure quelqu\'un sans que cette personne le sache ?' },
  { id: 'ml_hard_309', level: 'hard', text: 'Qui pourrait avoir changé de camp dans un conflit entre amis selon ce qui l\'arrangeait le plus ?' },
  { id: 'ml_hard_310', level: 'hard', text: 'Qui pourrait avoir alimenté une tension entre deux personnes sans jamais sembler impliqué ?' },
  { id: 'ml_hard_311', level: 'hard', text: 'Qui pourrait avoir communiqué les coordonnées d\'un ami à quelqu\'un sans son consentement ?' },
  { id: 'ml_hard_312', level: 'hard', text: 'Qui pourrait avoir accepté de garder un secret, l\'avoir raconté, et prétendu ne plus savoir comment c\'était sorti ?' },
  { id: 'ml_hard_313', level: 'hard', text: 'Qui pourrait avoir tiré profit d\'une dispute entre amis pour en bénéficier directement ?' },
  { id: 'ml_hard_314', level: 'hard', text: 'Qui pourrait avoir un rôle fondamental dans une histoire de groupe dont personne ne connaît sa vraie implication ?' },
  { id: 'ml_hard_315', level: 'hard', text: 'Qui pourrait avoir vendu quelqu\'un dans son groupe pour se protéger lui-même ?' },

  // Vie numérique — niveau 2
  { id: 'ml_hard_316', level: 'hard', text: 'Qui pourrait avoir récupéré un mot de passe ou un accès à un compte qui ne lui appartenait pas ?' },
  { id: 'ml_hard_317', level: 'hard', text: 'Qui pourrait avoir utilisé la localisation d\'un proche à son insu pour savoir où il/elle était ?' },
  { id: 'ml_hard_318', level: 'hard', text: 'Qui pourrait avoir screenshotté des stories ou publications avant qu\'elles soient supprimées pour les utiliser plus tard ?' },
  { id: 'ml_hard_319', level: 'hard', text: 'Qui pourrait avoir créé un faux compte pour s\'infiltrer dans un groupe privé dont il/elle était exclu(e) ?' },
  { id: 'ml_hard_320', level: 'hard', text: 'Qui pourrait avoir lu les mails ou messages d\'un proche sur un ordi partagé sans jamais le dire ?' },
  { id: 'ml_hard_321', level: 'hard', text: 'Qui pourrait avoir répondu à un message depuis le téléphone de quelqu\'un en se faisant passer pour lui/elle ?' },
  { id: 'ml_hard_322', level: 'hard', text: 'Qui pourrait avoir archivé des conversations pour avoir des "preuves" en cas de désaccord futur ?' },
  { id: 'ml_hard_323', level: 'hard', text: 'Qui pourrait avoir utilisé le téléphone de quelqu\'un pour envoyer un message qu\'il/elle ne voulait pas envoyer lui-même ?' },
  { id: 'ml_hard_324', level: 'hard', text: 'Qui pourrait avoir partagé une info privée en ligne en pensant que "personne ne verrait" ?' },
  { id: 'ml_hard_325', level: 'hard', text: 'Qui pourrait avoir accédé au compte d\'un(e) ex après la rupture pour voir avec qui il/elle parlait ?' },

  // Confessions relationnelles
  { id: 'ml_hard_326', level: 'hard', text: 'Qui pourrait avoir rompu avec quelqu\'un juste avant une occasion importante pour éviter d\'y aller ensemble ?' },
  { id: 'ml_hard_327', level: 'hard', text: 'Qui pourrait avoir dit "je t\'aime" pour la première fois principalement pour garder quelqu\'un ?' },
  { id: 'ml_hard_328', level: 'hard', text: 'Qui pourrait avoir repris contact avec un ex la nuit de Noël ou du Nouvel An "juste pour prendre des nouvelles" ?' },
  { id: 'ml_hard_329', level: 'hard', text: 'Qui pourrait avoir envoyé le même message à plusieurs personnes en même temps pour maximiser ses chances ?' },
  { id: 'ml_hard_330', level: 'hard', text: 'Qui pourrait avoir utilisé une relation amoureuse pour accéder à un cercle social ou une opportunité ?' },
  { id: 'ml_hard_331', level: 'hard', text: 'Qui pourrait avoir promis de rencontrer les amis ou parents de quelqu\'un sans jamais avoir l\'intention de le faire ?' },
  { id: 'ml_hard_332', level: 'hard', text: 'Qui pourrait avoir mis fin à une relation uniquement parce qu\'une meilleure opportunité s\'était présentée la semaine d\'avant ?' },
  { id: 'ml_hard_333', level: 'hard', text: 'Qui pourrait avoir laissé quelqu\'un croire à une relation plus sérieuse qu\'elle ne l\'était pour ne pas le/la perdre ?' },
  { id: 'ml_hard_334', level: 'hard', text: 'Qui pourrait avoir partagé des détails intimes d\'une relation passée sous prétexte de "témoignage" ?' },
  { id: 'ml_hard_335', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un de ce groupe lors d\'une autre occasion que cette soirée ?' },
  { id: 'ml_hard_336', level: 'hard', text: 'Qui pourrait avoir entretenu une relation bien plus longtemps que nécessaire par habitude pure ?' },
  { id: 'ml_hard_337', level: 'hard', text: 'Qui pourrait avoir eu des sentiments intenses pour quelqu\'un tout en étant en couple et ne l\'avoir jamais dit ?' },
  { id: 'ml_hard_338', level: 'hard', text: 'Qui pourrait avoir eu une relation complète avec quelqu\'un que ses amis n\'ont jamais rencontré ?' },
  { id: 'ml_hard_339', level: 'hard', text: 'Qui pourrait avoir fait croire à quelqu\'un d\'exclusif tout en voyant activement quelqu\'un d\'autre dans la même ville ?' },
  { id: 'ml_hard_340', level: 'hard', text: 'Qui pourrait avoir trompé émotionnellement quelqu\'un pendant des semaines tout en jurant que "tout allait bien" ?' },

  // Red flags comportementaux & finale
  { id: 'ml_hard_341', level: 'hard', text: 'Qui pourrait ne jamais prendre ses torts dans une dispute et toujours trouver un angle pour s\'en sortir propre ?' },
  { id: 'ml_hard_342', level: 'hard', text: 'Qui pourrait avoir des comportements très différents selon s\'il est observé ou non ?' },
  { id: 'ml_hard_343', level: 'hard', text: 'Qui pourrait avoir utilisé sa popularité ou son statut pour obtenir quelque chose qui ne lui était pas dû ?' },
  { id: 'ml_hard_344', level: 'hard', text: 'Qui pourrait avoir méprisé quelqu\'un en public avec humour en faisant croire que c\'était une blague ?' },
  { id: 'ml_hard_345', level: 'hard', text: 'Qui pourrait traiter les serveurs ou caissiers très différemment des gens qui lui "sont utiles" ?' },
  { id: 'ml_hard_346', level: 'hard', text: 'Qui pourrait avoir fait une promesse solennelle et l\'avoir brisée sans vraiment s\'en excuser ?' },
  { id: 'ml_hard_347', level: 'hard', text: 'Qui pourrait avoir utilisé une période de faiblesse de quelqu\'un pour l\'influencer dans une décision qui l\'arrangeait ?' },
  { id: 'ml_hard_348', level: 'hard', text: 'Qui pourrait avoir joué un personnage tellement longtemps qu\'il a du mal à dire qui il est vraiment ?' },
  { id: 'ml_hard_349', level: 'hard', text: 'Qui pourrait avoir l\'impression de mériter plus que ce qu\'il a, dans presque chaque domaine de sa vie ?' },
  { id: 'ml_hard_350', level: 'hard', text: 'Qui pourrait être la personne dont tout le monde parle quand il n\'est pas là, et le savoir parfaitement ?' },
]
