export interface MLQuestion {
  id: string
  level: 'soft' | 'hard'
  text: string
}

export const ML_QUESTIONS: MLQuestion[] = [
  // ─── SOFT (100) ────────────────────────────────────────────────────────────

  // Flemme légendaire
  { id: 'ml_soft_1',  level: 'soft', text: 'Qui pourrait commander un Uber pour faire moins de 300 mètres ?' },
  { id: 'ml_soft_2',  level: 'soft', text: 'Qui pourrait envoyer un message vocal de 4 minutes plutôt que de rappeler ?' },
  { id: 'ml_soft_3',  level: 'soft', text: 'Qui pourrait payer plus cher juste pour ne pas avoir à chercher une place de parking ?' },
  { id: 'ml_soft_4',  level: 'soft', text: 'Qui pourrait laisser sa valise non rangée pendant une semaine après être rentré de vacances ?' },
  { id: 'ml_soft_5',  level: 'soft', text: 'Qui pourrait lire un message sans répondre et l\'oublier pendant 3 jours ?' },
  { id: 'ml_soft_6',  level: 'soft', text: 'Qui pourrait regarder un film en 4 fois parce qu\'il s\'endort à chaque fois ?' },
  { id: 'ml_soft_7',  level: 'soft', text: 'Qui pourrait mettre sa tenue du lendemain sur sa chaise de bureau depuis l\'enfance ?' },
  { id: 'ml_soft_8',  level: 'soft', text: 'Qui pourrait faire 5 allers-retours dans sa cuisine parce qu\'il oublie ce qu\'il est venu chercher ?' },
  { id: 'ml_soft_9',  level: 'soft', text: 'Qui pourrait laisser le linge dans le tambour de la machine pendant 2 jours ?' },
  { id: 'ml_soft_10', level: 'soft', text: 'Qui pourrait repousser sa sonnerie de réveil 7 fois avant de se lever ?' },

  // Étourderies & bourdes
  { id: 'ml_soft_11', level: 'soft', text: 'Qui pourrait essayer de rentrer chez lui avec les clés de sa voiture dans sa porte d\'entrée ?' },
  { id: 'ml_soft_12', level: 'soft', text: 'Qui pourrait mettre ses lunettes pour chercher ses lunettes ?' },
  { id: 'ml_soft_13', level: 'soft', text: 'Qui pourrait passer 10 minutes à chercher son téléphone alors qu\'il est en train de chercher dessus ?' },
  { id: 'ml_soft_14', level: 'soft', text: 'Qui pourrait oublier son code de carte bleue au moment de payer l\'addition ?' },
  { id: 'ml_soft_15', level: 'soft', text: 'Qui pourrait envoyer un message à la mauvaise personne et paniquer ?' },
  { id: 'ml_soft_16', level: 'soft', text: 'Qui pourrait sortir en ayant mis son pull à l\'envers sans s\'en rendre compte ?' },
  { id: 'ml_soft_17', level: 'soft', text: 'Qui pourrait arriver à une réunion un jour trop tôt ?' },
  { id: 'ml_soft_18', level: 'soft', text: 'Qui pourrait appeler quelqu\'un "maman" par accident ?' },
  { id: 'ml_soft_19', level: 'soft', text: 'Qui pourrait verser son café dans son verre d\'eau parce qu\'il est pas réveillé ?' },
  { id: 'ml_soft_20', level: 'soft', text: 'Qui pourrait confondre sel et sucre et servir ça à des invités sans s\'en apercevoir ?' },

  // Réseaux sociaux & téléphone
  { id: 'ml_soft_21', level: 'soft', text: 'Qui pourrait liker accidentellement une vieille photo en faisant du stalking ?' },
  { id: 'ml_soft_22', level: 'soft', text: 'Qui pourrait regarder les stories Insta de quelqu\'un tous les jours sans jamais lui parler ?' },
  { id: 'ml_soft_23', level: 'soft', text: 'Qui pourrait passer 2h sur TikTok en pensant en avoir passé 15 minutes ?' },
  { id: 'ml_soft_24', level: 'soft', text: 'Qui pourrait suivre un inconnu par erreur et le désabonner 3 secondes après ?' },
  { id: 'ml_soft_25', level: 'soft', text: 'Qui pourrait poster une photo puis la supprimer parce qu\'elle n\'a pas assez de likes ?' },
  { id: 'ml_soft_26', level: 'soft', text: 'Qui pourrait répondre "ça va et toi ?" sans attendre la réponse ?' },
  { id: 'ml_soft_27', level: 'soft', text: 'Qui pourrait avoir plus de 1000 notifications non lues ?' },
  { id: 'ml_soft_28', level: 'soft', text: 'Qui pourrait mettre en sourdine un groupe WhatsApp et ne jamais le sortir de sourdine ?' },
  { id: 'ml_soft_29', level: 'soft', text: 'Qui pourrait écrire un long message, tout effacer et envoyer juste "ok" ?' },
  { id: 'ml_soft_30', level: 'soft', text: 'Qui pourrait rechercher ses propres photos pour voir comment il apparaît dans les recherches ?' },

  // Comportements en société
  { id: 'ml_soft_31', level: 'soft', text: 'Qui pourrait dire "c\'est pas loin" et marcher 40 minutes ?' },
  { id: 'ml_soft_32', level: 'soft', text: 'Qui pourrait oublier le prénom de quelqu\'un au milieu d\'une présentation ?' },
  { id: 'ml_soft_33', level: 'soft', text: 'Qui pourrait inventer un rendez-vous pour partir d\'une soirée ennuyeuse ?' },
  { id: 'ml_soft_34', level: 'soft', text: 'Qui pourrait rire très fort à une blague qu\'il n\'a pas comprise ?' },
  { id: 'ml_soft_35', level: 'soft', text: 'Qui pourrait répondre "avec plaisir" au lieu de "merci" ?' },
  { id: 'ml_soft_36', level: 'soft', text: 'Qui pourrait se faire rembarrer en essayant d\'être drôle ?' },
  { id: 'ml_soft_37', level: 'soft', text: 'Qui pourrait passer au rouge parce qu\'il n\'a pas entendu ce qu\'on lui a dit ?' },
  { id: 'ml_soft_38', level: 'soft', text: 'Qui pourrait dire "moi pareil" alors que c\'est totalement faux ?' },
  { id: 'ml_soft_39', level: 'soft', text: 'Qui pourrait donner une poignée de main à quelqu\'un qui voulait faire la bise ?' },
  { id: 'ml_soft_40', level: 'soft', text: 'Qui pourrait claquer la bise dans le vide parce qu\'il ne sait pas combien en faire ?' },

  // Alimentation & cuisine
  { id: 'ml_soft_41', level: 'soft', text: 'Qui pourrait manger les restes du frigo froid parce qu\'il est trop flemmard pour chauffer ?' },
  { id: 'ml_soft_42', level: 'soft', text: 'Qui pourrait appeler la livraison 3 soirs de suite au même endroit ?' },
  { id: 'ml_soft_43', level: 'soft', text: 'Qui pourrait brûler de l\'eau en faisant une recette "simple" ?' },
  { id: 'ml_soft_44', level: 'soft', text: 'Qui pourrait manger directement dans la casserole pour éviter de faire la vaisselle ?' },
  { id: 'ml_soft_45', level: 'soft', text: 'Qui pourrait commander une entrée + plat + dessert et regretter dès l\'entrée ?' },
  { id: 'ml_soft_46', level: 'soft', text: 'Qui pourrait finir l\'assiette de tout le monde "pour ne pas gâcher" ?' },
  { id: 'ml_soft_47', level: 'soft', text: 'Qui pourrait refuser un plat dans un restaurant et commander le même chez lui via Uber Eats 1h après ?' },
  { id: 'ml_soft_48', level: 'soft', text: 'Qui pourrait snacker en faisant les courses et ne pas déclarer tout à la caisse ?' },
  { id: 'ml_soft_49', level: 'soft', text: 'Qui pourrait faire croire qu\'il a cuisiné alors qu\'il a juste réchauffé un plat préparé ?' },
  { id: 'ml_soft_50', level: 'soft', text: 'Qui pourrait avoir un placard entier de nourriture et déclarer "ya rien à manger" ?' },

  // Travail & études
  { id: 'ml_soft_51', level: 'soft', text: 'Qui pourrait s\'endormir en réunion et faire semblant de prendre des notes ?' },
  { id: 'ml_soft_52', level: 'soft', text: 'Qui pourrait remettre un devoir/rapport à la dernière seconde littéralement ?' },
  { id: 'ml_soft_53', level: 'soft', text: 'Qui pourrait "travailler depuis chez lui" en faisant 30 minutes de boulot sur 8 heures ?' },
  { id: 'ml_soft_54', level: 'soft', text: 'Qui pourrait oublier qu\'il a un exam/entretien le lendemain ?' },
  { id: 'ml_soft_55', level: 'soft', text: 'Qui pourrait arriver systématiquement en retard à tout, sauf aux apéros ?' },
  { id: 'ml_soft_56', level: 'soft', text: 'Qui pourrait demander à ChatGPT de rédiger un email "professionnel" de 2 lignes ?' },
  { id: 'ml_soft_57', level: 'soft', text: 'Qui pourrait mentir sur ce qu\'il a fait le week-end pour paraître plus intéressant au bureau ?' },
  { id: 'ml_soft_58', level: 'soft', text: 'Qui pourrait gérer toute sa to-do list en "déplaçant" chaque tâche au lendemain ?' },
  { id: 'ml_soft_59', level: 'soft', text: 'Qui pourrait passer 1h à organiser son bureau plutôt que de travailler ?' },
  { id: 'ml_soft_60', level: 'soft', text: 'Qui pourrait avoir son bureau avec 47 onglets ouverts dont il n\'a utilisé aucun ?' },

  // Habitudes bizarres
  { id: 'ml_soft_61', level: 'soft', text: 'Qui pourrait parler à ses plantes ou à ses animaux comme si c\'était des humains ?' },
  { id: 'ml_soft_62', level: 'soft', text: 'Qui pourrait garder des emballages de cadeaux "au cas où" depuis 5 ans ?' },
  { id: 'ml_soft_63', level: 'soft', text: 'Qui pourrait réécouter la même chanson en boucle pendant 3 jours ?' },
  { id: 'ml_soft_64', level: 'soft', text: 'Qui pourrait pleurer devant un film qu\'il a déjà vu 5 fois ?' },
  { id: 'ml_soft_65', level: 'soft', text: 'Qui pourrait chanter faux à tue-tête dans sa voiture et s\'arrêter net quand il voit quelqu\'un ?' },
  { id: 'ml_soft_66', level: 'soft', text: 'Qui pourrait avoir une peluche ou un objet fétiche qu\'il cache à tout le monde ?' },
  { id: 'ml_soft_67', level: 'soft', text: 'Qui pourrait se parler à voix haute quand il est seul chez lui ?' },
  { id: 'ml_soft_68', level: 'soft', text: 'Qui pourrait faire un plan détaillé pour rien faire et s\'en sentir fier ?' },
  { id: 'ml_soft_69', level: 'soft', text: 'Qui pourrait googler les symptômes d\'un rhume et conclure qu\'il a une maladie grave ?' },
  { id: 'ml_soft_70', level: 'soft', text: 'Qui pourrait refuser d\'admettre être perdu et continuer dans la mauvaise direction ?' },

  // En société & sorties
  { id: 'ml_soft_71', level: 'soft', text: 'Qui pourrait s\'endormir le premier en pleine soirée ?' },
  { id: 'ml_soft_72', level: 'soft', text: 'Qui pourrait commander au resto et demander ensuite ce qu\'il a commandé ?' },
  { id: 'ml_soft_73', level: 'soft', text: 'Qui pourrait changer d\'avis sur le restaurant après 20 minutes de trajet ?' },
  { id: 'ml_soft_74', level: 'soft', text: 'Qui pourrait toujours arriver en retard mais avoir une excuse différente à chaque fois ?' },
  { id: 'ml_soft_75', level: 'soft', text: 'Qui pourrait prétendre avoir déjà vu un film qu\'il n\'a jamais vu pour pas avoir l\'air largué ?' },
  { id: 'ml_soft_76', level: 'soft', text: 'Qui pourrait zapper le film que tout le monde avait choisi parce qu\'il le trouvait mauvais ?' },
  { id: 'ml_soft_77', level: 'soft', text: 'Qui pourrait s\'ajouter lui-même dans un groupe WhatsApp qu\'il avait quitté ?' },
  { id: 'ml_soft_78', level: 'soft', text: 'Qui pourrait emprunter un truc sans le rendre et le garder comme le sien ?' },
  { id: 'ml_soft_79', level: 'soft', text: 'Qui pourrait faire semblant de chercher son portefeuille pour que quelqu\'un d\'autre paye ?' },
  { id: 'ml_soft_80', level: 'soft', text: 'Qui pourrait se vanter d\'un régime qu\'il abandonne le soir même ?' },

  // Caractère & ego
  { id: 'ml_soft_81', level: 'soft', text: 'Qui pourrait googler son propre nom pour voir ce qui sort ?' },
  { id: 'ml_soft_82', level: 'soft', text: 'Qui pourrait refaire une photo 20 fois pour avoir "l\'air naturel" ?' },
  { id: 'ml_soft_83', level: 'soft', text: 'Qui pourrait relire sa propre conversation après l\'avoir envoyée pour voir si elle est bien ?' },
  { id: 'ml_soft_84', level: 'soft', text: 'Qui pourrait toujours commencer ses phrases par "moi, j\'aurais fait autrement" ?' },
  { id: 'ml_soft_85', level: 'soft', text: 'Qui pourrait préparer un discours imaginaire pour un conflit qui n\'aura probablement jamais lieu ?' },
  { id: 'ml_soft_86', level: 'soft', text: 'Qui pourrait passer 1 heure sur une caption Instagram de 3 mots ?' },
  { id: 'ml_soft_87', level: 'soft', text: 'Qui pourrait se trouver moins bien en photo que dans la vraie vie ?' },
  { id: 'ml_soft_88', level: 'soft', text: 'Qui pourrait s\'énerver tout seul en rejouant une dispute passée dans sa tête ?' },
  { id: 'ml_soft_89', level: 'soft', text: 'Qui pourrait acheter un truc qu\'il avait déjà mais avait oublié ?' },
  { id: 'ml_soft_90', level: 'soft', text: 'Qui pourrait mentionner son régime/sport dans toutes les conversations ?' },

  // Divers & inclassables
  { id: 'ml_soft_91', level: 'soft', text: 'Qui pourrait lire la fin d\'un livre avant de le finir pour savoir si ça vaut le coup ?' },
  { id: 'ml_soft_92', level: 'soft', text: 'Qui pourrait regarder le prix sur la carte et commander "en fonction" ?' },
  { id: 'ml_soft_93', level: 'soft', text: 'Qui pourrait demander à tout le monde son avis et finalement faire ce qu\'il voulait dès le départ ?' },
  { id: 'ml_soft_94', level: 'soft', text: 'Qui pourrait s\'énerver contre la télé ou un jeu vidéo en criant ?' },
  { id: 'ml_soft_95', level: 'soft', text: 'Qui pourrait payer un abonnement de salle de sport sans jamais y aller ?' },
  { id: 'ml_soft_96', level: 'soft', text: 'Qui pourrait voir un chat dans la rue et lui parler en faisant des bruits bizarres ?' },
  { id: 'ml_soft_97', level: 'soft', text: 'Qui pourrait acheter 3 mêmes t-shirts noirs en pensant que c\'est différent ?' },
  { id: 'ml_soft_98', level: 'soft', text: 'Qui pourrait oublier qu\'il avait mis quelque chose dans le four ?' },
  { id: 'ml_soft_99', level: 'soft', text: 'Qui pourrait faire semblant de ne pas voir quelqu\'un dans la rue pour éviter la conversation ?' },
  { id: 'ml_soft_100', level: 'soft', text: 'Qui pourrait pleurer plus fort si quelqu\'un vient le consoler ?' },

  // ─── HARD (150) ────────────────────────────────────────────────────────────

  // Alcool & soirées
  { id: 'ml_hard_1',  level: 'hard', text: 'Qui pourrait appeler son ex en pleurant après 3 verres de trop ?' },
  { id: 'ml_hard_2',  level: 'hard', text: 'Qui pourrait être le premier à vomir après un concours de shots ?' },
  { id: 'ml_hard_3',  level: 'hard', text: 'Qui pourrait finir la soirée en train de danser sur les tables (ou finir torse nu) ?' },
  { id: 'ml_hard_4',  level: 'hard', text: 'Qui pourrait se réveiller dans une ville inconnue sans savoir comment il est arrivé là ?' },
  { id: 'ml_hard_5',  level: 'hard', text: 'Qui pourrait boire dans le verre de tout le monde sans demander ?' },
  { id: 'ml_hard_6',  level: 'hard', text: 'Qui pourrait commander une bouteille entière "pour le groupe" et la finir presque seul ?' },
  { id: 'ml_hard_7',  level: 'hard', text: 'Qui pourrait perdre ses chaussures en soirée et continuer pieds nus ?' },
  { id: 'ml_hard_8',  level: 'hard', text: 'Qui pourrait s\'endormir dans les toilettes d\'un bar ?' },
  { id: 'ml_hard_9',  level: 'hard', text: 'Qui pourrait passer du "je bois rien ce soir" à "c\'est moi le plus bourré" en 1 heure ?' },
  { id: 'ml_hard_10', level: 'hard', text: 'Qui pourrait se retrouver à chialer à 3h du mat en disant "vous comprenez pas ma vie" ?' },
  { id: 'ml_hard_11', level: 'hard', text: 'Qui pourrait faire le mort dans son canapé pour éviter de rentrer ?' },
  { id: 'ml_hard_12', level: 'hard', text: 'Qui pourrait mélanger tous les alcools et prétendre que "ça va aller" ?' },
  { id: 'ml_hard_13', level: 'hard', text: 'Qui pourrait commander des shots que personne n\'a demandé "pour tout le monde" ?' },
  { id: 'ml_hard_14', level: 'hard', text: 'Qui pourrait faire une chute mémorable sur la piste de danse ?' },
  { id: 'ml_hard_15', level: 'hard', text: 'Qui pourrait se réveiller avec des photos dans son téléphone dont il n\'a aucun souvenir ?' },

  // Comportements en soirée
  { id: 'ml_hard_16', level: 'hard', text: 'Qui pourrait draguer quelqu\'un qui est clairement venu avec un/une partenaire ?' },
  { id: 'ml_hard_17', level: 'hard', text: 'Qui pourrait passer toute la soirée sur son téléphone à texter quelqu\'un qui n\'est pas là ?' },
  { id: 'ml_hard_18', level: 'hard', text: 'Qui pourrait ramener quelqu\'un chez lui que personne n\'avait jamais vu avant ?' },
  { id: 'ml_hard_19', level: 'hard', text: 'Qui pourrait lancer un ragot et faire semblant d\'être étonné quand ça fait le tour ?' },
  { id: 'ml_hard_20', level: 'hard', text: 'Qui pourrait disparaître de la soirée sans prévenir personne ?' },
  { id: 'ml_hard_21', level: 'hard', text: 'Qui pourrait faire un discours non demandé qui met tout le monde mal à l\'aise ?' },
  { id: 'ml_hard_22', level: 'hard', text: 'Qui pourrait monopoliser l\'enceinte bluetooth et ne passer que ses sons ?' },
  { id: 'ml_hard_23', level: 'hard', text: 'Qui pourrait commencer une bagarre verbale pour une raison stupide ?' },
  { id: 'ml_hard_24', level: 'hard', text: 'Qui pourrait être encore debout à 7h du mat alors que tout le monde est parti ?' },
  { id: 'ml_hard_25', level: 'hard', text: 'Qui pourrait casser ou abîmer quelque chose chez son hôte et ne pas le dire ?' },

  // Drague & vie amoureuse
  { id: 'ml_hard_26', level: 'hard', text: 'Qui pourrait mentir sur son âge ou son métier pour draguer en soirée ?' },
  { id: 'ml_hard_27', level: 'hard', text: 'Qui pourrait envoyer un texto de "t\'es rentré bien ?" en espérant clairement autre chose ?' },
  { id: 'ml_hard_28', level: 'hard', text: 'Qui pourrait embrasser quelqu\'un et prétendre le lendemain que c\'était "l\'alcool" ?' },
  { id: 'ml_hard_29', level: 'hard', text: 'Qui pourrait avoir un crush sur quelqu\'un dans ce groupe sans jamais l\'avoir dit ?' },
  { id: 'ml_hard_30', level: 'hard', text: 'Qui pourrait garder des textos d\'ex "au cas où" alors qu\'il est en couple ?' },
  { id: 'ml_hard_31', level: 'hard', text: 'Qui pourrait se lancer dans un make-out session dans un coin de soirée ?' },
  { id: 'ml_hard_32', level: 'hard', text: 'Qui pourrait envoyer un vocal très compromettant à la mauvaise personne ?' },
  { id: 'ml_hard_33', level: 'hard', text: 'Qui pourrait stalker l\'ex de son ex pour "savoir" ?' },
  { id: 'ml_hard_34', level: 'hard', text: 'Qui pourrait revenir avec un ex juste parce qu\'il s\'ennuyait ?' },
  { id: 'ml_hard_35', level: 'hard', text: 'Qui pourrait se retrouver coincé dans un plan à deux non désiré parce qu\'il a trop bien été gentil ?' },
  { id: 'ml_hard_36', level: 'hard', text: 'Qui pourrait bloquer quelqu\'un sur tous les réseaux plutôt que d\'avoir la conversation ?' },
  { id: 'ml_hard_37', level: 'hard', text: 'Qui pourrait ghosting total quelqu\'un après 3 semaines de flirt ?' },
  { id: 'ml_hard_38', level: 'hard', text: 'Qui pourrait envoyer "tu penses à moi ?" en sachant très bien que la réponse sera oui ?' },
  { id: 'ml_hard_39', level: 'hard', text: 'Qui pourrait utiliser "j\'ai besoin d\'aide pour un truc" comme excuse pour voir quelqu\'un qu\'il drague ?' },
  { id: 'ml_hard_40', level: 'hard', text: 'Qui pourrait vérifier si son/sa ex est passé(e) en ligne après l\'avoir bloqué ?' },

  // Dossiers & comportements douteux
  { id: 'ml_hard_41', level: 'hard', text: 'Qui pourrait secrètement juger les goûts vestimentaires de tout le monde ici ?' },
  { id: 'ml_hard_42', level: 'hard', text: 'Qui pourrait avoir fouillé dans le téléphone de quelqu\'un sans permission ?' },
  { id: 'ml_hard_43', level: 'hard', text: 'Qui pourrait avoir inventé une maladie pour ne pas aller quelque part ?' },
  { id: 'ml_hard_44', level: 'hard', text: 'Qui pourrait avoir menti sur son salaire, en plus ou en moins, selon l\'interlocuteur ?' },
  { id: 'ml_hard_45', level: 'hard', text: 'Qui pourrait rapporter une conversation privée à quelqu\'un qui ne devait pas la connaître ?' },
  { id: 'ml_hard_46', level: 'hard', text: 'Qui pourrait se mettre en mode "j\'entends tout" dans les conversations des autres sans participer ?' },
  { id: 'ml_hard_47', level: 'hard', text: 'Qui pourrait savoir un secret de quelqu\'un dans ce groupe et le garder pour ce soir ?' },
  { id: 'ml_hard_48', level: 'hard', text: 'Qui pourrait avoir fait une chose dont il/elle ne serait pas fier(e) si ses parents le savaient ?' },
  { id: 'ml_hard_49', level: 'hard', text: 'Qui pourrait prendre le crédit d\'une idée ou d\'un travail de quelqu\'un d\'autre ?' },
  { id: 'ml_hard_50', level: 'hard', text: 'Qui pourrait inventer une histoire pour paraître plus intéressant en soirée ?' },

  // Choix moraux & situations limites
  { id: 'ml_hard_51', level: 'hard', text: 'Qui pourrait choisir l\'argent plutôt que l\'amitié si les deux entraient en conflit ?' },
  { id: 'ml_hard_52', level: 'hard', text: 'Qui pourrait lire les messages de son/sa partenaire s\'il/elle en avait l\'occasion ?' },
  { id: 'ml_hard_53', level: 'hard', text: 'Qui pourrait sortir avec quelqu\'un juste pour ses invitations et ses bons restos ?' },
  { id: 'ml_hard_54', level: 'hard', text: 'Qui pourrait simuler une urgence pour sortir d\'un mauvais date ?' },
  { id: 'ml_hard_55', level: 'hard', text: 'Qui pourrait accepter une faveur et ne jamais la rendre ?' },
  { id: 'ml_hard_56', level: 'hard', text: 'Qui pourrait avoir participé à un ragot qu\'il savait faux ?' },
  { id: 'ml_hard_57', level: 'hard', text: 'Qui pourrait avoir pris une décision importante sous l\'influence de quelqu\'un d\'autre ?' },
  { id: 'ml_hard_58', level: 'hard', text: 'Qui pourrait trahir une confidence si ça l\'arrangeait vraiment ?' },
  { id: 'ml_hard_59', level: 'hard', text: 'Qui pourrait avoir dit du mal d\'une personne absente à cette soirée ?' },
  { id: 'ml_hard_60', level: 'hard', text: 'Qui pourrait avoir fait un choix honteux qu\'il a caché pendant des mois ?' },

  // Le croustillant pur
  { id: 'ml_hard_61', level: 'hard', text: 'Qui pourrait avoir eu un plan cul qu\'il a gardé secret de tout le groupe ?' },
  { id: 'ml_hard_62', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un le soir même de leur rencontre ?' },
  { id: 'ml_hard_63', level: 'hard', text: 'Qui pourrait avoir eu un crush sur un ami en couple sans jamais rien dire ?' },
  { id: 'ml_hard_64', level: 'hard', text: 'Qui pourrait avoir embrassé deux personnes différentes dans la même soirée ?' },
  { id: 'ml_hard_65', level: 'hard', text: 'Qui pourrait avoir utilisé quelqu\'un juste pour ne pas être seul(e) ?' },
  { id: 'ml_hard_66', level: 'hard', text: 'Qui pourrait avoir kiffé quelqu\'un dans ce groupe à un moment donné ?' },
  { id: 'ml_hard_67', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un qu\'il/elle n\'aurait jamais avoué ?' },
  { id: 'ml_hard_68', level: 'hard', text: 'Qui pourrait avoir flirté avec quelqu\'un juste pour voir jusqu\'où ça allait aller ?' },
  { id: 'ml_hard_69', level: 'hard', text: 'Qui pourrait avoir envoyé un nude et regretté instantanément ?' },
  { id: 'ml_hard_70', level: 'hard', text: 'Qui pourrait avoir fait semblant d\'être plus sage qu\'il/elle ne l\'est vraiment ?' },

  // Le passé & les dossiers
  { id: 'ml_hard_71', level: 'hard', text: 'Qui pourrait avoir une phase de sa vie dont il/elle ne parle jamais et qui serait gênante à révéler ?' },
  { id: 'ml_hard_72', level: 'hard', text: 'Qui pourrait avoir une photo ou une vidéo embarrassante de lui/elle quelque part sur internet ?' },
  { id: 'ml_hard_73', level: 'hard', text: 'Qui pourrait avoir eu un pseudo ou une phase emo/cosplay/autre qu\'il renie aujourd\'hui ?' },
  { id: 'ml_hard_74', level: 'hard', text: 'Qui pourrait avoir fait une erreur de jugement monumentale dont il a mis longtemps à se remettre ?' },
  { id: 'ml_hard_75', level: 'hard', text: 'Qui pourrait avoir eu un comportement dont il/elle a honte si on lui remontrait en vidéo ?' },
  { id: 'ml_hard_76', level: 'hard', text: 'Qui pourrait avoir eu un plan à trois (ou plus) ?' },
  { id: 'ml_hard_77', level: 'hard', text: 'Qui pourrait avoir dragué le/la meilleur(e) ami(e) de son/sa ex ?' },
  { id: 'ml_hard_78', level: 'hard', text: 'Qui pourrait avoir eu un surnom honteux au lycée ?' },
  { id: 'ml_hard_79', level: 'hard', text: 'Qui pourrait avoir fait quelque chose d\'illégal et ne s\'être jamais fait prendre ?' },
  { id: 'ml_hard_80', level: 'hard', text: 'Qui pourrait avoir passé une nuit en garde à vue ou s\'en être approché de peu ?' },

  // Confessions & vérités
  { id: 'ml_hard_81', level: 'hard', text: 'Qui pourrait avoir une dépendance secrète (sucre, shopping, réseaux...) qu\'il cache bien ?' },
  { id: 'ml_hard_82', level: 'hard', text: 'Qui pourrait avoir dépensé une somme qu\'il regrette encore pour une personne qui ne le méritait pas ?' },
  { id: 'ml_hard_83', level: 'hard', text: 'Qui pourrait avoir pleuré en regardant un match de foot ou un film qu\'il trouvait nul ?' },
  { id: 'ml_hard_84', level: 'hard', text: 'Qui pourrait avoir abandonné un ami dans une mauvaise situation pour éviter les ennuis ?' },
  { id: 'ml_hard_85', level: 'hard', text: 'Qui pourrait avoir fait croire qu\'il était occupé juste pour éviter une personne du groupe ?' },
  { id: 'ml_hard_86', level: 'hard', text: 'Qui pourrait avoir caché une relation parce qu\'il avait honte de la personne ?' },
  { id: 'ml_hard_87', level: 'hard', text: 'Qui pourrait avoir trompé quelqu\'un (même à moitié) et ne l\'avoir jamais dit ?' },
  { id: 'ml_hard_88', level: 'hard', text: 'Qui pourrait avoir été la raison d\'une rupture sans le dire ?' },
  { id: 'ml_hard_89', level: 'hard', text: 'Qui pourrait avoir fait une chose pour rendre quelqu\'un jaloux alors qu\'il n\'en avait rien à faire de lui ?' },
  { id: 'ml_hard_90', level: 'hard', text: 'Qui pourrait avoir dit "je t\'aime" sans vraiment le penser ?' },

  // Finance & deals
  { id: 'ml_hard_91', level: 'hard', text: 'Qui pourrait avoir "oublié" de rembourser une dette à un ami ?' },
  { id: 'ml_hard_92', level: 'hard', text: 'Qui pourrait avoir emprunté de l\'argent sans jamais avoir l\'intention de le rendre ?' },
  { id: 'ml_hard_93', level: 'hard', text: 'Qui pourrait avoir déclaré moins que ce qu\'il gagne pour bénéficier d\'un avantage ?' },
  { id: 'ml_hard_94', level: 'hard', text: 'Qui pourrait avoir fait un retour frauduleux pour récupérer son argent ?' },
  { id: 'ml_hard_95', level: 'hard', text: 'Qui pourrait avoir profité d\'une erreur en sa faveur sans la signaler ?' },
  { id: 'ml_hard_96', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de payer pour lui avec une excuse bidon ?' },
  { id: 'ml_hard_97', level: 'hard', text: 'Qui pourrait avoir dépensé son loyer dans une soirée ?' },
  { id: 'ml_hard_98', level: 'hard', text: 'Qui pourrait avoir misé de l\'argent sur quelque chose de stupide et perdu ?' },
  { id: 'ml_hard_99', level: 'hard', text: 'Qui pourrait avoir fait du cashback ou un bon plan limite légal pour s\'en sortir ?' },
  { id: 'ml_hard_100', level: 'hard', text: 'Qui pourrait avoir menti à ses parents sur où partait l\'argent qu\'ils lui donnaient ?' },

  // Honte & situations catastrophiques
  { id: 'ml_hard_101', level: 'hard', text: 'Qui pourrait avoir fait une scène dans un lieu public ?' },
  { id: 'ml_hard_102', level: 'hard', text: 'Qui pourrait avoir insulté quelqu\'un puis fait semblant que c\'était une blague ?' },
  { id: 'ml_hard_103', level: 'hard', text: 'Qui pourrait avoir été viré, plaqué ou mis à la porte en moins de 3 minutes ?' },
  { id: 'ml_hard_104', level: 'hard', text: 'Qui pourrait avoir échoué un examen ou entretien à cause d\'une gueule de bois ?' },
  { id: 'ml_hard_105', level: 'hard', text: 'Qui pourrait avoir manqué un avion, un train ou un RDV important par flemme ?' },
  { id: 'ml_hard_106', level: 'hard', text: 'Qui pourrait avoir volé la scène lors d\'une soirée organisée par quelqu\'un d\'autre ?' },
  { id: 'ml_hard_107', level: 'hard', text: 'Qui pourrait avoir fait une chose en soirée dont il/elle n\'a parlé à personne depuis ?' },
  { id: 'ml_hard_108', level: 'hard', text: 'Qui pourrait avoir pris la mauvaise décision de sa vie sous l\'influence d\'un groupe ?' },
  { id: 'ml_hard_109', level: 'hard', text: 'Qui pourrait avoir été expulsé d\'un lieu (bar, club, hôtel, transport...) ?' },
  { id: 'ml_hard_110', level: 'hard', text: 'Qui pourrait avoir accidentellement mis le feu (ou failli) à quelque chose ?' },

  // Séduction & manipulation
  { id: 'ml_hard_111', level: 'hard', text: 'Qui pourrait jouer la carte "j\'ai besoin de toi" pour attirer l\'attention de quelqu\'un ?' },
  { id: 'ml_hard_112', level: 'hard', text: 'Qui pourrait avoir utilisé quelqu\'un comme plan B en cas de plan A raté ?' },
  { id: 'ml_hard_113', level: 'hard', text: 'Qui pourrait donner de faux espoirs sans jamais avoir l\'intention de concrétiser ?' },
  { id: 'ml_hard_114', level: 'hard', text: 'Qui pourrait utiliser la jalousie comme arme de séduction ?' },
  { id: 'ml_hard_115', level: 'hard', text: 'Qui pourrait avoir entretenu une ambiguïté avec quelqu\'un juste pour son égo ?' },
  { id: 'ml_hard_116', level: 'hard', text: 'Qui pourrait flirter avec les ami(e)s de son/sa partenaire "juste pour voir" ?' },
  { id: 'ml_hard_117', level: 'hard', text: 'Qui pourrait avoir gardé un/une ex "en attente" pendant qu\'il/elle explorrait d\'autres options ?' },
  { id: 'ml_hard_118', level: 'hard', text: 'Qui pourrait avoir fait semblant d\'être plus intéressé qu\'il/elle ne l\'est pour ne pas blesser ?' },
  { id: 'ml_hard_119', level: 'hard', text: 'Qui pourrait avoir profité de quelqu\'un qui avait clairement un faible pour lui/elle ?' },
  { id: 'ml_hard_120', level: 'hard', text: 'Qui pourrait avoir fait revenir un/une ex et recommencer à l\'éviter juste après ?' },

  // Comportements en groupe
  { id: 'ml_hard_121', level: 'hard', text: 'Qui pourrait toujours rentrer chez lui avec quelqu\'un à la fin de la soirée ?' },
  { id: 'ml_hard_122', level: 'hard', text: 'Qui pourrait saboter un plan de groupe parce que ça ne l\'arrangeait pas ?' },
  { id: 'ml_hard_123', level: 'hard', text: 'Qui pourrait être le premier à "balance" un pote quand ça l\'arrange ?' },
  { id: 'ml_hard_124', level: 'hard', text: 'Qui pourrait avoir fait une chose honteuse en groupe dont il a maintenant une photo compromettante ?' },
  { id: 'ml_hard_125', level: 'hard', text: 'Qui pourrait écouter et participer à une conversation qu\'il n\'était pas censé entendre ?' },
  { id: 'ml_hard_126', level: 'hard', text: 'Qui pourrait avoir mis un ami dans l\'embarras pour faire rire les autres ?' },
  { id: 'ml_hard_127', level: 'hard', text: 'Qui pourrait avoir raconté des secrets d\'un pote sous couvert d\'anecdote ?' },
  { id: 'ml_hard_128', level: 'hard', text: 'Qui pourrait avoir joué double jeu entre deux groupes d\'amis ?' },
  { id: 'ml_hard_129', level: 'hard', text: 'Qui pourrait parler différemment selon les personnes à qui il/elle s\'adresse ?' },
  { id: 'ml_hard_130', level: 'hard', text: 'Qui pourrait avoir retourné un groupe contre quelqu\'un pour une raison égoïste ?' },

  // Vie numérique & excès
  { id: 'ml_hard_131', level: 'hard', text: 'Qui pourrait avoir créé un faux profil pour voir ce que les gens disaient de lui ?' },
  { id: 'ml_hard_132', level: 'hard', text: 'Qui pourrait avoir stalké quelqu\'un jusqu\'à retrouver l\'endroit exact sur une photo ?' },
  { id: 'ml_hard_133', level: 'hard', text: 'Qui pourrait avoir screenshotté une conversation privée et la montrer à quelqu\'un ?' },
  { id: 'ml_hard_134', level: 'hard', text: 'Qui pourrait avoir fait du catfishing, même une seule fois "pour rigoler" ?' },
  { id: 'ml_hard_135', level: 'hard', text: 'Qui pourrait avoir posté quelque chose en soirée et le regretter le lendemain matin ?' },
  { id: 'ml_hard_136', level: 'hard', text: 'Qui pourrait avoir un double compte Instagram que personne ne connaît ?' },
  { id: 'ml_hard_137', level: 'hard', text: 'Qui pourrait avoir scrollé les réseaux d\'un ex jusqu\'à remonter 3 ans en arrière ?' },
  { id: 'ml_hard_138', level: 'hard', text: 'Qui pourrait avoir répondu à une story de quelqu\'un juste pour ouvrir la porte à une conversation ?' },
  { id: 'ml_hard_139', level: 'hard', text: 'Qui pourrait avoir bloqué quelqu\'un puis créé un faux compte pour continuer à le/la surveiller ?' },
  { id: 'ml_hard_140', level: 'hard', text: 'Qui pourrait avoir exagéré sa vie sur les réseaux jusqu\'à y croire lui-même ?' },

  // Les défis ultimes
  { id: 'ml_hard_141', level: 'hard', text: 'Qui pourrait avoir couché avec quelqu\'un d\'un groupe d\'amis et ne jamais l\'avoir dit ?' },
  { id: 'ml_hard_142', level: 'hard', text: 'Qui pourrait avoir fait un truc en soirée qui lui coûterait sa réputation s\'il était filmé ?' },
  { id: 'ml_hard_143', level: 'hard', text: 'Qui pourrait avoir dansé de façon totalement indécente en pensant que personne ne regardait ?' },
  { id: 'ml_hard_144', level: 'hard', text: 'Qui pourrait avoir eu une aventure lors d\'un séjour ou d\'un voyage de groupe ?' },
  { id: 'ml_hard_145', level: 'hard', text: 'Qui pourrait avoir besoin d\'une soirée entière pour raconter tout ce qu\'il a fait ?' },
  { id: 'ml_hard_146', level: 'hard', text: 'Qui pourrait avoir convaincu quelqu\'un de faire quelque chose de stupide juste pour le film ?' },
  { id: 'ml_hard_147', level: 'hard', text: 'Qui pourrait avoir une histoire de soirée tellement folle qu\'il refuse encore d\'en parler ?' },
  { id: 'ml_hard_148', level: 'hard', text: 'Qui pourrait avoir pris une photo ou une vidéo de quelqu\'un sans consentement ?' },
  { id: 'ml_hard_149', level: 'hard', text: 'Qui pourrait avoir eu un pari ou un défi qui a mal tourné et gardé ça pour lui ?' },
  { id: 'ml_hard_150', level: 'hard', text: 'Qui pourrait avoir fait le plus de dégâts dans une soirée et s\'en être sorti sans punition ?' },
]
