export type NhieLevel = 'soft' | 'medium' | 'hard'

export interface NhieQuestion {
  text: string
  level: NhieLevel
}

export const NHIE_QUESTIONS: NhieQuestion[] = [
  // ─── SOFT (100) ───────────────────────────────────────────────────────────
  { level: 'soft', text: 'mangé de la nourriture tombée par terre' },
  { level: 'soft', text: 'dormi avec une peluche à l\'âge adulte' },
  { level: 'soft', text: 'chanté à tue-tête seul(e) dans la voiture' },
  { level: 'soft', text: 'envoyé un message à la mauvaise personne' },
  { level: 'soft', text: 'pleuré devant un film d\'animation' },
  { level: 'soft', text: 'oublié le prénom de quelqu\'un juste après l\'avoir rencontré' },
  { level: 'soft', text: 'commandé de la pizza à 2h du matin' },
  { level: 'soft', text: 'regardé une série entière en une seule journée' },
  { level: 'soft', text: 'fait semblant de dormir pour éviter quelqu\'un' },
  { level: 'soft', text: 'mangé de la pâte à cookie crue' },
  { level: 'soft', text: 'parlé tout seul en public' },
  { level: 'soft', text: 'cherché mon téléphone alors que je l\'avais à la main' },
  { level: 'soft', text: 'liké accidentellement une vieille photo en scrollant trop loin' },
  { level: 'soft', text: 'bu du lait directement dans la bouteille' },
  { level: 'soft', text: 'mis des vêtements à l\'envers sans m\'en rendre compte' },
  { level: 'soft', text: 'fait tomber mon plateau à la cafétéria devant tout le monde' },
  { level: 'soft', text: 'glissé et fait semblant que c\'était volontaire' },
  { level: 'soft', text: 'passé plus de 3h sur les réseaux sociaux en une journée' },
  { level: 'soft', text: 'oublié un anniversaire important' },
  { level: 'soft', text: 'acheté quelque chose que je n\'ai jamais utilisé' },
  { level: 'soft', text: 'pris un détour pour éviter quelqu\'un dans la rue' },
  { level: 'soft', text: 'dormi dans les transports et loupé mon arrêt' },
  { level: 'soft', text: 'fait une sieste censée durer 20 minutes qui a duré 3h' },
  { level: 'soft', text: 'mangé des restes froids directement dans le frigo' },
  { level: 'soft', text: 'passé plus de temps à choisir quoi regarder qu\'à regarder quelque chose' },
  { level: 'soft', text: 'inventé une excuse pour sortir d\'un appel téléphonique' },
  { level: 'soft', text: 'lu la fin d\'un livre avant d\'avoir lu le milieu' },
  { level: 'soft', text: 'sniffé un vêtement pour savoir s\'il était encore propre' },
  { level: 'soft', text: 'fait semblant d\'aimer un cadeau que je détestais' },
  { level: 'soft', text: 'ri tout seul en me souvenant d\'un souvenir dans un lieu public' },
  { level: 'soft', text: 'porté les mêmes chaussettes deux jours de suite' },
  { level: 'soft', text: 'eu une conversation entière avec mon animal de compagnie' },
  { level: 'soft', text: 'pleuré à cause d\'une pub' },
  { level: 'soft', text: 'cherché des symptômes sur Google et conclu que j\'avais une maladie grave' },
  { level: 'soft', text: 'mangé le dernier morceau en espérant que personne ne le remarque' },
  { level: 'soft', text: 'essayé de marcher silencieusement la nuit pour ne pas réveiller quelqu\'un' },
  { level: 'soft', text: 'inventé des paroles à une chanson instrumentale' },
  { level: 'soft', text: 'posté puis supprimé une story ou un post' },
  { level: 'soft', text: 'répondu "toi aussi" quand le serveur m\'a dit "bon appétit"' },
  { level: 'soft', text: 'dessiné quelque chose de honteux dans les marges de mon cahier' },
  { level: 'soft', text: 'mangé du chocolat en cachette pour ne pas partager' },
  { level: 'soft', text: 'passé 30 minutes à choisir une photo de profil' },
  { level: 'soft', text: 'raté une poignée de main et transformé ça en geste bizarre' },
  { level: 'soft', text: 'regardé le même épisode d\'une série plus de 3 fois' },
  { level: 'soft', text: 'eu une chanson dans la tête toute une journée sans pouvoir m\'en débarrasser' },
  { level: 'soft', text: 'essayé de changer de chaîne avec mon téléphone' },
  { level: 'soft', text: 'oublié de répondre à un message et m\'en souvenu des semaines plus tard' },
  { level: 'soft', text: 'fait semblant de comprendre quelque chose qu\'on m\'expliquait' },
  { level: 'soft', text: 'eu une dispute avec quelqu\'un dans ma tête' },
  { level: 'soft', text: 'mangé de la confiture directement dans le pot' },
  { level: 'soft', text: 'regardé des compilations de chutes de gens pendant plus de 30 minutes' },
  { level: 'soft', text: 'créé un compte sur un réseau social juste pour stalker quelqu\'un' },
  { level: 'soft', text: 'acheté un livre uniquement pour sa couverture' },
  { level: 'soft', text: 'collectionné quelque chose d\'inutile pendant des années' },
  { level: 'soft', text: 'fabriqué une cabane en coussins à l\'âge adulte' },
  { level: 'soft', text: 'mangé du dentifrice quand j\'étais petit(e)' },
  { level: 'soft', text: 'fait une sieste dans ma voiture sur un parking' },
  { level: 'soft', text: 'couru pour attraper quelque chose et tout raté devant des gens' },
  { level: 'soft', text: 'eu peur d\'une scène de film qui n\'était pas censée faire peur' },
  { level: 'soft', text: 'préféré rester seul(e) plutôt que sortir quand j\'avais quelque chose de prévu' },
  { level: 'soft', text: 'regardé une recette compliquée et finalement commandé en livraison' },
  { level: 'soft', text: 'eu la flemme de me lever et attrapé quelque chose avec mon pied' },
  { level: 'soft', text: 'acheté des légumes qui ont fini à la poubelle sans jamais avoir été mangés' },
  { level: 'soft', text: 'mis du sel à la place du sucre dans quelque chose' },
  { level: 'soft', text: 'pris une photo de mon repas avant de manger' },
  { level: 'soft', text: 'regardé des tutoriels sans jamais appliquer ce que j\'avais appris' },
  { level: 'soft', text: 'joué à un jeu mobile pendant plus d\'une heure d\'affilée' },
  { level: 'soft', text: 'oublié ce que j\'allais dire au milieu d\'une phrase' },
  { level: 'soft', text: 'chanté une chanson en inventant des paroles au fur et à mesure' },
  { level: 'soft', text: 'mâché un chewing-gum sans m\'en souvenir et le retrouver collé quelque part' },
  { level: 'soft', text: 'recopié des devoirs de quelqu\'un d\'autre' },
  { level: 'soft', text: 'mis une alarme "au cas où" que je n\'ai jamais entendue' },
  { level: 'soft', text: 'envoyé un message d\'anniversaire avec un jour de retard' },
  { level: 'soft', text: 'essayé de parler une autre langue et complètement échoué' },
  { level: 'soft', text: 'écouté la même chanson en boucle toute une semaine' },
  { level: 'soft', text: 'voulu rappeler quelqu\'un et oublié qui c\'était' },
  { level: 'soft', text: 'accepté une invitation juste pour la nourriture gratuite' },
  { level: 'soft', text: 'joué à cache-cache avec mes parents pour éviter une corvée' },
  { level: 'soft', text: 'menti sur le fait d\'avoir lu un livre que je n\'ai pas lu' },
  { level: 'soft', text: 'essayé de faire un geste cool et raté devant tout le monde' },
  { level: 'soft', text: 'commandé la même chose à chaque fois dans un restaurant' },
  { level: 'soft', text: 'regardé des vidéos de bébés animaux pendant plus d\'une heure' },
  { level: 'soft', text: 'passé un trajet entier à regarder les gens par la fenêtre du train' },
  { level: 'soft', text: 'fait du air guitar ou air drums seul(e) chez moi' },
  { level: 'soft', text: 'eu des crampes à force de trop rire' },
  { level: 'soft', text: 'rebranché mes écouteurs au mauvais moment dans un lieu public' },
  { level: 'soft', text: 'trouvé quelque chose par terre et l\'avoir gardé' },
  { level: 'soft', text: 'sauté les pages ennuyeuses d\'un livre pour aller à la fin' },
  { level: 'soft', text: 'regardé un film triste juste pour avoir une excuse de pleurer' },
  { level: 'soft', text: 'fait semblant de ne pas entendre quelqu\'un qui m\'appelait' },
  { level: 'soft', text: 'gardé un objet cassé parce que je n\'arrivais pas à m\'en séparer' },
  { level: 'soft', text: 'rêvé d\'un inconnu et essayé de savoir qui c\'était dans la vraie vie' },
  { level: 'soft', text: 'commencé une phrase et changé de sujet à mi-chemin' },
  { level: 'soft', text: 'fait semblant d\'être malade pour rester chez moi' },
  { level: 'soft', text: 'préféré envoyer un message plutôt qu\'appeler pour éviter de parler' },
  { level: 'soft', text: 'perdu aux ciseaux-papier-pierre plusieurs fois de suite contre la même personne' },
  { level: 'soft', text: 'menti sur combien j\'aimais un plat pour ne pas vexer quelqu\'un qui l\'avait cuisiné' },
  { level: 'soft', text: 'essayé une tendance TikTok tout seul(e) chez moi' },
  { level: 'soft', text: 'dormi sur mon téléphone et retrouvé un message envoyé que je n\'avais aucun souvenir d\'avoir tapé' },
  { level: 'soft', text: 'remis des vêtements dans l\'armoire sans les avoir lavés pour éviter de faire la lessive' },

  // ─── MEDIUM (100) ─────────────────────────────────────────────────────────
  { level: 'medium', text: 'menti à mes parents sur où je dormais' },
  { level: 'medium', text: 'embrassé quelqu\'un le soir de notre rencontre' },
  { level: 'medium', text: 'bu jusqu\'à ne plus me souvenir de la soirée' },
  { level: 'medium', text: 'envoyé un SMS ivre que j\'ai regretté le lendemain' },
  { level: 'medium', text: 'flirté avec quelqu\'un en couple' },
  { level: 'medium', text: 'dansé sur une table en soirée' },
  { level: 'medium', text: 'fait du ghosting à quelqu\'un que je fréquentais' },
  { level: 'medium', text: 'dragué quelqu\'un pour gagner un pari' },
  { level: 'medium', text: 'inventé une urgence pour quitter une soirée' },
  { level: 'medium', text: 'embrassé l\'ex de quelqu\'un de ma bande' },
  { level: 'medium', text: 'menti à mon/ma partenaire pour avoir une soirée libre' },
  { level: 'medium', text: 'pris un taxi seul(e) à 4h du matin' },
  { level: 'medium', text: 'dormi dans mes vêtements de soirée' },
  { level: 'medium', text: 'perdu mon téléphone en soirée' },
  { level: 'medium', text: 'embrassé plus de 3 personnes dans la même soirée' },
  { level: 'medium', text: 'sauté par-dessus une barrière pour entrer quelque part gratuitement' },
  { level: 'medium', text: 'raconté les secrets d\'un(e) ami(e) à quelqu\'un d\'autre' },
  { level: 'medium', text: 'utilisé quelqu\'un pour rendre un/une ex jaloux/jalouse' },
  { level: 'medium', text: 'fui une soirée sans dire au revoir à personne' },
  { level: 'medium', text: 'commis une infraction au code de la route (même légère)' },
  { level: 'medium', text: 'acheté des billets pour un événement et pas y être allé' },
  { level: 'medium', text: 'créé un faux profil sur un réseau social' },
  { level: 'medium', text: 'lu le journal intime ou les messages privés de quelqu\'un' },
  { level: 'medium', text: 'laissé croire à quelqu\'un que j\'avais des sentiments alors que non' },
  { level: 'medium', text: 'ouvert un cadeau avant Noël' },
  { level: 'medium', text: 'payé quelqu\'un pour faire un devoir ou un exposé à ma place' },
  { level: 'medium', text: 'dépensé plus d\'argent que prévu en soirée et menti dessus' },
  { level: 'medium', text: 'dragué un(e) serveur/serveuse et laissé mon numéro' },
  { level: 'medium', text: 'copié-collé le même message à plusieurs personnes simultanément' },
  { level: 'medium', text: 'dit "je t\'aime" sans vraiment le penser' },
  { level: 'medium', text: 'raconté une histoire entièrement inventée comme si elle était vraie' },
  { level: 'medium', text: 'essayé de faire venir quelqu\'un à une soirée uniquement parce que je le/la trouvais attirant(e)' },
  { level: 'medium', text: 'demandé le numéro de quelqu\'un juste pour voir si ça marcherait' },
  { level: 'medium', text: 'bu avant 18h sans occasion particulière' },
  { level: 'medium', text: 'menti sur mon expérience dans quelque chose pour paraître plus cool' },
  { level: 'medium', text: 'eu une dispute par message qui aurait pu se régler en deux secondes en vrai' },
  { level: 'medium', text: 'rompu avec quelqu\'un par message ou par texto' },
  { level: 'medium', text: 'fréquenté deux personnes en même temps sans que l\'une sache pour l\'autre' },
  { level: 'medium', text: 'donné un faux numéro à quelqu\'un en boîte' },
  { level: 'medium', text: 'dragué le/la colocataire d\'un(e) ami(e)' },
  { level: 'medium', text: 'menti sur combien de personnes j\'ai fréquentées' },
  { level: 'medium', text: 'dépensé de l\'argent que je n\'avais pas' },
  { level: 'medium', text: 'flirté par messages en étant officiellement en couple' },
  { level: 'medium', text: 'donné un surnom moqueur à quelqu\'un dans mon dos' },
  { level: 'medium', text: 'imité un(e) ami(e) derrière son dos' },
  { level: 'medium', text: 'menti à un médecin pour obtenir un arrêt de travail' },
  { level: 'medium', text: 'quitté un groupe WhatsApp et bloqué les notifications immédiatement' },
  { level: 'medium', text: 'participé à un défi stupide sous la pression des amis' },
  { level: 'medium', text: 'laissé quelqu\'un payer à ma place en faisant semblant d\'avoir oublié mon portefeuille' },
  { level: 'medium', text: 'fait des commérages sur un(e) collègue' },
  { level: 'medium', text: 'simulé un appel téléphonique pour couper une conversation' },
  { level: 'medium', text: 'dit du mal de quelqu\'un à qui je souriais deux minutes avant' },
  { level: 'medium', text: 'envoyé une capture d\'écran d\'une conversation privée à quelqu\'un d\'autre' },
  { level: 'medium', text: 'affirmé avoir terminé quelque chose que je n\'avais pas commencé' },
  { level: 'medium', text: 'cherché des infos sur un(e) ex en mode vrai détective (LinkedIn, Instagram privé, etc.)' },
  { level: 'medium', text: 'menti sur mes habitudes de consommation d\'alcool ou de tabac à ma famille' },
  { level: 'medium', text: 'menti sur mon âge sur une appli de rencontre' },
  { level: 'medium', text: 'inventé une relation amoureuse fictive pour impressionner quelqu\'un' },
  { level: 'medium', text: 'utilisé une application de rencontre juste par ennui sans vraie intention' },
  { level: 'medium', text: 'obtenu quelque chose grâce au charme plutôt qu\'au mérite' },
  { level: 'medium', text: 'regardé des stories anonymement via un compte secondaire' },
  { level: 'medium', text: 'pris une décision importante uniquement sous l\'impulsion de l\'alcool' },
  { level: 'medium', text: 'répondu à un(e) ex en mode "ça va" alors que ça n\'allait pas du tout' },
  { level: 'medium', text: 'enregistré une conversation sans que l\'autre le sache' },
  { level: 'medium', text: 'menti à un employeur sur mon CV' },
  { level: 'medium', text: 'gardé de l\'argent que j\'avais trouvé par terre sans chercher le propriétaire' },
  { level: 'medium', text: 'annulé des plans à la dernière minute avec une fausse excuse' },
  { level: 'medium', text: 'menti sur mes sentiments pour ne pas blesser quelqu\'un' },
  { level: 'medium', text: 'ouvert une bouteille de champagne et renversé la moitié' },
  { level: 'medium', text: 'raté un entretien intentionnellement parce que je ne voulais pas vraiment ce poste' },
  { level: 'medium', text: 'passé une soirée entière à regarder le profil de quelqu\'un que je n\'avais pas revu depuis des années' },
  { level: 'medium', text: 'menti sur combien j\'avais bu ce soir-là' },
  { level: 'medium', text: 'dragué quelqu\'un qui était clairement en couple' },
  { level: 'medium', text: 'fait une blague sur quelqu\'un sans qu\'il/elle sache que c\'était sur lui/elle' },
  { level: 'medium', text: 'menti sur ma situation financière pour impressionner quelqu\'un' },
  { level: 'medium', text: 'fait semblant d\'être plus sobre que je ne l\'étais' },
  { level: 'medium', text: 'sauté une journée entière de cours sans avertir personne' },
  { level: 'medium', text: 'changé mon avis sur quelqu\'un uniquement parce qu\'une autre personne m\'y avait influencé' },
  { level: 'medium', text: 'menti sur mes sentiments romantiques pour éviter une conversation difficile' },
  { level: 'medium', text: 'utilisé la jalousie comme outil de manipulation dans une relation' },
  { level: 'medium', text: 'flirté avec quelqu\'un en étant avec quelqu\'un d\'autre en face' },
  { level: 'medium', text: 'fait semblant d\'avoir vu un film que je n\'ai pas vu pour paraître cultivé' },
  { level: 'medium', text: 'volontairement ignoré quelqu\'un qui m\'envoyait des messages en boucle' },
  { level: 'medium', text: 'mentionné un(e) ex en cours de discussion pour susciter de la jalousie' },
  { level: 'medium', text: 'suivi quelqu\'un sur les réseaux juste pour surveiller ce qu\'il/elle faisait' },
  { level: 'medium', text: 'fait semblant de ne pas parler une langue pour éviter d\'avoir à l\'utiliser' },
  { level: 'medium', text: 'menti à mes parents sur combien je gagnais' },
  { level: 'medium', text: 'volé de la nourriture dans le frigo d\'un(e) colocataire ou ami(e)' },
  { level: 'medium', text: 'mis une photo de profil très retouchée qui ne me ressemble pas vraiment' },
  { level: 'medium', text: 'dragué quelqu\'un juste pour voir si ça marchait, sans intention sérieuse' },
  { level: 'medium', text: 'mangé quelque chose d\'inconnu et prétendu aimer ça pour ne pas vexer' },
  { level: 'medium', text: 'joué la comédie pour attirer l\'attention de quelqu\'un qui ne s\'intéressait pas à moi' },
  { level: 'medium', text: 'menti sur mon statut amoureux à quelqu\'un qui me plaisait' },
  { level: 'medium', text: 'partagé une rumeur que je savais peut-être fausse' },
  { level: 'medium', text: 'baragouiné dans une autre langue pour impressionner quelqu\'un' },
  { level: 'medium', text: 'fait semblant de ne pas reconnaître quelqu\'un pour éviter de lui parler' },
  { level: 'medium', text: 'gardé un secret sur quelqu\'un alors que je savais que ça aurait dû être dit' },
  { level: 'medium', text: 'pris quelqu\'un en photo en soirée sans qu\'il/elle le sache' },
  { level: 'medium', text: 'utilisé une excuse médicale qui n\'était pas vraie' },
  { level: 'medium', text: 'embrassé quelqu\'un uniquement parce que j\'étais ivre' },

  // ─── HARD (100) ───────────────────────────────────────────────────────────
  { level: 'hard', text: 'envoyé des photos osées (nudes) à quelqu\'un' },
  { level: 'hard', text: 'eu une aventure d\'un soir' },
  { level: 'hard', text: 'été attiré(e) par le/la partenaire d\'un(e) ami(e) proche' },
  { level: 'hard', text: 'couché avec quelqu\'un sans retenir son prénom le lendemain' },
  { level: 'hard', text: 'eu une relation dans un lieu public ou inhabituel' },
  { level: 'hard', text: 'sexté avec quelqu\'un' },
  { level: 'hard', text: 'fantasmé sur quelqu\'un présent dans cette pièce ce soir' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un de significativement plus âgé ou plus jeune' },
  { level: 'hard', text: 'fait semblant d\'avoir eu un orgasme' },
  { level: 'hard', text: 'eu des sentiments pour un(e) ami(e) qui était en couple' },
  { level: 'hard', text: 'couché avec l\'ex de quelqu\'un de proche' },
  { level: 'hard', text: 'eu une relation non officielle avec quelqu\'un qui était en couple' },
  { level: 'hard', text: 'tenté de séduire quelqu\'un juste pour voir si je pouvais, sans intention réelle' },
  { level: 'hard', text: 'eu une aventure lors d\'un voyage loin de chez moi' },
  { level: 'hard', text: 'regardé du contenu pour adultes au travail ou en cours' },
  { level: 'hard', text: 'utilisé quelqu\'un physiquement sans aucun intérêt romantique' },
  { level: 'hard', text: 'menti à un(e) partenaire sur ce que j\'avais fait la nuit précédente' },
  { level: 'hard', text: 'eu un plan cul récurrent pendant plus de 2 mois sans aucun sentiment' },
  { level: 'hard', text: 'flashé ou montré une partie de mon corps en public' },
  { level: 'hard', text: 'couché avec quelqu\'un juste pour rendre un(e) ex jaloux/jalouse' },
  { level: 'hard', text: 'fait semblant d\'aimer quelqu\'un pour obtenir quelque chose' },
  { level: 'hard', text: 'envoyé un nude accidentellement à la mauvaise personne' },
  { level: 'hard', text: 'regardé discrètement quelqu\'un se changer sans que ça soit prévu' },
  { level: 'hard', text: 'couché avec quelqu\'un le jour même de notre rencontre' },
  { level: 'hard', text: 'acheté ou regardé du contenu pour adultes payant' },
  { level: 'hard', text: 'eu une relation avec un(e) professeur, coach ou supérieur(e) hiérarchique' },
  { level: 'hard', text: 'eu des relations dans une voiture' },
  { level: 'hard', text: 'sexté avec quelqu\'un que je n\'avais jamais rencontré en vrai' },
  { level: 'hard', text: 'menti sur le nombre de partenaires que j\'ai eu' },
  { level: 'hard', text: 'trompé quelqu\'un avec qui j\'étais officiellement en couple' },
  { level: 'hard', text: 'su que quelqu\'un était trompé et n\'avoir rien dit' },
  { level: 'hard', text: 'été surpris(e) ou avoir surpris quelqu\'un dans un moment intime' },
  { level: 'hard', text: 'participé à un strip-poker ou jeu avec déshabillage' },
  { level: 'hard', text: 'fait le premier pas de façon très directe et osée' },
  { level: 'hard', text: 'embrassé quelqu\'un en public uniquement pour rendre un(e) ex jaloux/jalouse' },
  { level: 'hard', text: 'utilisé une application pour trouver quelqu\'un pour la nuit uniquement' },
  { level: 'hard', text: 'discuté de ma vie sexuelle avec quelqu\'un que je connaissais à peine' },
  { level: 'hard', text: 'couché avec quelqu\'un et regretté immédiatement après' },
  { level: 'hard', text: 'eu des relations alors que quelqu\'un dormait dans la pièce d\'à côté' },
  { level: 'hard', text: 'regardé du porno avec quelqu\'un' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un que je ne supportais pas en dehors du contexte physique' },
  { level: 'hard', text: 'été filmé(e) ou photographié(e) dans un moment intime' },
  { level: 'hard', text: 'couché avec quelqu\'un par pure curiosité alors que je n\'étais pas vraiment attiré(e)' },
  { level: 'hard', text: 'eu une relation physique avec plus d\'une personne dans la même soirée' },
  { level: 'hard', text: 'cherché activement à séduire quelqu\'un dont je savais qu\'il/elle était en relation' },
  { level: 'hard', text: 'partagé des secrets intimes d\'un(e) ex avec quelqu\'un d\'autre' },
  { level: 'hard', text: 'proposé ou reçu une proposition d\'un(e) ami(e) de longue date' },
  { level: 'hard', text: 'simulé l\'amour pour ne pas blesser quelqu\'un avec qui j\'avais une relation physique' },
  { level: 'hard', text: 'gardé des photos osées d\'un(e) ex après la rupture' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un en couple tout en sachant qu\'il/elle ne romprait jamais' },
  { level: 'hard', text: 'embrassé quelqu\'un juste après avoir embrassé quelqu\'un d\'autre dans la même soirée' },
  { level: 'hard', text: 'fait quelque chose de sexuellement inhabituel que je ne referais jamais' },
  { level: 'hard', text: 'couché avec deux personnes différentes dans la même semaine' },
  { level: 'hard', text: 'flirté sérieusement avec quelqu\'un le lendemain d\'une rupture' },
  { level: 'hard', text: 'eu une relation pendant laquelle je pensais à quelqu\'un d\'autre' },
  { level: 'hard', text: 'tenu une relation secrète pendant plus de 3 mois sans que personne le sache' },
  { level: 'hard', text: 'eu des pensées très claires sur quelqu\'un dans cette pièce ce soir' },
  { level: 'hard', text: 'saboté la relation d\'un(e) ami(e) parce que j\'étais attiré(e) par son/sa partenaire' },
  { level: 'hard', text: 'utilisé quelqu\'un émotionnellement tout en sachant que je n\'avais aucune intention sérieuse' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un le soir même d\'une rupture avec quelqu\'un d\'autre' },
  { level: 'hard', text: 'regardé les messages d\'un(e) partenaire sans sa permission' },
  { level: 'hard', text: 'couché avec quelqu\'un que je ne supportais pas' },
  { level: 'hard', text: 'joué à un jeu de défi sexuel lors d\'une soirée' },
  { level: 'hard', text: 'eu un "ami(e) avec avantages" pendant plus de 6 mois sans jamais aborder le sujet' },
  { level: 'hard', text: 'fait quelque chose d\'intime dont je ne me souviens pas clairement le lendemain' },
  { level: 'hard', text: 'eu une conversation très explicitement sexuelle par message juste pour tester' },
  { level: 'hard', text: 'fait quelque chose en soirée dont je suis sûr(e) que personne dans cette pièce ne le sait' },
  { level: 'hard', text: 'proposé ou participé à un jeu de rôle dans un contexte intime' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un uniquement pour ses avantages (argent, logement, etc.)' },
  { level: 'hard', text: 'participé à une conversation de groupe à caractère sexuel' },
  { level: 'hard', text: 'eu une relation intime avec un(e) inconnu(e) rencontré(e) dans les transports' },
  { level: 'hard', text: 'utilisé la réconciliation après une dispute comme prétexte à une relation physique' },
  { level: 'hard', text: 'tenu une double vie amoureuse pendant plus d\'un mois' },
  { level: 'hard', text: 'eu une attirance pour quelqu\'un que je devais absolument ne pas fréquenter' },
  { level: 'hard', text: 'couché avec quelqu\'un de la même famille (ex : deux ami(e)s frères/sœurs)' },
  { level: 'hard', text: 'participé à un plan à trois ou avoir sérieusement envisagé de le faire' },
  { level: 'hard', text: 'envoyé une photo de moi très peu habillé(e) sans vraiment y réfléchir' },
  { level: 'hard', text: 'eu une relation physique dans les toilettes d\'un lieu public' },
  { level: 'hard', text: 'menti sur le fait d\'avoir été avec quelqu\'un pour éviter la jalousie' },
  { level: 'hard', text: 'eu des relations sexuelles en plein air' },
  { level: 'hard', text: 'été payé(e) ou avoir payé pour une soirée romantique avec quelqu\'un' },
  { level: 'hard', text: 'fait quelque chose d\'intime filmé ou photographié volontairement' },
  { level: 'hard', text: 'eu une attirance réelle pour le/la meilleur(e) ami(e) de mon/ma partenaire' },
  { level: 'hard', text: 'commencé une relation uniquement parce que j\'étais seul(e) et qu\'on était disponibles' },
  { level: 'hard', text: 'simulé d\'être libre pour séduire quelqu\'un alors que je ne l\'étais pas' },
  { level: 'hard', text: 'eu une relation avec quelqu\'un que je venais tout juste de rencontrer sur une appli le jour même' },
  { level: 'hard', text: 'raté un rendez-vous intime parce que je n\'en voulais plus au dernier moment et menti sur la raison' },
  { level: 'hard', text: 'regretté une relation physique au point de mentir sur le fait qu\'elle a eu lieu' },
  { level: 'hard', text: 'eu une discussion "je t\'aime mais suis pas amoureux(se)" uniquement pour garder la personne disponible' },
  { level: 'hard', text: 'eu un coup de foudre pour quelqu\'un lors d\'un mariage ou d\'un enterrement' },
  { level: 'hard', text: 'couché avec quelqu\'un en sachant très bien que je ne le/la reverrais pas' },
  { level: 'hard', text: 'accepté une relation physique uniquement pour ne pas décevoir l\'autre' },
  { level: 'hard', text: 'eu des relations avec quelqu\'un juste pour oublier quelqu\'un d\'autre' },
  { level: 'hard', text: 'envoyé un message à caractère sexuel à quelqu\'un de ma connaissance pour voir sa réaction' },
  { level: 'hard', text: 'eu une relation physique dans un lieu où on aurait pu se faire attraper' },
  { level: 'hard', text: 'dit "c\'était la dernière fois" et recommencé plusieurs fois' },
  { level: 'hard', text: 'trompé quelqu\'un et avoué uniquement parce que j\'avais peur d\'être découvert(e)' },
  { level: 'hard', text: 'fait quelque chose d\'osé en soirée dont toutes les personnes présentes ce soir ont entendu parler' },
  { level: 'hard', text: 'intentionnellement laissé quelqu\'un développer des sentiments pour moi sans aucune intention d\'y répondre' },
  { level: 'hard', text: 'embrassé quelqu\'un en sachant très bien que mon/ma partenaire le/la connaissait' },
]
