export interface TODQuestion {
  id: string;
  type: 'truth' | 'action';
  level: 'soft' | 'medium' | 'hard';
  text: string;
}

const truths = [
  "Quel est le dernier compte Instagram que tu as stalké en cachette ?",
  "Quelle est ta pire photo de carte d'identité ou de passeport ?",
  "As-tu déjà swipé à droite sur quelqu'un que tu connaissais juste pour voir ?",
  "Quel est le message le plus gênant que tu aies envoyé à tes parents par erreur ?",
  "As-tu déjà utilisé l'excuse du 'bug de connexion' pour fuir un appel ?",
  "Quel est ton pire date Tinder à ce jour ?",
  "Quelle est la chanson que tu mets à fond quand tu as un coup de blues ?",
  "Quel est le surnom le plus honteux qu'on t'ait donné au lycée ?",
  "As-tu déjà pleuré devant une vidéo TikTok ?",
  "Quelle est la chose la plus bizarre que tu aies faite pour attirer l'attention de ton crush ?",
  "Quel est ton plaisir coupable sur Netflix ou YouTube ?",
  "Quelle est l'anecdote la plus absurde qui te soit arrivée en cours ?",
  "As-tu déjà fouillé dans le téléphone de ton ou ta partenaire ?",
  "Quel est le pire cadeau que tu aies offert à quelqu'un en pensant bien faire ?",
  "Quelle est ta plus grande peur irrationnelle ?",
  "Quel est ton pire mensonge lors d'un entretien d'embauche ?",
  "As-tu déjà ghosté quelqu'un sans aucune raison valable ?",
  "Quel est le dernier achat inutile que tu as fait sur Internet ?",
  "Quelle est la rumeur la plus folle que tu aies entendue sur toi-même ?",
  "As-tu déjà simulé d'être malade pour sécher un événement social ?",
  "Quelle est ta pire expérience dans les transports en commun ?",
  "Quel est le plat que tu cuisines quand tu as la flemme absolue ?",
  "Quelle est ta pire gaffe lors d'un repas de famille ?",
  "As-tu déjà créé un faux profil sur les réseaux sociaux ?",
  "Quel est ton complexe physique le plus ridicule ?",
  "Quelle est la série honteuse que tu as regardée en entier ?",
  "Quel est ton pire tue-l'amour lors d'un premier rendez-vous ?",
  "As-tu déjà fouillé les affaires d'un ami quand tu étais seul(e) chez lui ?",
  "Quelle est la chose la plus enfantine que tu fasses encore aujourd'hui ?",
  "Quel est ton pire souvenir lié à l'alcool (sans être hardcore) ?",
  "As-tu déjà eu un crush inavouable pour le parent d'un pote ?",
  "Quelle est l'excuse la plus bidon que tu aies sortie pour arriver en retard ?",
  "Quel est ton pire fail en essayant de flirter ?",
  "As-tu déjà pleuré pour obtenir quelque chose ?",
  "Quelle est la tendance mode que tu regrettes d'avoir suivie ?",
  "Quel est le pire conseil que tu aies donné à un ami ?",
  "As-tu déjà été surpris(e) en train de parler tout(e) seul(e) ?",
  "Quelle est la recherche Google la plus bizarre de ton historique ?",
  "Quel est ton pire souvenir de vacances entre amis ?",
  "As-tu déjà menti sur ton âge pour paraître plus vieux/vieille ?",
  "Quelle est ta pire phobie liée aux animaux ?",
  "Quel est le dernier SMS que tu as envoyé ?",
  "As-tu déjà liké une vieille photo Instagram par erreur en stalkant ?",
  "Quelle est la célébrité qui te fait le plus fantasmer en secret ?",
  "Quel est ton pire souvenir chez le coiffeur ?",
  "As-tu déjà oublié l'anniversaire d'une personne très proche ?",
  "Quelle est la superstition la plus ridicule à laquelle tu crois ?",
  "Quel est ton talent le plus inutile en soirée ?",
  "As-tu déjà fait semblant de téléphoner pour éviter de parler à quelqu'un ?",
  "Quelle est ta pire expérience dans des toilettes publiques ?",
  "Quel est le truc le plus cliché que tu aimes faire ?",
  "As-tu déjà gâché la surprise d'une fête d'anniversaire ?",
  "Quelle est l'odeur bizarre que tu adores ?",
  "Quel est ton pire fail sportif ?",
  "As-tu déjà eu honte d'être avec l'un de tes amis en public ?",
  "Quelle est ta pire anecdote de covoiturage ?",
  "Si tu devais participer à une émission de télé-réalité, laquelle serait-ce ?",
  "As-tu déjà mangé quelque chose tombé par terre après la règle des 5 secondes ?",
  "Quel est ton mot de passe le plus ridicule (sans le donner en entier) ?",
  "Quelle est la chose la plus chère que tu aies cassée ?",
  "As-tu déjà accusé quelqu'un d'autre pour une de tes erreurs ?",
  "Quel est le pire métier que tu pourrais faire ?",
  "Quelle est ton astuce secrète de flemmard(e) au quotidien ?",
  "As-tu déjà ri au pire moment possible lors d'un événement sérieux ?",
  "Quel est le message le plus passif-agressif que tu aies écrit ?",
  "Quelle est la célébrité que tout le monde trouve belle sauf toi ?",
  "As-tu déjà menti sur tes goûts musicaux pour plaire à quelqu'un ?",
  "Quel est ton pire souvenir de rentrée scolaire ?",
  "Quelle est la chose la plus absurde que tu aies achetée en ligne la nuit ?",
  "As-tu déjà été viré(e) d'un bar ou d'une boîte de nuit ?",
  "Quel est le dernier rêve très étrange dont tu te souviens ?",
  "Quelle est ta pire expérience avec un voisin ?",
  "As-tu déjà prétendu aimer un cadeau alors que tu le détestais ?",
  "Quel est ton péché mignon en matière de junk food ?",
  "Quelle est la pire chanson que tu connaisses par cœur ?",
  "As-tu déjà fait semblant de dormir pour éviter une conversation ?",
  "Quelle est l'anecdote la plus embarrassante impliquant ton animal de compagnie ?",
  "Quel est ton plus grand regret de la semaine dernière ?",
  "As-tu déjà flirté pour obtenir un avantage gratuit (café, verre, etc.) ?",
  "Quelle est ta pire technique pour sécher les cours ?",
  "Quel est le dernier drama croustillant dans lequel tu as été impliqué(e) ?",
  "As-tu déjà caché une mauvaise note à tes parents pendant des semaines ?",
  "Quelle est la chose la plus ridicule qui t'ait fait pleurer ?",
  "Quel est ton pire souvenir de dentiste ou de médecin ?",
  "As-tu déjà envoyé un screen à la personne même que tu critiquais ?",
  "Quelle est l'application que tu ouvres en premier le matin ?",
  "Quel est le secret de beauté le plus étrange que tu utilises ?",
  "As-tu déjà menti sur ce que tu avais fait de ton week-end ?",
  "Quel est le pire plat que tu aies préparé pour quelqu'un d'autre ?",
  "Quelle est l'excuse la plus fréquente que tu utilises pour ne pas sortir ?",
  "As-tu déjà eu un crush sur un professeur ?",
  "Quelle est la chose la plus honteuse dans ta chambre en ce moment ?",
  "Quel est le dernier texto d'un(e) ex que tu as relu ?",
  "As-tu déjà volé quelque chose dans un supermarché ?",
  "Quelle est la dernière fois où tu as été vraiment jaloux(se) ?",
  "Quel est ton pire fail en tentant une trend TikTok ?",
  "As-tu déjà espionné une conversation de tes parents ?",
  "Quelle est la pire décision capillaire de ta vie ?",
  "Quel est le détail physique que tu regardes en premier chez quelqu'un ?",
  "As-tu déjà eu une amende pour une raison totalement stupide ?",
  "Quel est le dernier mensonge que tu as dit à ton/ta meilleur(e) ami(e) ?",
  "Quelle est ta réaction quand tu croises quelqu'un que tu ne veux pas voir ?",
  "As-tu déjà simulé un orgasme pour en finir plus vite ?",
  "Quelle est l'anecdote de soirée dont tes amis te parlent encore ?",
  "Quel est le film d'horreur qui t'a empêché(e) de dormir enfant ?",
  "As-tu déjà fait un faux compte pour espionner quelqu'un sur Insta ?",
  "Quelle est la chose la plus ridicule que tu aies crue étant petit(e) ?",
  "Quel est ton avis impopulaire sur une série à succès ?",
  "As-tu déjà porté les mêmes sous-vêtements deux jours de suite ?",
  "Quelle est la phrase d'accroche la plus éclatée qu'on t'ait sortie ?",
  "Quel est ton moment de solitude le plus grand de cette année ?",
  "As-tu déjà été surpris(e) en train de chanter à tue-tête dans ta voiture ?",
  "Quelle est ta phobie la plus bizarre liée à la nourriture ?",
  "Quel est le surnom affectueux que tu donnes à tes amis les plus proches ?",
  "As-tu déjà ressenti une attirance pour un personnage de dessin animé ?",
  "Quelle est la pire blague que tu aies faite et qui a mal tourné ?",
  "Quel est ton secret pour éviter de répondre à un message tout de suite ?",
  "As-tu déjà pleuré pour une rupture de célébrités ?",
  "Quelle est ton expression préférée qui est complètement ringarde ?",
  "Quel est ton pire souvenir d'auto-école ou d'examen de conduite ?",
  "As-tu déjà fait semblant de ne pas parler français à l'étranger ?",
  "Quelle est la chose la plus inutile que tu connaisses par cœur ?",
  "Quel est le dernier message reçu sur un groupe WhatsApp familial ?",
  "As-tu déjà utilisé le Wi-Fi du voisin sans lui dire ?",
  "Quelle est ta pire expérience dans une colocation ?",
  "Quel est l'emoji que tu utilises beaucoup trop ?",
  "As-tu déjà mangé l'étiquette d'un fruit par accident sans le recracher ?",
  "Quelle est la mode que tu détestes mais que tu as finie par porter ?",
  "Quel est ton dernier fail avec l'autocorrecteur de ton téléphone ?",
  "As-tu déjà menti à un médecin sur ta consommation d'alcool ?",
  "Quelle est ta tactique pour sortir d'un groupe de discussion sans vexer personne ?",
  "Quel est le moment le plus humiliant que tu aies vécu au supermarché ?",
  "As-tu déjà simulé une urgence pour fuir un date catastrophique ?",
  "Quelle est ta chanson de karaoké préférée où tu chantes faux ?",
  "Quel est le compliment le plus bizarre que tu aies reçu ?",
  "As-tu déjà fait semblant de connaître un groupe de musique pour avoir l'air cool ?",
  "Quelle est ton habitude la plus étrange avant d'aller dormir ?",
  "Quel est ton pire souvenir avec une application de rencontre ?",
  "As-tu déjà fouillé dans l'historique d'un ordinateur public ?",
  "Quelle est la rumeur la plus drôle que tu aies inventée sur quelqu'un ?",
  "Quel est le film que tu as vu le plus grand nombre de fois ?",
  "As-tu déjà ressenti de la jalousie envers un animal de compagnie ?",
  "Quelle est la chose la plus absurde que tu aies dite en dormant ?",
  "Quel est ton dernier acte de rébellion très mineur ?",
  "As-tu déjà menti sur tes compétences sur un CV de façon éhontée ?",
  "Quelle est la pire excuse que tu aies utilisée pour ne pas rendre un devoir ?",
  "Quel est l'endroit le plus bizarre où tu t'es endormi(e) ?",
  "As-tu déjà pleuré de rire à un moment totalement inapproprié ?",
  "Quelle est la chose la plus bizarre dans ton réfrigérateur actuellement ?",
  "Quel est ton pire souvenir de photo de classe ?",
  "As-tu déjà oublié ton propre âge ou ton code PIN ?",
  "Quelle est ta technique infaillible pour tricher sans te faire prendre ?",
  "Quel est le dernier objet que tu aies cassé de rage ?",
  "As-tu déjà été amoureux(se) de deux personnes en même temps ?",
  "Quelle est la phobie de ton partenaire/meilleur pote dont tu te moques secrètement ?",
  "Quel est ton souvenir de honte ultime en faisant du sport ?",
  "As-tu déjà fait semblant d'aimer la cuisine de tes beaux-parents ?",
  "Quelle est la chose la plus chère que tu aies volée à un hôtel ?",
  "Quel est ton pire fail en essayant de prendre un selfie discret ?",
  "As-tu déjà envoyé un message énervé puis réalisé que tu avais tort ?",
  "Quelle est l'anecdote la plus folle que tu aies vue dans le métro/bus ?",
  "Quel est ton record de jours passés sans sortir de chez toi ?",
  "As-tu déjà fouillé les tiroirs de tes parents étant petit(e) ?",
  "Quelle est la pire série française selon toi ?",
  "Quel est ton rituel secret quand tu as une mauvaise journée ?",
  "As-tu déjà inventé une excuse médicale pour une sortie ?",
  "Quelle est ta pire expérience avec un service client ?",
  "Quel est ton dernier achat impulsif lié à une passion éphémère ?",
  "As-tu déjà prétendu être un expert dans un domaine où tu es nul(le) ?",
  "Quelle est la chose la plus gênante que ton téléphone ait faite en public ?",
  "Quel est le dernier message lu mais ignoré volontairement dans ton téléphone ?",
  "As-tu déjà eu un fou rire à un enterrement ou une messe ?",
  "Quelle est l'habitude de tes amis que tu supportes le moins ?",
  "Quel est ton pire souvenir avec un insecte dans ta chambre ?",
  "As-tu déjà pleuré devant une publicité à la télé ?",
  "Quelle est ton astuce de pro pour paraître occupé(e) au travail/en cours ?",
  "Quel est le mensonge le plus drôle auquel tu as cru enfant ?",
  "As-tu déjà espionné l'écran du téléphone de la personne à côté de toi dans le bus ?",
  "Quelle est ta pire expérience avec un livreur UberEats ou Deliveroo ?",
  "Quel est ton plus grand moment de paranoïa irrationnelle ?",
  "As-tu déjà prétendu aimer un groupe de K-pop sans en connaître un seul ?",
  "Quelle est la dernière photo que tu as supprimée de ton téléphone et pourquoi ?",
  "Quel est le pire message d'ivresse que tu aies écrit ?",
  "As-tu déjà menti à un SDF pour ne pas lui donner d'argent ?",
  "Quelle est la chose la plus étrange que tu aies trouvée dans tes poches ?",
  "Quel est le dernier mensonge de tes parents que tu as découvert ?",
  "As-tu déjà simulé une crampe pour arrêter une activité physique ?",
  "Quelle est ta technique pour esquiver les distributeurs de flyers dans la rue ?",
  "Quel est ton pire fail en essayant d'être sexy ?",
  "As-tu déjà pleuré pour une mauvaise coupe de cheveux au salon ?",
  "Quelle est la pire excuse que tu aies sortie pour annuler un rdv galant ?",
  "Quel est l'endroit le plus bizarre où tu aies pris une photo de toi ?",
  "As-tu déjà prétendu avoir lu un livre classique pour faire intelligent(e) ?",
  "Quelle est ton anecdote de honte maximale dans une boutique de vêtements ?",
  "Quel est ton pire complexe quand tu vas à la plage ?",
  "As-tu déjà fouillé dans les médicaments de la salle de bain de quelqu'un ?",
  "Quelle est la pire chanson que tu aies mise pendant l'intimité ?",
  "Quel est le dernier objet que tu as cassé par maladresse ?",
  "As-tu déjà ri à une blague que tu n'avais pas du tout comprise ?",
  "Quelle est l'émission de télé-réalité que tu regardes secrètement ?",
  "Quel est ton pire fail avec un assistant vocal (Siri, Alexa) ?",
  "As-tu déjà envoyé un email professionnel avec une énorme faute ?",
  "Quelle est ton habitude la plus dégoûtante quand personne ne regarde ?"
];

const actions = [
  "Montre le dernier message envoyé à ta mère.",
  "Imite le rire de la personne à ta gauche pendant 10 secondes.",
  "Envoie un emoji 'aubergine' au 3ème contact de ton répertoire WhatsApp.",
  "Mets ta photo de profil Instagram ou WhatsApp à l'envers pendant 10 minutes.",
  "Laisse la personne à ta droite publier un tweet (ou thread) avec ton téléphone.",
  "Danse la Macarena sans aucune musique pendant 15 secondes.",
  "Parle avec un accent québécois jusqu'à ton prochain tour.",
  "Tente de faire un compliment romantique au mur le plus proche.",
  "Fais le tour du groupe en marchant comme un canard.",
  "Bois une gorgée d'eau sans utiliser tes mains.",
  "Mime ta scène de film préférée, les autres doivent la deviner.",
  "Reste figé(e) comme une statue pendant 30 secondes chrono.",
  "Chante le refrain de ta chanson préférée en remplaçant toutes les voyelles par 'o'.",
  "Appelle le 5ème contact de ton répertoire et raccroche immédiatement après qu'il décroche.",
  "Laisse la personne en face de toi dessiner sur ton bras avec un stylo.",
  "Fais 10 pompes ou 10 squats en criant 'Je suis le roi/la reine !'.",
  "Imite un influenceur qui fait un placement de produit pour une brosse à toilettes.",
  "Récite l'alphabet à l'envers aussi vite que possible.",
  "Fais un câlin de 5 secondes à la personne à ta gauche.",
  "Change ton statut WhatsApp pour 'À la recherche d'un sugar daddy/mommy'.",
  "Prends un selfie très laid et mets-le en story privée (ou close friends).",
  "Parle comme un robot pendant tes trois prochaines interventions.",
  "Touche ton nez avec ta langue, ou essaie pendant 15 secondes.",
  "Laisse le joueur de ton choix te recoiffer.",
  "Fais un discours politique de 30 secondes sur l'importance du fromage.",
  "Mets un glaçon dans ton t-shirt jusqu'à ce qu'il fonde.",
  "Envoie 'Je crois que j'ai fait une grosse bêtise' à un(e) ami(e) et montre la réponse.",
  "Chuchote tout ce que tu dis jusqu'à ton prochain tour.",
  "Donne ton téléphone déverrouillé au joueur à ta droite pendant 30 secondes.",
  "Mange un aliment de la table en gardant les yeux fermés et devine ce que c'est.",
  "Fais le poirier (ou essaie) contre le mur le plus proche.",
  "Invente un rap de 15 secondes sur la personne en face de toi.",
  "Masse les épaules de la personne à ta droite pendant 1 minute.",
  "Fais semblant d'être ivre jusqu'à ton prochain tour.",
  "Mime une bagarre au ralenti avec un adversaire invisible.",
  "Prends la voix la plus grave possible pour tes 3 prochaines phrases.",
  "Renifle les chaussettes (ou chaussures) de la personne à ta gauche.",
  "Mange un morceau de citron ou un aliment très acide sans faire de grimace.",
  "Invente une chorégraphie TikTok de 10 secondes et réalise-la devant tout le monde.",
  "Imite un professeur que tout le groupe connaît (ou ton patron).",
  "Fais un Tuto Beauté hilarant en utilisant des objets de la table.",
  "Lis tes 3 dernières recherches YouTube à voix haute.",
  "Fais comme si tu animais une émission de télé-achat pour vendre la table basse.",
  "Déclare ton amour inconditionnel à la plante verte ou à l'objet le plus proche.",
  "Twerk pendant 10 secondes (ou essaie au moins).",
  "Agis comme si tu avais perdu la mémoire pendant la prochaine minute.",
  "Fais un air guitar très passionné sur une chanson imaginaire.",
  "Mime un animal en pleine parade nuptiale.",
  "Chante une chanson Disney en imitant les voix des personnages.",
  "Fais une critique gastronomique de ta dernière boisson comme un grand chef.",
  "Imite un tyrannosaure pendant 30 secondes.",
  "Fais un tour de magie qui rate lamentablement.",
  "Laisse le groupe choisir un mot que tu n'auras plus le droit de prononcer ce soir.",
  "Fais une pose de mannequin de haute couture et maintiens-la 20 secondes.",
  "Laisse la personne de ton choix te mordre le doigt très légèrement.",
  "Invente une rumeur complètement absurde sur la personne en face de toi.",
  "Fais un discours d'excuse larmoyant pour avoir mangé la dernière part de pizza.",
  "Fais la météo de demain de manière extrêmement dramatique.",
  "Mime un astronaute qui marche sur la lune avec une gravité faible.",
  "Fais la voix d'un animateur radio des années 80 pour annoncer le prochain tour.",
  "Imite un oiseau qui essaie de séduire un humain.",
  "Raconte ton pire cauchemar d'enfance avec une voix de bébé.",
  "Mime une personne qui a très envie d'aller aux toilettes mais ne trouve pas la porte.",
  "Joue du piano invisible comme un virtuose en plein concert.",
  "Imite le cri de guerre d'un samouraï au moment d'attaquer.",
  "Fais un bruit de sirène d'alarme jusqu'à ce qu'un joueur te demande d'arrêter.",
  "Mime un chef cuisinier très stressé qui rate sa recette.",
  "Fais la danse de la victoire de Fortnite de ton choix.",
  "Écris 'Je suis fan de toi' en commentaire sur le dernier post Instagram de la 3ème personne de ton feed.",
  "Lèche ton coude (ou passe 10 secondes à essayer désespérément).",
  "Imite un présentateur de JT annonçant la fin du monde imminente.",
  "Fais semblant de jouer du violon sur un air très triste pendant 20 secondes.",
  "Dis 'Je t'aime' de 3 façons différentes avec 3 accents différents.",
  "Fais une roulade au sol (ou un salto imaginaire si pas d'espace).",
  "Laisse le joueur à ta droite te choisir un nouveau fond d'écran pour la soirée.",
  "Chante une chanson de rap en version berceuse.",
  "Mime une publicité pour un produit anti-chute de cheveux.",
  "Fais 5 squats en criant le nom de ton/ta crush actuel(le) ou historique.",
  "Laisse la personne à ta gauche te faire un suçon dans le cou... avec ses doigts (un faux).",
  "Prends l'objet le plus proche et essaie de le vendre au groupe pour 1 million d'euros.",
  "Agis comme un chat qui fait sa toilette pendant 30 secondes.",
  "Appelle la 2ème personne de tes contacts récents et demande-lui la recette des crêpes.",
  "Fais le bruit du modem des années 2000 qui se connecte à internet.",
  "Laisse un joueur te chatouiller pendant 10 secondes sans rire.",
  "Mime une personne qui essaie de marcher avec des talons de 15 cm pour la première fois.",
  "Fais semblant d'être possédé par un démon jusqu'à ce qu'on te 'désenvoûte'.",
  "Répète tout ce que dit le joueur à ta droite pendant 3 minutes.",
  "Fais un câlin à la personne qui a le plus de points.",
  "Mets tes chaussettes sur tes mains et garde-les pour 2 tours.",
  "Chante la Marseillaise avec la bouche fermée.",
  "Fais une imitation d'Emmanuel Macron (ou du président) qui annonce une bonne nouvelle.",
  "Tente de jongler avec 3 objets choisis par le groupe.",
  "Fais une danse du ventre sensuelle devant la personne en face de toi.",
  "Parle de toi à la troisième personne du singulier pour les 3 prochains tours.",
  "Imite un coq au lever du soleil très bruyamment.",
  "Essaie de faire pleurer le groupe avec une histoire fausse.",
  "Fais un bruit de pet avec tes aisselles.",
  "Laisse le joueur de ton choix t'attacher les poignets avec un lacet pendant 5 minutes.",
  "Lis tes 5 derniers messages reçus en prenant la voix de Dark Vador.",
  "Fais comme si tu étais un zombie cherchant des cerveaux pendant 1 minute.",
  "Mime un combat épique d'arts martiaux contre une mouche imaginaire.",
  "Fais 15 sauts en étoile en criant 'Hourra !' à chaque saut.",
  "Tente d'hypnotiser la personne à ta gauche avec tes mains et tes yeux.",
  "Mime une séance photo pour un magazine de mode ridicule.",
  "Fais un compliment à chaque joueur, mais termine par '...mais bon, c'est dommage pour le reste'.",
  "Chante a capella comme si tu étais à l'opéra.",
  "Laisse le groupe te renommer pour la soirée (tu devras répondre uniquement à ce nom).",
  "Imite une alarme de voiture qui s'emballe.",
  "Mime une personne coincée dans une boîte invisible de plus en plus petite.",
  "Fais semblant de perdre les eaux comme dans un film.",
  "Appelle un numéro au hasard (composé par tes amis) et souhaite une bonne année.",
  "Tente de toucher ton nez avec ta langue en fermant un seul œil.",
  "Mets ton pull ou ton t-shirt à l'envers et laisse-le ainsi jusqu'à la fin de la partie.",
  "Agis comme un commentateur sportif pour décrire les actions de la pièce.",
  "Mime un plongeon au ralenti comme dans Alerte à Malibu.",
  "Fais le poirier en appuyant tes pieds contre le mur.",
  "Essaie de gober un aliment jeté en l'air par le joueur en face de toi.",
  "Fais un rap d'au moins 4 rimes avec les prénoms des joueurs présents.",
  "Fais comme si tu découvrais le feu pour la première fois.",
  "Laisse la personne à ta gauche te maquiller les yeux (ou mime-le si pas de maquillage).",
  "Mime la personne la plus soûle de la soirée.",
  "Fais un discours passionnant sur l'utilité des lacets de chaussures.",
  "Imite un singe qui vient de trouver une banane géante.",
  "Parle avec un cheveu sur la langue jusqu'à ton prochain tour.",
  "Essaie de faire rire la personne en face de toi sans la toucher.",
  "Mime un joueur de tennis professionnel en plein match.",
  "Laisse le groupe t'inventer une punition si tu perds le prochain jeu.",
  "Fais une déclaration d'amour digne d'une telenovela au balai ou à la serpillière.",
  "Chante une chanson de Noël au milieu du salon.",
  "Fais le bruit d'une moto qui démarre et qui cale.",
  "Fais comme si ton doigt était une baguette magique et jette des sorts.",
  "Imite le rire de Gollum dans le Seigneur des Anneaux.",
  "Parle avec les dents serrées pendant 3 tours.",
  "Mime une personne qui marche sur des braises ardentes.",
  "Laisse le joueur à ta droite te choisir une nouvelle coupe de cheveux (avec les mains).",
  "Tente de faire du breakdance au sol.",
  "Fais une imitation d'un professeur d'yoga très spirituel.",
  "Imite un avion en plein décollage avec les bruits.",
  "Mime un cambrioleur qui se fait surprendre.",
  "Chante une berceuse en fixant la personne à ta droite.",
  "Agis comme si tu avais une puce géante dans le dos et essaie de t'en débarrasser.",
  "Fais un poème en alexandrins sur ton dernier repas.",
  "Imite un enfant de 4 ans qui fait un caprice au supermarché.",
  "Laisse le groupe choisir ta sonnerie de téléphone pour demain matin.",
  "Mime la personne de ton choix dans la pièce, on doit deviner.",
  "Enlève une de tes chaussettes avec tes dents.",
  "Fais une scène de jalousie au joueur de ton choix pour une raison absurde.",
  "Agis comme un robot dont la batterie est faible.",
  "Chante le générique d'un dessin animé culte.",
  "Fais une publicité pour un produit de beauté invisible.",
  "Laisse la personne à ta gauche te donner à manger à la cuillère.",
  "Mime un personnage de jeu vidéo en pleine action.",
  "Imite une sirène de police française.",
  "Parle sans bouger les lèvres comme un ventriloque.",
  "Essaie de deviner la marque des sous-vêtements de 3 personnes (si faux, bois 1 gorgée).",
  "Fais la roue (ou essaie) sans rien casser.",
  "Mime une personne qui vient de gagner au Loto.",
  "Imite une poule qui pond un œuf d'or.",
  "Chante une chanson de variété française en pleurant.",
  "Fais un concours de grimaces avec le joueur en face (le perdant boit).",
  "Laisse le groupe lire ton historique de recherche Google récent.",
  "Agis comme si tu étais dans un film muet en noir et blanc.",
  "Mime un western duel au soleil avec ton voisin.",
  "Fais une démonstration de magie avec un stylo.",
  "Fais 5 burpees en criant 'Je suis une machine !'.",
  "Imite un pigeon dans un parc public.",
  "Laisse la personne de ton choix te dessiner un tatouage au stylo sur le bras.",
  "Chante une chanson de rock avec une voix aiguë.",
  "Agis comme si tu étais le présentateur d'une émission de télé-achat.",
  "Mime un personnage de Star Wars.",
  "Fais semblant d'être une statue de musée.",
  "Imite un chien qui demande une friandise.",
  "Laisse la personne à ta droite prendre le contrôle de ton compte Insta pendant 1 minute.",
  "Mime la préparation d'un cocktail sophistiqué.",
  "Fais une imitation d'un animal marin de ton choix.",
  "Chante une chanson en anglais avec un très fort accent français.",
  "Agis comme si tu étais le roi ou la reine d'un pays inventé.",
  "Mime un super-héros qui découvre ses pouvoirs.",
  "Laisse le groupe te poser une question gênante supplémentaire.",
  "Imite un chat qui demande des caresses.",
  "Fais un discours pour sauver le monde d'une invasion extraterrestre.",
  "Mime un danseur de ballet maladroit.",
  "Chante une chanson de Britney Spears avec passion.",
  "Agis comme si tu étais un espion infiltré dans la soirée.",
  "Laisse la personne à ta gauche te raconter une blague sans rire.",
  "Mime un DJ en plein set dans un club.",
  "Fais semblant d'être un fantôme gentil.",
  "Imite un loup qui hurle à la lune.",
  "Chante le générique des Pokémon avec conviction.",
  "Agis comme si tu étais le leader d'une secte amicale.",
  "Laisse le groupe te choisir un nouveau style vestimentaire avec tes vêtements actuels.",
  "Mime un astronaute en train de réparer une fusée.",
  "Fais une imitation d'une personne célèbre de ton choix.",
  "Chante une chanson romantique au joueur de ton choix.",
  "Agis comme si tu étais un chef d'orchestre passionné.",
  "Mime un personnage de conte de fées.",
  "Laisse la personne à ta droite te choisir une nouvelle photo de profil.",
  "Imite un présentateur de jeu télévisé très enthousiaste.",
  "Fais semblant d'être une horloge coucou.",
  "Chante une chanson de comédie musicale avec chorégraphie.",
  "Agis comme si tu étais un détective privé.",
  "Mime un joueur de baseball qui frappe un home run.",
  "Laisse le groupe choisir ta prochaine action.",
  "Imite un perroquet qui répète tout.",
  "Fais un discours de motivation pour le joueur de ton choix.",
  "Mime un personnage de manga.",
  "Chante une chanson avec la bouche pleine (d'eau ou d'air).",
  "Agis comme si tu étais un vampire qui a peur du sang.",
  "Laisse la personne à ta gauche te faire un massage des épaules.",
  "Mime un pirate qui cherche un trésor.",
  "Fais une imitation d'un animateur de colonie de vacances.",
  "Chante une chanson d'amour à une chaussure."
];

const mediumTruths = [
  "Qui parmi les joueurs présents a les pires goûts amoureux selon toi ?",
  "As-tu déjà trompé quelqu'un (même virtuellement) ?",
  "Quelle est la chose la plus illégale que tu aies faite sans te faire prendre ?",
  "Qui ici pourrait survivre le moins longtemps dans une télé-réalité d'aventure ?",
  "Quel est ton pire souvenir sexuel ou romantique ?",
  "As-tu déjà embrassé quelqu'un que tu détestais pour rendre jaloux un ex ?",
  "Quelle est l'opinion la plus dure que tu aies eue sur un des joueurs ici ?",
  "As-tu déjà volé de l'argent dans le portefeuille de tes parents ?",
  "Quel est le plus gros mensonge que tu aies dit pour coucher avec quelqu'un ?",
  "Qui dans cette pièce a le plus de chances de finir en prison ?",
  "As-tu déjà envoyé un nude à la mauvaise personne ?",
  "Quelle est ton excuse préférée pour éviter de payer l'addition ?",
  "As-tu déjà eu des pensées impures sur le/la partenaire d'un de tes amis ?",
  "Quel est le pire défaut du joueur à ta droite ?",
  "As-tu déjà stalké un(e) ex avec un faux compte pendant plus d'une heure ?",
  "Quel est ton plus grand fantasme inavoué ?",
  "Parmi les joueurs, avec qui refuserais-tu catégoriquement de vivre en colocation ?",
  "As-tu déjà fait l'amour dans un lieu public très risqué ?",
  "Quelle est la rumeur la plus cruelle que tu aies lancée ou partagée ?",
  "As-tu déjà été attiré(e) par quelqu'un du même sexe (si hétéro) ou sexe opposé (si homo) ?",
  "Quelle est la chose la plus humiliante que tu aies faite pour de l'argent ?",
  "Quel joueur ici a le moins bon style vestimentaire selon toi ?",
  "As-tu déjà couché avec l'ex d'un(e) ami(e) en secret ?",
  "Quelle est la conversation WhatsApp la plus compromettante sur ton téléphone ?",
  "Si tu devais sauver un seul joueur de la pièce et sacrifier les autres, qui choisirais-tu ?",
  "As-tu déjà simulé des sentiments pour ne pas te retrouver seul(e) ?",
  "Quelle est la drogue ou substance la plus dure que tu aies testée (ou voulu tester) ?",
  "Qui est la personne la plus fausse que tu connaisses dans ton entourage large ?",
  "As-tu déjà lu les SMS de ton/ta partenaire en cachette ?",
  "Quel est le montant le plus élevé de ton découvert bancaire et pourquoi ?",
  "Si tu devais coucher avec un(e) collègue ou camarade de classe, ce serait qui ?",
  "Quelle est ton opinion la plus honnête et brutale sur la personne en face de toi ?",
  "As-tu déjà fait chanter quelqu'un avec une information secrète ?",
  "Quel est ton plus grand regret avec ton dernier ou ta dernière ex ?",
  "As-tu déjà eu une relation toxique que tu as cachée à tes amis ?",
  "Qui parmi les joueurs ferait le pire parent ?",
  "As-tu déjà profité de la vulnérabilité de quelqu'un (alcool, tristesse) pour l'embrasser ?",
  "Quelle est la pire crasse que tu aies faite à un(e) collègue de travail ?",
  "Quel est le moment le plus gênant où tes parents t'ont surpris(e) ?",
  "As-tu déjà eu une MST/IST ou très peur d'en avoir une ?",
  "Si tu pouvais effacer de ta vie une personne présente ici, qui serait-ce ?",
  "Quelle est ta pire histoire de 'friendzone' ?",
  "As-tu déjà gardé les cadeaux d'un(e) ex pour les revendre ?",
  "Qui ici a le plus de chances de finir ruiné(e) ?",
  "Quelle est ta pire expérience dans une boîte de nuit ?",
  "As-tu déjà été attiré(e) par le frère ou la sœur d'un de tes potes ?",
  "Quel est ton secret le plus sombre concernant ton historique internet ?",
  "Qui est le joueur le plus hypocrite de la soirée ?",
  "As-tu déjà rompu par message vocal ou texto de lâche ?",
  "Quelle est la note la plus basse que tu te donnerais physiquement sur 10 ?",
  "As-tu déjà vomi sur quelqu'un d'autre en soirée ?",
  "Qui ici serait capable de trahir un secret pour 1000 euros ?",
  "Quelle est ta pire technique de manipulation pour obtenir ce que tu veux ?",
  "As-tu déjà flirté avec le videur pour rentrer en boîte ?",
  "Quelle est ton opinion impopulaire sur l'un des amis du groupe ?",
  "As-tu déjà menti sur le nombre de tes partenaires sexuels ?",
  "Qui dans la pièce a le pire caractère quand il a bu ?",
  "As-tu déjà simulé une maladie grave pour attirer la compassion ?",
  "Quel est le pire endroit où tu aies eu envie d'aller aux toilettes sans pouvoir le faire ?",
  "As-tu déjà couché le premier soir en promettant de rappeler sans jamais le faire ?",
  "Qui parmi nous est le/la plus radin(e) selon toi ?",
  "Quelle est ton anecdote la plus honteuse impliquant des forces de l'ordre ?",
  "As-tu déjà eu des sentiments pour deux personnes en même temps sans choisir ?",
  "Quel est ton péché inavouable quand tu es célibataire depuis longtemps ?",
  "As-tu déjà dragué l'ex d'une connaissance juste par compétition ?",
  "Qui ici pourrait secrètement avoir une double vie ?",
  "Quelle est ta plus grande insécurité lors d'un rapport intime ?",
  "As-tu déjà pris une photo de quelqu'un à son insu ?",
  "Quelle est la pire chose que tu aies souhaitée à ton pire ennemi ?",
  "Qui est le joueur avec qui tu as le moins d'affinités réelles ?",
  "As-tu déjà organisé une soirée en excluant volontairement un(e) pote ?",
  "Quelle est ta plus grosse dépense liée uniquement à ton apparence ?",
  "As-tu déjà fait un plan à trois ou as-tu très envie d'en faire un ?",
  "Quel est le pire jugement hâtif que tu aies porté sur quelqu'un ici ?",
  "As-tu déjà fouillé le téléphone d'un membre de ta famille ?",
  "Quelle est ta pire pensée pendant que tu faisais l'amour ?",
  "Si on devait tous voter pour exclure quelqu'un du groupe, pour qui voterais-tu ?",
  "As-tu déjà ghosté quelqu'un après avoir couché avec ?",
  "Quelle est ton anecdote la plus pathétique après une rupture ?",
  "As-tu déjà fantasmé sur un personnage de dessin animé, et lequel ?",
  "Qui ici a l'ego le plus surdimensionné selon toi ?",
  "Quelle est la dernière fois que tu as été méchant(e) gratuitement avec un inconnu ?",
  "As-tu déjà ressenti un sentiment de supériorité face à tes potes ?",
  "Quel est ton mensonge le plus élaboré qui n'a jamais été découvert ?",
  "As-tu déjà été recalé(e) physiquement à l'entrée d'un lieu (pas pour l'âge) ?",
  "Qui parmi les joueurs a les anecdotes les moins intéressantes ?",
  "Quelle est la pire chose que tu aies faite sur une application de rencontre ?",
  "As-tu déjà continué de fréquenter quelqu'un juste pour son argent/situation ?",
  "Quelle est la partie de ton corps que tu détestes le plus ?",
  "Si on lisait ton journal intime (ou tes notes), quelle serait la pire découverte ?",
  "As-tu déjà envoyé un message hot sur un groupe familial par erreur ?",
  "Qui ici est le plus susceptible de mentir pour sauver sa peau ?",
  "Quelle est ta pire expérience de jalousie maladive ?",
  "As-tu déjà pleuré pour attirer l'attention lors d'une dispute ?",
  "Quelle est l'habitude sexuelle de ton/ta partenaire que tu trouves bizarre ?",
  "As-tu déjà jugé secrètement la façon d'éduquer des parents de tes amis ?",
  "Qui parmi nous est le moins fiable pour garder un secret ?",
  "Quelle est la pire insulte que tu aies prononcée dans le dos de quelqu'un ici ?",
  "As-tu déjà simulé un faux malaise en public ?",
  "Quelle est l'histoire la plus trash que tu aies entendue sur un de tes ex ?",
  "Qui ici a la pire hygiène de vie ?",
  "As-tu déjà été infidèle en pensées intenses (rêves récurrents, messages ambigus) ?",
  "Quelle est la chose que tu trouves attirante mais qui est très taboue ?",
  "As-tu déjà couché avec quelqu'un pour te venger ?",
  "Quel est ton pire souvenir d'alcoolisation excessive impliquant des dégâts matériels ?",
  "Qui dans ce groupe est le plus grand manipulateur/manipulatrice ?",
  "As-tu déjà utilisé le brossage de dents d'une autre personne en pleine conscience ?",
  "Quelle est la pire chose que tu aies découverte en fouillant les affaires de ton partenaire ?",
  "As-tu déjà eu honte de l'apparence de la personne avec qui tu sortais ?",
  "Quel joueur ici te ferait le plus douter de ton orientation sexuelle ?",
  "Quelle est ta pire technique pour rompre en douceur ?",
  "As-tu déjà entretenu une relation cachée pendant plus de six mois ?",
  "Qui est la personne de ton passé que tu regrettes le plus d'avoir blessée ?",
  "As-tu déjà éprouvé du soulagement lors d'un drame chez un de tes proches ?",
  "Quelle est ta pire obsession inavouable sur Instagram ?",
  "As-tu déjà embrassé quelqu'un qui avait une très mauvaise haleine sans oser le dire ?",
  "Qui ici pourrait facilement devenir un gourou de secte ?",
  "Quel est ton plus grand mensonge sur tes revenus ou ta réussite ?",
  "As-tu déjà triché lors d'un test médical ou de santé ?",
  "Quelle est l'application la plus honteuse de ton téléphone actuel ?",
  "As-tu déjà prétendu être en couple pour recaler quelqu'un lourdement ?",
  "Quel est le pire complexe que tes parents t'ont transmis ?",
  "Qui dans la pièce serait capable de ruiner son mariage pour une passade ?",
  "As-tu déjà couché dans le lit de tes parents ?",
  "Quelle est l'anecdote de ton enfance qui met tout le monde mal à l'aise ?",
  "As-tu déjà flirté avec le/la prof particulier de quelqu'un ?",
  "Quel est le joueur qui en fait toujours trop pour se faire remarquer ?",
  "Quelle est ta pire vengeance après une séparation difficile ?",
  "As-tu déjà envoyé le même message mignon à deux personnes différentes ?",
  "Qui ici est le plus susceptible de cacher une addiction ?",
  "Quel est ton dernier acte de pure méchanceté assumée ?",
  "As-tu déjà volé l'idée de quelqu'un au travail ou en cours ?",
  "Quelle est l'opinion politique ou sociale que tu n'oses pas avouer ?",
  "As-tu déjà pleuré de rage face à une petite critique ?",
  "Qui parmi nous est le plus désespéré(e) en amour selon toi ?",
  "Quelle est ta pire peur concernant ton futur amoureux ?",
  "As-tu déjà été attiré(e) par la voix d'une personne que tu n'avais jamais vue ?",
  "Quel est le pire cadeau que tu aies revendu sur Vinted/LeBonCoin ?",
  "As-tu déjà utilisé tes larmes comme une arme lors d'un contrôle routier ?",
  "Qui dans cette pièce a le rire le plus insupportable ?",
  "Quelle est l'injustice que tu as subie mais que tu as méritée au fond ?",
  "As-tu déjà espionné l'ordinateur portable de ton boss ?",
  "Quelle est la chose la plus égoïste que tu aies faite cette année ?",
  "As-tu déjà menti sur un test de grossesse ou de MST pour tester quelqu'un ?",
  "Quel joueur ici a les pires réactions sous le coup de l'émotion ?",
  "Quelle est la pire blague que tu aies faite sur le physique de quelqu'un ?",
  "As-tu déjà eu une relation purement virtuelle sans jamais rencontrer la personne ?",
  "Qui parmi nous a les histoires d'amour les plus ennuyeuses ?",
  "Quel est le détail que tu regardes chez les autres pour juger leur classe sociale ?",
  "As-tu déjà simulé une crise de larmes pour éviter une rupture ?",
  "Quelle est la chose la plus folle que tu aies dite pour te valoriser en date ?",
  "Qui ici pourrait te trahir dans un cadre professionnel ?",
  "As-tu déjà fouillé les messages effacés d'une corbeille de téléphone/ordi ?",
  "Quelle est ton anecdote de nudité publique la plus traumatisante ?",
  "As-tu déjà pris du plaisir à voir un(e) ennemi(e) échouer lamentablement ?",
  "Qui dans la pièce a le plus mauvais rapport à l'argent ?",
  "Quel est le pire conseil de couple que tu aies suivi aveuglément ?",
  "As-tu déjà menti à un(e) de tes meilleur(e)s ami(e)s sur sa nouvelle tenue ?",
  "Quelle est la célébrité qui, si elle te le demandait, te ferait tout quitter ?",
  "Qui ici est le plus susceptible de créer un scandale familial ?",
  "As-tu déjà eu un rapport intime en sachant pertinemment que l'autre était en couple ?",
  "Quel est ton plus grand secret lié à un complexe d'infériorité ?",
  "As-tu déjà inventé une rumeur de toute pièce par vengeance ?",
  "Qui parmi les joueurs serait le moins apte à survivre s'il perdait tout son argent ?",
  "Quelle est la pire chose que tu aies pensée en regardant la personne à ta gauche ?",
  "As-tu déjà couché avec quelqu'un uniquement par pitié ?",
  "Quel est le dernier message reçu d'un compte fake sur les réseaux ?",
  "Qui ici a le plus tendance à tirer la couverture à soi ?",
  "As-tu déjà rompu l'amitié de deux personnes par tes actions ?",
  "Quelle est l'anecdote de soirée que tes parents ne doivent JAMAIS apprendre ?",
  "As-tu déjà eu envie de frapper violemment quelqu'un du groupe ?",
  "Quel est le critère superficiel rédhibitoire pour toi en drague ?",
  "Qui parmi nous fait le plus d'efforts pour paraître cool ?",
  "As-tu déjà été soulagé(e) d'apprendre la rupture d'un couple d'amis ?",
  "Quel est ton pire souvenir lié à un examen médical intime ?",
  "As-tu déjà ressenti une attirance inavouable lors d'un événement tragique (enterrement, etc.) ?",
  "Qui ici a le plus de chance de finir seul(e) à 50 ans ?",
  "Quelle est la plus grosse somme d'argent que tu aies dilapidée en une soirée ?",
  "As-tu déjà piraté le compte d'un proche (Facebook, Insta, mail) ?",
  "Quel est ton pire fail en tentant d'envoyer un message vocal sexy ?",
  "Qui dans cette pièce te connaît le moins bien en réalité ?",
  "As-tu déjà profité de ton statut pour écraser quelqu'un hiérarchiquement inférieur ?",
  "Quelle est ta pire pensée récurrente qui te fait te sentir comme une mauvaise personne ?",
  "As-tu déjà utilisé les affaires intimes d'un colocataire ou membre de la famille ?",
  "Qui parmi nous pourrait ruiner l'ambiance de la soirée en une phrase ?",
  "Quel est ton mensonge le plus fréquent concernant ta vie sexuelle ?",
  "As-tu déjà simulé de t'entendre avec les parents de ton ex pour des avantages ?",
  "Quelle est ton opinion cachée sur le/la partenaire actuel(le) de ton/ta meilleur(e) ami(e) ?",
  "Qui ici a le rire le plus forcé lors des blagues des autres ?",
  "As-tu déjà pleuré devant le miroir en testant une tenue ?",
  "Quelle est ta plus grande déception amoureuse qui te hante encore ?",
  "As-tu déjà envoyé un message groupé à plusieurs crushs en même temps ?",
  "Quel joueur ici a les opinions politiques les plus étranges selon toi ?",
  "Quelle est la pire décision que tu aies prise sous l'effet de la colère pure ?",
  "As-tu déjà été attiré(e) par la mère/le père d'un(e) de tes potes ?",
  "Qui est le/la plus immature émotionnellement dans cette pièce ?"
];

const mediumActions = [
  "Envoie un message vocal de 10 secondes de gémissements (légers) à la 3ème personne de ton répertoire.",
  "Masse les pieds du joueur à ta gauche pendant une minute entière.",
  "Laisse un joueur envoyer un SMS de son choix à ton/ta boss ou professeur (soft mais gênant).",
  "Montre ta liste de conversations Instagram cachées ou archivées.",
  "Bois cul sec un shot préparé par le groupe (sans alcool fort, mais un mix douteux).",
  "Fais un lap-dance (habillé) au joueur de ton choix pendant 30 secondes.",
  "Ouvre Tinder/Bumble et swipe à droite les 10 prochains profils avec un Super Like pour le premier.",
  "Montre à tout le monde la dernière photo supprimée dans ta corbeille.",
  "Lis à voix haute le dernier SMS reçu de ton ex (ou de ta dernière conquête).",
  "Suce le doigt (propre) du joueur en face de toi pendant 3 secondes.",
  "Laisse la personne à ta droite te bander les yeux et te faire goûter un mystère de la cuisine.",
  "Fais une déclaration enflammée de 30 secondes au joueur que tu trouves le moins attirant.",
  "Poste une story Insta de toi avec le doigt dans le nez et laisse-la au moins 10 minutes.",
  "Fais le tour de la pièce à quatre pattes en aboyant agressivement sur les joueurs.",
  "Laisse le groupe publier un commentaire provocant sur la dernière publication Instagram de ton ex.",
  "Mords délicatement l'oreille du joueur à ta gauche.",
  "Retire une pièce de tes vêtements (pas les sous-vêtements) sans utiliser tes mains.",
  "Imite la scène orgasmique de Meg Ryan dans le film 'Quand Harry rencontre Sally'.",
  "Laisse un joueur consulter ton historique de navigation privée pendant 20 secondes.",
  "Fais une chorégraphie sexy de 30 secondes sur le mur.",
  "Envoie 'On doit parler d'urgence' à tes parents et ne réponds pas pendant 5 minutes.",
  "Mime une position du Kama Sutra et demande au groupe de la deviner.",
  "Fais 5 pompes avec un joueur assis sur ton dos (ou essaie).",
  "Embrasse le cou de la personne à ta droite de manière langoureuse.",
  "Montre le dernier compte bloqué sur tes réseaux et explique pourquoi.",
  "Prends un selfie très près du visage de la personne en face et mets-le en fond d'écran.",
  "Appelle la dernière personne que tu as ajoutée sur ton téléphone et chante-lui une berceuse.",
  "Laisse la personne à ta gauche te fouiller les poches et le portefeuille.",
  "Fais semblant d'embrasser passionnément le coussin le plus proche pendant 15 secondes.",
  "Envoie un emoji 'Pêche' et un point d'interrogation à un collègue de travail/fac.",
  "Mime la dernière dispute de couple que tu as eue, en jouant les deux rôles.",
  "Garde la main sur la cuisse du joueur à ta droite pendant les 3 prochains tours.",
  "Échange ton t-shirt avec la personne en face de toi.",
  "Chante le refrain de 'Je t'aime' de Lara Fabian en regardant quelqu'un droit dans les yeux.",
  "Fais un suçon (faux, avec la bouche bien serrée) sur le bras de ton voisin.",
  "Laisse le groupe lire à voix haute tes notes d'application 'Notes'.",
  "Renifle le cou du joueur de ton choix et fais un commentaire détaillé sur son odeur.",
  "Fais la roue (ou une roulade) tout en criant une insulte.",
  "Twerk contre le dos d'un joueur pendant 15 secondes.",
  "Envoie un message à ton ex disant 'J'ai rêvé de toi cette nuit'.",
  "Laisse un joueur te chatouiller violemment pendant 20 secondes, interdiction de bouger.",
  "Raconte ta dernière expérience intime en utilisant uniquement des métaphores sportives.",
  "Montre la conversation WhatsApp la plus récente avec ton père/ta mère.",
  "Bois le fond du verre du joueur à ta gauche.",
  "Sursaute et crie à pleins poumons de manière inattendue.",
  "Fais un massage du crâne très appuyé à la personne en face de toi.",
  "Lèche la joue de la personne à ta droite.",
  "Imite le joueur à ta gauche lors de sa dernière cuite.",
  "Envoie 'Je crois que tu me plais' à un ami platonique de longue date.",
  "Fais 15 abdominaux tout en déclarant tes péchés mignons.",
  "Mime une séance d'épilation douloureuse à la cire.",
  "Donne ton téléphone au groupe, ils ont 1 minute pour écrire un SMS à qui ils veulent (pas le droit d'envoyer).",
  "Appelle une pizzeria et commande un kebab avec beaucoup de conviction.",
  "Fais un French Kiss au dos de ta main avec des bruits de bouche intenses.",
  "Agis comme si tu étais un acteur porno des années 80 qui fait son entrée.",
  "Laisse la personne à ta gauche écrire un mot au marqueur/stylo sur ton front.",
  "Chuchote une insulte très vulgaire à l'oreille de chaque joueur, d'une voix suave.",
  "Fais semblant de pleurer à chaudes larmes pendant 45 secondes.",
  "Montre au groupe le DM Instagram le plus étrange que tu aies reçu ou envoyé.",
  "Passe la main dans les cheveux de chaque joueur de manière creepy.",
  "Bois une gorgée d'alcool (ou d'eau) en croisant les bras avec le joueur en face (façon mariage).",
  "Retire les chaussettes du joueur à ta droite uniquement avec tes pieds.",
  "Simule une crise de panique très réaliste.",
  "Lis ton dernier tweet ou post Facebook comme un prêtre fait la messe.",
  "Laisse un joueur te nourrir à l'aveugle avec un aliment de son choix.",
  "Danse un slow très collé avec un balai ou un objet de la pièce.",
  "Envoie un message à ton groupe familial avec une blague très limite.",
  "Renifle sous les aisselles de la personne à ta gauche.",
  "Fais une déclaration d'amour de 1 minute chrono sans jamais ciller des yeux.",
  "Mange une cuillère de sauce piquante ou moutarde forte sans boire pendant 1 minute.",
  "Laisse le groupe te faire une 'beauté' express avec du rouge à lèvres.",
  "Singe la démarche de la personne que tu aimes le moins dans ton entourage.",
  "Reste assis(e) sur les genoux du joueur en face jusqu'à ton prochain tour.",
  "Appelle le service client de ton opérateur téléphonique et chante une chanson.",
  "Montre la pire photo de toi enregistrée sur le téléphone d'un de tes potes présents.",
  "Fais une grimace horrible et laisse-la comme photo de profil de ton réseau principal pendant 15 minutes.",
  "Fais semblant d'accoucher au milieu de la pièce.",
  "Masse le dos de la personne à ta droite tout en lui racontant une histoire d'horreur.",
  "Laisse le groupe fouiller la galerie photos de ton téléphone avec le mot-clé 'Amour'.",
  "Imite une strip-teaseuse débutante et maladroite.",
  "Bois une gorgée d'eau directement dans la bouche du joueur à ta gauche (sans avaler de travers).",
  "Chante une chanson paillarde à plein volume.",
  "Fais une critique très sévère et snob de la tenue d'un autre joueur.",
  "Appelle un ami et demande-lui s'il peut te prêter 500 euros pour une urgence.",
  "Lèche tes propres orteils (ou fais semblant très très près).",
  "Laisse la personne de ton choix te pincer doucement le nez pendant 3 minutes.",
  "Fais un bruit d'animal en chaleur pendant 10 secondes.",
  "Poste un statut 'Je me sens tellement seul(e)' sur le réseau de ton choix.",
  "Imite la personne la plus insupportable que tu croises au travail/cours.",
  "Tiens la main du joueur à ta gauche pendant les 2 prochains tours de jeu.",
  "Fais semblant de lécher une glace de manière très suggestive.",
  "Montre l'application la plus embarrassante téléchargée sur ton téléphone.",
  "Laisse le groupe envoyer un message avec un cœur noir 🖤 à ton boss/professeur.",
  "Imite un présentateur de journal télévisé qui annonce qu'il n'a pas de pantalon.",
  "Mords l'épaule du joueur de ton choix (sans faire mal).",
  "Fais une demande de mariage extravagante au joueur à ta droite avec une bague imaginaire.",
  "Bois un verre d'eau pendant qu'un joueur te chatouille le ventre.",
  "Mime une séance de spiritisme pour invoquer l'esprit d'une célébrité.",
  "Envoie un selfie de toi en train de loucher à ton/ta crush actuel(le) ou ex.",
  "Parle avec la langue bloquée sous tes dents du haut pour les 3 prochains tours.",
  "Laisse le joueur en face de toi te faire renifler 3 objets à l'aveugle.",
  "Masse les mollets de la personne à ta droite pendant 30 secondes.",
  "Fais une scène de théâtre shakespearienne tragique sur la mort d'une mouche.",
  "Appelle un membre de ta famille et annonce que tu as adopté un lama.",
  "Mime un combat de boxe au ralenti avec une fin dramatique.",
  "Laisse la personne à ta gauche te faire un massage facial vigorously.",
  "Fais comme si tu recevais un Oscar et remercie tes amants cachés.",
  "Chante une berceuse de façon menaçante à la personne en face de toi.",
  "Montre au groupe la recherche la plus bizarre de ton navigateur actuel.",
  "Imite la démarche d'un zombie dans un supermarché.",
  "Fais semblant d'être possédé(e) par l'esprit de Michael Jackson pendant 20 sec.",
  "Laisse un joueur te poser une question hyper indiscrète, tu dois y répondre par 'oui' ou 'non'.",
  "Mime un plongeon de haut vol qui se termine en plat.",
  "Envoie 'Je suis désolé(e) pour hier soir' au dernier numéro inconnu de ton journal d'appels.",
  "Fais la roue (ou essaie de faire l'équilibre) pendant que quelqu'un filme.",
  "Masse la nuque de la personne de ton choix en faisant des bruits relaxants bizarres.",
  "Agis comme si tu étais un robot défectueux dont l'alarme se déclenche.",
  "Laisse le groupe créer un groupe WhatsApp avec un nom absurde et y ajouter 3 de tes contacts.",
  "Imite le cri d'une chèvre en colère pendant 15 secondes.",
  "Fais semblant d'être un influenceur(se) fitness donnant un cours catastrophique.",
  "Montre les 3 premières photos de ta pellicule en tapant 'Soirée'.",
  "Appelle un salon de coiffure et demande s'ils font des coupes pour caniche.",
  "Mime une personne qui marche pieds nus sur du Lego.",
  "Lèche la cuillère (ou l'ustensile) d'un autre joueur.",
  "Fais une critique de cinéma d'un film pour enfants mais avec un ton très sérieux.",
  "Laisse le joueur à ta gauche te faire des couettes ou une coiffure ridicule.",
  "Imite une alarme incendie jusqu'à ce que quelqu'un crie 'Au feu !'.",
  "Fais un discours enflammé de 45 secondes sur l'injustice des chaussettes orphelines.",
  "Mime un DJ sous substances au milieu d'un grand festival.",
  "Envoie une vidéo de toi en train de faire un clin d'œil appuyé à ton dernier crush.",
  "Touche le nez de chaque joueur avec ton doigt et dis 'Boop' de façon creepy.",
  "Fais semblant de jouer de la batterie intensément pendant 30 secondes.",
  "Agis comme si la personne à ta droite était ton idole absolue et demande un autographe sur ton front.",
  "Laisse le groupe choisir ta sonnerie de réveil et mets le volume au max.",
  "Fais une scène de jalousie toxique au joueur de ton choix parce qu'il a regardé ailleurs.",
  "Mime une publicité pour un parfum avec une sensualité très malaisante.",
  "Chante 'Let it Go' (Libérée, Délivrée) en version death metal.",
  "Laisse la personne en face te pincer fortement les deux joues.",
  "Appelle un restaurant pour réserver une table pour deux en précisant que c'est pour rompre.",
  "Fais un strip-tease lent sur tes chaussettes uniquement.",
  "Imite un pingouin qui a trop chaud.",
  "Mime une attaque de panique dans un ascenseur invisible.",
  "Fais le tour du groupe en faisant le bisou esquimau à tout le monde.",
  "Laisse le joueur à ta gauche écrire son pseudo Insta sur ton bras au feutre.",
  "Agis comme si tu avais avalé une mouche et essaie de la recracher.",
  "Fais 20 sauts à cloche-pied en récitant une poésie classique.",
  "Montre le dernier TikTok ou Reel enregistré dans tes favoris.",
  "Imite la voix du traducteur Google pendant tes 4 prochaines phrases.",
  "Mime une personne très soûle essayant de déverrouiller sa porte d'entrée.",
  "Fais un monologue de 30 secondes sur ton amour pour les légumes bouillis.",
  "Laisse la personne de ton choix te faire un suçon dans le cou (un vrai, soft).",
  "Appelle tes grands-parents (ou parents) pour leur demander comment on fait des bébés.",
  "Mime un personnage de jeu de combat qui perd misérablement.",
  "Fais une déclaration dramatique comme si tu allais mourir dans 5 minutes.",
  "Imite un chat de gouttière très agressif.",
  "Fais semblant de jouer de la trompette de manière très passionnée.",
  "Laisse le groupe choisir un objet que tu dois balancer par la fenêtre (ou dehors).",
  "Mime une séance de méditation qui tourne mal.",
  "Envoie un message vocal de toi en train de chanter la Marseillaise à un contact pro.",
  "Fais 5 burpees tout en avouant tes plus grands secrets à chaque saut.",
  "Imite un politicien qui esquive une question difficile pendant 1 minute.",
  "Fais le lézard sur le sol du salon pendant 15 secondes.",
  "Montre la pire photo de ton/ta partenaire (ou ex) que tu as gardée.",
  "Appelle un fast-food et demande s'ils vendent des salades vegan sans salade.",
  "Mime un cambriolage où tu te fais griller par la police.",
  "Fais une critique virulente de la décoration de la pièce.",
  "Laisse la personne à ta droite te maquiller le visage avec ses doigts.",
  "Agis comme si tu recevais un choc électrique à chaque fois qu'on prononce ton prénom.",
  "Chante une chanson romantique en regardant intensément le plafond.",
  "Fais semblant d'être un extraterrestre qui découvre la gravité terrestre.",
  "Mime un surfeur qui se fait attaquer par un requin imaginaire.",
  "Laisse le joueur en face de toi te mordre gentiment le menton.",
  "Envoie 'Je crois que j'ai fait une connerie' à ton meilleur ami et ignore sa réponse.",
  "Fais une scène de rupture avec une bouteille d'eau.",
  "Imite la façon de manger du joueur de ton choix.",
  "Agis comme si tu avais perdu ton téléphone et cherche-le en panique.",
  "Fais un discours pour défendre les droits des nains de jardin.",
  "Mime une personne qui passe à la télé pour la première fois.",
  "Laisse le groupe écrire une note dans ton téléphone intitulée 'Mes pensées sombres'.",
  "Fais comme si tu conduisais une voiture de course en plein milieu du salon.",
  "Appelle un cinéma et demande s'ils passent le film 'La Reine des Neiges 3'.",
  "Mime un ninja qui s'infiltre dans la soirée.",
  "Fais une imitation d'un chien qui se gratte les puces.",
  "Laisse la personne à ta gauche te faire un câlin par derrière pendant 1 minute.",
  "Agis comme si tu avais gagné au loto et distribue de l'argent imaginaire.",
  "Chante le refrain d'une chanson paillarde très fort.",
  "Fais une séance de spiritisme pour invoquer l'esprit d'une pizza.",
  "Mime un personnage de dessin animé célèbre, les autres doivent deviner.",
  "Laisse le joueur à ta droite fouiller tes poches sans rien dire.",
  "Fais un discours enflammé sur ton amour pour les lundis matins.",
  "Imite une alarme de voiture avec la bouche ouverte.",
  "Agis comme si tu étais un espion infiltré et cache-toi derrière un meuble.",
  "Fais semblant d'être une statue de musée très célèbre.",
  "Mime un duel de cowboys avec la personne en face de toi.",
  "Laisse le groupe choisir une punition supplémentaire si tu rigoles dans la minute.",
  "Fais une imitation d'un professeur d'école primaire très stricte.",
  "Chante une chanson de rock en faisant du playback agressif.",
  "Agis comme si tu avais une puce géante dans le dos.",
  "Mime un présentateur météo annonçant un ouragan de paillettes.",
  "Fais un poème en alexandrins sur la beauté d'un balai-brosse."
];

export const TOD_QUESTIONS: TODQuestion[] = [
  ...truths.slice(0, 200).map((text, i) => ({
    id: `soft-v-${i + 1}`,
    type: 'truth' as const,
    level: 'soft' as const,
    text
  })),
  ...actions.slice(0, 200).map((text, i) => ({
    id: `soft-a-${i + 1}`,
    type: 'action' as const,
    level: 'soft' as const,
    text
  })),
  ...mediumTruths.slice(0, 200).map((text, i) => ({
    id: `medium-v-${i + 1}`,
    type: 'truth' as const,
    level: 'medium' as const,
    text
  })),
  ...mediumActions.slice(0, 200).map((text, i) => ({
    id: `medium-a-${i + 1}`,
    type: 'action' as const,
    level: 'medium' as const,
    text
  })),
  // À SUIVRE : VAGUE 3 (HARD)
];
