export interface TODQuestion {
  id: string;
  type: 'truth' | 'action';
  level: 'soft' | 'medium' | 'hard';
  text: string;
}

export const TOD_QUESTIONS: TODQuestion[] = [
  { id: 'soft-v-1', type: 'truth', level: 'soft', text: "Quel est ton pire tue-l'amour ?" },
  { id: 'soft-v-2', type: 'truth', level: 'soft', text: "Quelle est ta phobie la plus ridicule ?" },
  { id: 'soft-v-3', type: 'truth', level: 'soft', text: "Raconte la chose la plus gênante que tu aies faite au collège." },
  { id: 'soft-v-4', type: 'truth', level: 'soft', text: "Quel est le dernier mensonge que tu as dit ?" },
  { id: 'soft-v-5', type: 'truth', level: 'soft', text: "Quel est ton talent le plus inutile ?" },
  { id: 'soft-v-6', type: 'truth', level: 'soft', text: "Quelle est la pire excuse que tu aies donnée pour annuler une sortie ?" },
  { id: 'soft-v-7', type: 'truth', level: 'soft', text: "As-tu déjà eu un crush sur le/la partenaire d'un de tes potes ?" },
  { id: 'soft-v-8', type: 'truth', level: 'soft', text: "Quel est ton plaisir coupable musical ?" },
  { id: 'soft-v-9', type: 'truth', level: 'soft', text: "Quelle est la dernière chose que tu as cherchée sur Google ?" },
  { id: 'soft-v-10', type: 'truth', level: 'soft', text: "Quel est le pire cadeau que tu aies jamais reçu ?" },
  { id: 'soft-v-11', type: 'truth', level: 'soft', text: "As-tu déjà stalké le profil de l'ex de ton ex ?" },
  { id: 'soft-v-12', type: 'truth', level: 'soft', text: "Quel est ton pire fashion faux-pas ?" },
  { id: 'soft-v-13', type: 'truth', level: 'soft', text: "As-tu déjà pleuré devant un dessin animé ? Lequel ?" },
  { id: 'soft-v-14', type: 'truth', level: 'soft', text: "Quelle est la pire chose que tu aies dite en pensant avoir raccroché ?" },
  { id: 'soft-v-15', type: 'truth', level: 'soft', text: "Quel est le surnom le plus honteux qu'on t'ait jamais donné ?" },
  { id: 'soft-v-16', type: 'truth', level: 'soft', text: "Quelle est la chose la plus bizarre que tu fasses quand tu es seul(e) ?" },
  { id: 'soft-v-17', type: 'truth', level: 'soft', text: "As-tu déjà fait semblant de connaître quelqu'un dans la rue pour éviter quelqu'un d'autre ?" },
  { id: 'soft-v-18', type: 'truth', level: 'soft', text: "Quel est ton pire fail en cuisinant ?" },
  { id: 'soft-v-19', type: 'truth', level: 'soft', text: "Quel est le pire message que tu aies envoyé à la mauvaise personne ?" },
  { id: 'soft-v-20', type: 'truth', level: 'soft', text: "Si tu devais effacer une application de ton téléphone, ce serait laquelle ?" },
  { id: 'soft-v-21', type: 'truth', level: 'soft', text: "Quelle est la chose la plus chère que tu aies cassée sans le dire ?" },
  { id: 'soft-v-22', type: 'truth', level: 'soft', text: "As-tu déjà fouillé dans le téléphone de quelqu'un ?" },
  { id: 'soft-v-23', type: 'truth', level: 'soft', text: "Quel est ton film préféré que tu n'assumes pas du tout ?" },
  { id: 'soft-v-24', type: 'truth', level: 'soft', text: "Quel est ton pire souvenir de vacances ?" },
  { id: 'soft-v-25', type: 'truth', level: 'soft', text: "As-tu déjà triché à un examen important ?" },
  { id: 'soft-v-26', type: 'truth', level: 'soft', text: "Quelle est la superstition à laquelle tu crois secrètement ?" },
  { id: 'soft-v-27', type: 'truth', level: 'soft', text: "Quel est ton pire date Tinder ou équivalent ?" },
  { id: 'soft-v-28', type: 'truth', level: 'soft', text: "As-tu déjà menti sur ton âge ?" },
  { id: 'soft-v-29', type: 'truth', level: 'soft', text: "Quelle est la phobie que tu as depuis l'enfance ?" },
  { id: 'soft-v-30', type: 'truth', level: 'soft', text: "Quel est le pire conseil qu'on t'ait jamais donné ?" },
  { id: 'soft-v-31', type: 'truth', level: 'soft', text: "Si tu étais un personnage de télé-réalité, quel serait ton rôle ?" },
  { id: 'soft-v-32', type: 'truth', level: 'soft', text: "Quelle est la chose la plus stupide que tu aies faite pour impressionner un crush ?" },
  { id: 'soft-v-33', type: 'truth', level: 'soft', text: "As-tu déjà eu peur du noir récemment ?" },
  { id: 'soft-v-34', type: 'truth', level: 'soft', text: "Quelle est ta pire anecdote de transport en commun ?" },
  { id: 'soft-v-35', type: 'truth', level: 'soft', text: "Quel est ton péché mignon niveau junk food ?" },
  { id: 'soft-v-36', type: 'truth', level: 'soft', text: "Quelle est la chanson que tu chantes toujours sous la douche ?" },
  { id: 'soft-v-37', type: 'truth', level: 'soft', text: "As-tu déjà prétendu être malade pour rester chez toi ?" },
  { id: 'soft-v-38', type: 'truth', level: 'soft', text: "Quel est ton pire souvenir d'anniversaire ?" },
  { id: 'soft-v-39', type: 'truth', level: 'soft', text: "Quelle est la chose la plus enfantine que tu possèdes encore ?" },
  { id: 'soft-v-40', type: 'truth', level: 'soft', text: "As-tu déjà vomi dans un lieu public ?" },
  { id: 'soft-v-41', type: 'truth', level: 'soft', text: "Quel est le pire achat que tu aies jamais fait ?" },
  { id: 'soft-v-42', type: 'truth', level: 'soft', text: "Quelle est ton habitude la plus agaçante ?" },
  { id: 'soft-v-43', type: 'truth', level: 'soft', text: "As-tu déjà eu un crush sur un prof ?" },
  { id: 'soft-v-44', type: 'truth', level: 'soft', text: "Quel est le message le plus gênant dans tes DM actuels ?" },
  { id: 'soft-v-45', type: 'truth', level: 'soft', text: "Si tu devais échanger ta vie avec quelqu'un ici, ce serait qui ?" },
  { id: 'soft-v-46', type: 'truth', level: 'soft', text: "Quelle est ta plus grande honte en cours de sport ?" },
  { id: 'soft-v-47', type: 'truth', level: 'soft', text: "As-tu déjà pleuré pour obtenir ce que tu voulais ?" },
  { id: 'soft-v-48', type: 'truth', level: 'soft', text: "Quel est ton pire souvenir chez le coiffeur ?" },
  { id: 'soft-v-49', type: 'truth', level: 'soft', text: "Quelle est la chose la plus étrange que tu aies mangée ?" },
  { id: 'soft-v-50', type: 'truth', level: 'soft', text: "As-tu déjà oublié le prénom de la personne avec qui tu étais ?" },
  { id: 'soft-v-51', type: 'truth', level: 'soft', text: "Quel est ton complexe le plus ridicule ?" },
  { id: 'soft-v-52', type: 'truth', level: 'soft', text: "Quelle est ta pire expérience dans des toilettes publiques ?" },
  { id: 'soft-v-53', type: 'truth', level: 'soft', text: "Si tu pouvais effacer une heure de ton passé, ça serait laquelle ?" },
  { id: 'soft-v-54', type: 'truth', level: 'soft', text: "As-tu déjà menti à tes parents sur l'endroit où tu dormais ?" },
  { id: 'soft-v-55', type: 'truth', level: 'soft', text: "Quelle est la pire rumeur que tu aies fait courir (ou entendu sur toi) ?" },
  { id: 'soft-v-56', type: 'truth', level: 'soft', text: "Quel est le rêve le plus étrange que tu aies fait ?" },
  { id: 'soft-v-57', type: 'truth', level: 'soft', text: "Quelle est ta pire photo sur les réseaux sociaux ?" },
  { id: 'soft-v-58', type: 'truth', level: 'soft', text: "As-tu déjà laissé quelqu'un d'autre se faire accuser à ta place ?" },
  { id: 'soft-v-59', type: 'truth', level: 'soft', text: "Quel est ton mot de passe le plus ridicule (sans le dire en entier) ?" },
  { id: 'soft-v-60', type: 'truth', level: 'soft', text: "Quelle est la série honteuse que tu as binge-watchée ?" },
  { id: 'soft-v-61', type: 'truth', level: 'soft', text: "As-tu déjà simulé un orgasme (ou un fou rire) pour faire plaisir ?" },
  { id: 'soft-v-62', type: 'truth', level: 'soft', text: "Quel est ton pire souvenir d'auto-école ?" },
  { id: 'soft-v-63', type: 'truth', level: 'soft', text: "Quelle est la remarque la plus blessante que tu aies dite par erreur ?" },
  { id: 'soft-v-64', type: 'truth', level: 'soft', text: "As-tu déjà espionné tes voisins ?" },
  { id: 'soft-v-65', type: 'truth', level: 'soft', text: "Quel est le surnom affectueux que tu donnes à ton animal ?" },
  { id: 'soft-v-66', type: 'truth', level: 'soft', text: "Si tu devais participer à une émission de TV, laquelle serait-ce ?" },
  { id: 'soft-v-67', type: 'truth', level: 'soft', text: "Quelle est ton anecdote de cuite la plus soft ?" },
  { id: 'soft-v-68', type: 'truth', level: 'soft', text: "As-tu déjà volé quelque chose dans un magasin (même un bonbon) ?" },
  { id: 'soft-v-69', type: 'truth', level: 'soft', text: "Quel est le dernier truc que tu as acheté sous l'influence des réseaux ?" },
  { id: 'soft-v-70', type: 'truth', level: 'soft', text: "Quelle est la mode vestimentaire que tu regrettes d'avoir suivie ?" },
  { id: 'soft-v-71', type: 'truth', level: 'soft', text: "As-tu déjà eu un fou rire au pire moment possible ?" },
  { id: 'soft-v-72', type: 'truth', level: 'soft', text: "Quel est le message le plus passif-agressif que tu aies envoyé ?" },
  { id: 'soft-v-73', type: 'truth', level: 'soft', text: "Quelle est ton astuce de flemmard numéro 1 ?" },
  { id: 'soft-v-74', type: 'truth', level: 'soft', text: "As-tu déjà créé un faux compte sur les réseaux sociaux ?" },
  { id: 'soft-v-75', type: 'truth', level: 'soft', text: "Quel est le pire cadeau que tu aies offert ?" },
  { id: 'soft-v-76', type: 'truth', level: 'soft', text: "Quelle est l'odeur bizarre que tu aimes bien ?" },
  { id: 'soft-v-77', type: 'truth', level: 'soft', text: "As-tu déjà été surpris(e) en train de parler tout seul(e) ?" },
  { id: 'soft-v-78', type: 'truth', level: 'soft', text: "Quel est ton pire fail en sport ?" },
  { id: 'soft-v-79', type: 'truth', level: 'soft', text: "Quelle est la chose la plus ridicule qui t'ait fait pleurer ?" },
  { id: 'soft-v-80', type: 'truth', level: 'soft', text: "As-tu déjà eu honte de tes parents en public ?" },
  { id: 'soft-v-81', type: 'truth', level: 'soft', text: "Quel est ton compte Instagram ou TikTok le plus bizarre que tu suis ?" },
  { id: 'soft-v-82', type: 'truth', level: 'soft', text: "Si tu ne pouvais manger qu'un seul aliment pour le reste de ta vie ?" },
  { id: 'soft-v-83', type: 'truth', level: 'soft', text: "As-tu déjà menti lors d'un entretien d'embauche ?" },
  { id: 'soft-v-84', type: 'truth', level: 'soft', text: "Quelle est ta pire phobie liée aux insectes ?" },
  { id: 'soft-v-85', type: 'truth', level: 'soft', text: "Quel est le dernier compliment que tu t'es fait dans le miroir ?" },
  { id: 'soft-v-86', type: 'truth', level: 'soft', text: "As-tu déjà été ghosté(e) d'une façon mémorable ?" },
  { id: 'soft-v-87', type: 'truth', level: 'soft', text: "Quelle est la célébrité pour qui tu as eu le plus gros crush ado ?" },
  { id: 'soft-v-88', type: 'truth', level: 'soft', text: "Quel est ton pire souvenir de dentiste ?" },
  { id: 'soft-v-89', type: 'truth', level: 'soft', text: "As-tu déjà fait semblant de téléphoner pour éviter quelqu'un ?" },
  { id: 'soft-v-90', type: 'truth', level: 'soft', text: "Quelle est ton excuse favorite quand tu es en retard ?" },
  { id: 'soft-v-91', type: 'truth', level: 'soft', text: "Quel est le truc le plus cliché que tu fais en secret ?" },
  { id: 'soft-v-92', type: 'truth', level: 'soft', text: "As-tu déjà gâché une surprise ?" },
  { id: 'soft-v-93', type: 'truth', level: 'soft', text: "Quelle est ta pire habitude au réveil ?" },
  { id: 'soft-v-94', type: 'truth', level: 'soft', text: "Quel est ton record de temps sans te doucher ?" },
  { id: 'soft-v-95', type: 'truth', level: 'soft', text: "As-tu déjà fouillé les affaires d'un de tes frères et sœurs ?" },
  { id: 'soft-v-96', type: 'truth', level: 'soft', text: "Quelle est la phobie la plus bizarre d'un de tes proches ?" },
  { id: 'soft-v-97', type: 'truth', level: 'soft', text: "Quel est le film d'horreur qui t'a le plus traumatisé ?" },
  { id: 'soft-v-98', type: 'truth', level: 'soft', text: "As-tu déjà mangé quelque chose tombé par terre depuis plus de 5 secondes ?" },
  { id: 'soft-v-99', type: 'truth', level: 'soft', text: "Quelle est ton anecdote la plus drôle avec la police ?" },
  { id: 'soft-v-100', type: 'truth', level: 'soft', text: "Quel est le pire métier que tu pourrais exercer ?" },
  { id: 'soft-v-101', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà envoyé un texto à la mauvaise personne avec des conséquences graves ?" },
  { id: 'soft-v-102', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà envoyé un texto à la mauvaise personne avec des conséquences graves ?" },
  { id: 'soft-v-103', type: 'truth', level: 'soft', text: "En public, as-tu déjà envoyé un texto à la mauvaise personne avec des conséquences graves ?" },
  { id: 'soft-v-104', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà envoyé un texto à la mauvaise personne avec des conséquences graves ?" },
  { id: 'soft-v-105', type: 'truth', level: 'soft', text: "Récemment, quel est ton pire souvenir avec l'alcool (sans être trash) ?" },
  { id: 'soft-v-106', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est ton pire souvenir avec l'alcool (sans être trash) ?" },
  { id: 'soft-v-107', type: 'truth', level: 'soft', text: "En public, quel est ton pire souvenir avec l'alcool (sans être trash) ?" },
  { id: 'soft-v-108', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est ton pire souvenir avec l'alcool (sans être trash) ?" },
  { id: 'soft-v-109', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà triché à un jeu de société de façon éhontée ?" },
  { id: 'soft-v-110', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà triché à un jeu de société de façon éhontée ?" },
  { id: 'soft-v-111', type: 'truth', level: 'soft', text: "En public, as-tu déjà triché à un jeu de société de façon éhontée ?" },
  { id: 'soft-v-112', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà triché à un jeu de société de façon éhontée ?" },
  { id: 'soft-v-113', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire anecdote au supermarché ?" },
  { id: 'soft-v-114', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire anecdote au supermarché ?" },
  { id: 'soft-v-115', type: 'truth', level: 'soft', text: "En public, quelle est ta pire anecdote au supermarché ?" },
  { id: 'soft-v-116', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire anecdote au supermarché ?" },
  { id: 'soft-v-117', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà eu un crush sur un personnage de jeu vidéo ?" },
  { id: 'soft-v-118', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà eu un crush sur un personnage de jeu vidéo ?" },
  { id: 'soft-v-119', type: 'truth', level: 'soft', text: "En public, as-tu déjà eu un crush sur un personnage de jeu vidéo ?" },
  { id: 'soft-v-120', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà eu un crush sur un personnage de jeu vidéo ?" },
  { id: 'soft-v-121', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire gaffe lors d'un repas de famille ?" },
  { id: 'soft-v-122', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire gaffe lors d'un repas de famille ?" },
  { id: 'soft-v-123', type: 'truth', level: 'soft', text: "En public, quelle est ta pire gaffe lors d'un repas de famille ?" },
  { id: 'soft-v-124', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire gaffe lors d'un repas de famille ?" },
  { id: 'soft-v-125', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà utilisé la brosse à dents de quelqu'un d'autre ?" },
  { id: 'soft-v-126', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà utilisé la brosse à dents de quelqu'un d'autre ?" },
  { id: 'soft-v-127', type: 'truth', level: 'soft', text: "En public, as-tu déjà utilisé la brosse à dents de quelqu'un d'autre ?" },
  { id: 'soft-v-128', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà utilisé la brosse à dents de quelqu'un d'autre ?" },
  { id: 'soft-v-129', type: 'truth', level: 'soft', text: "Récemment, quel est ton pire mensonge à un professeur ?" },
  { id: 'soft-v-130', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est ton pire mensonge à un professeur ?" },
  { id: 'soft-v-131', type: 'truth', level: 'soft', text: "En public, quel est ton pire mensonge à un professeur ?" },
  { id: 'soft-v-132', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est ton pire mensonge à un professeur ?" },
  { id: 'soft-v-133', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire peur irrationnelle en avion ou en voiture ?" },
  { id: 'soft-v-134', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire peur irrationnelle en avion ou en voiture ?" },
  { id: 'soft-v-135', type: 'truth', level: 'soft', text: "En public, quelle est ta pire peur irrationnelle en avion ou en voiture ?" },
  { id: 'soft-v-136', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire peur irrationnelle en avion ou en voiture ?" },
  { id: 'soft-v-137', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà lu le journal intime de quelqu'un ?" },
  { id: 'soft-v-138', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà lu le journal intime de quelqu'un ?" },
  { id: 'soft-v-139', type: 'truth', level: 'soft', text: "En public, as-tu déjà lu le journal intime de quelqu'un ?" },
  { id: 'soft-v-140', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà lu le journal intime de quelqu'un ?" },
  { id: 'soft-v-141', type: 'truth', level: 'soft', text: "Récemment, quel est le pire message que tu aies reçu par erreur ?" },
  { id: 'soft-v-142', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est le pire message que tu aies reçu par erreur ?" },
  { id: 'soft-v-143', type: 'truth', level: 'soft', text: "En public, quel est le pire message que tu aies reçu par erreur ?" },
  { id: 'soft-v-144', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est le pire message que tu aies reçu par erreur ?" },
  { id: 'soft-v-145', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà été amoureux(se) en secret d'un(e) ami(e) présent(e) ?" },
  { id: 'soft-v-146', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà été amoureux(se) en secret d'un(e) ami(e) présent(e) ?" },
  { id: 'soft-v-147', type: 'truth', level: 'soft', text: "En public, as-tu déjà été amoureux(se) en secret d'un(e) ami(e) présent(e) ?" },
  { id: 'soft-v-148', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà été amoureux(se) en secret d'un(e) ami(e) présent(e) ?" },
  { id: 'soft-v-149', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire habitude quand tu es stressé(e) ?" },
  { id: 'soft-v-150', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire habitude quand tu es stressé(e) ?" },
  { id: 'soft-v-151', type: 'truth', level: 'soft', text: "En public, quelle est ta pire habitude quand tu es stressé(e) ?" },
  { id: 'soft-v-152', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire habitude quand tu es stressé(e) ?" },
  { id: 'soft-v-153', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà fait un rêve érotique sur quelqu'un ici ?" },
  { id: 'soft-v-154', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà fait un rêve érotique sur quelqu'un ici ?" },
  { id: 'soft-v-155', type: 'truth', level: 'soft', text: "En public, as-tu déjà fait un rêve érotique sur quelqu'un ici ?" },
  { id: 'soft-v-156', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà fait un rêve érotique sur quelqu'un ici ?" },
  { id: 'soft-v-157', type: 'truth', level: 'soft', text: "Récemment, quel est le pire date que tu aies organisé ?" },
  { id: 'soft-v-158', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est le pire date que tu aies organisé ?" },
  { id: 'soft-v-159', type: 'truth', level: 'soft', text: "En public, quel est le pire date que tu aies organisé ?" },
  { id: 'soft-v-160', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est le pire date que tu aies organisé ?" },
  { id: 'soft-v-161', type: 'truth', level: 'soft', text: "Récemment, quelle est l'émission ringarde que tu regardes en cachette ?" },
  { id: 'soft-v-162', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est l'émission ringarde que tu regardes en cachette ?" },
  { id: 'soft-v-163', type: 'truth', level: 'soft', text: "En public, quelle est l'émission ringarde que tu regardes en cachette ?" },
  { id: 'soft-v-164', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est l'émission ringarde que tu regardes en cachette ?" },
  { id: 'soft-v-165', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà pleuré pour une rupture qui n'était pas la tienne ?" },
  { id: 'soft-v-166', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà pleuré pour une rupture qui n'était pas la tienne ?" },
  { id: 'soft-v-167', type: 'truth', level: 'soft', text: "En public, as-tu déjà pleuré pour une rupture qui n'était pas la tienne ?" },
  { id: 'soft-v-168', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà pleuré pour une rupture qui n'était pas la tienne ?" },
  { id: 'soft-v-169', type: 'truth', level: 'soft', text: "Récemment, quel est ton pire complexe physique que personne ne remarque ?" },
  { id: 'soft-v-170', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est ton pire complexe physique que personne ne remarque ?" },
  { id: 'soft-v-171', type: 'truth', level: 'soft', text: "En public, quel est ton pire complexe physique que personne ne remarque ?" },
  { id: 'soft-v-172', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est ton pire complexe physique que personne ne remarque ?" },
  { id: 'soft-v-173', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire excuse pour ne pas aller au sport ?" },
  { id: 'soft-v-174', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire excuse pour ne pas aller au sport ?" },
  { id: 'soft-v-175', type: 'truth', level: 'soft', text: "En public, quelle est ta pire excuse pour ne pas aller au sport ?" },
  { id: 'soft-v-176', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire excuse pour ne pas aller au sport ?" },
  { id: 'soft-v-177', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà eu une amende ridicule ?" },
  { id: 'soft-v-178', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà eu une amende ridicule ?" },
  { id: 'soft-v-179', type: 'truth', level: 'soft', text: "En public, as-tu déjà eu une amende ridicule ?" },
  { id: 'soft-v-180', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà eu une amende ridicule ?" },
  { id: 'soft-v-181', type: 'truth', level: 'soft', text: "Récemment, quel est le film triste qui te fait pleurer à chaque fois ?" },
  { id: 'soft-v-182', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est le film triste qui te fait pleurer à chaque fois ?" },
  { id: 'soft-v-183', type: 'truth', level: 'soft', text: "En public, quel est le film triste qui te fait pleurer à chaque fois ?" },
  { id: 'soft-v-184', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est le film triste qui te fait pleurer à chaque fois ?" },
  { id: 'soft-v-185', type: 'truth', level: 'soft', text: "Récemment, quelle est ta pire habitude au volant ?" },
  { id: 'soft-v-186', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est ta pire habitude au volant ?" },
  { id: 'soft-v-187', type: 'truth', level: 'soft', text: "En public, quelle est ta pire habitude au volant ?" },
  { id: 'soft-v-188', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est ta pire habitude au volant ?" },
  { id: 'soft-v-189', type: 'truth', level: 'soft', text: "Récemment, as-tu déjà fouillé l'historique web de quelqu'un ?" },
  { id: 'soft-v-190', type: 'truth', level: 'soft', text: "Quand tu étais ado, as-tu déjà fouillé l'historique web de quelqu'un ?" },
  { id: 'soft-v-191', type: 'truth', level: 'soft', text: "En public, as-tu déjà fouillé l'historique web de quelqu'un ?" },
  { id: 'soft-v-192', type: 'truth', level: 'soft', text: "Pendant les vacances, as-tu déjà fouillé l'historique web de quelqu'un ?" },
  { id: 'soft-v-193', type: 'truth', level: 'soft', text: "Récemment, quel est le pire surnom que tes parents te donnaient ?" },
  { id: 'soft-v-194', type: 'truth', level: 'soft', text: "Quand tu étais ado, quel est le pire surnom que tes parents te donnaient ?" },
  { id: 'soft-v-195', type: 'truth', level: 'soft', text: "En public, quel est le pire surnom que tes parents te donnaient ?" },
  { id: 'soft-v-196', type: 'truth', level: 'soft', text: "Pendant les vacances, quel est le pire surnom que tes parents te donnaient ?" },
  { id: 'soft-v-197', type: 'truth', level: 'soft', text: "Récemment, quelle est la chose la plus chère que tu aies achetée sur un coup de tête ?" },
  { id: 'soft-v-198', type: 'truth', level: 'soft', text: "Quand tu étais ado, quelle est la chose la plus chère que tu aies achetée sur un coup de tête ?" },
  { id: 'soft-v-199', type: 'truth', level: 'soft', text: "En public, quelle est la chose la plus chère que tu aies achetée sur un coup de tête ?" },
  { id: 'soft-v-200', type: 'truth', level: 'soft', text: "Pendant les vacances, quelle est la chose la plus chère que tu aies achetée sur un coup de tête ?" },
  { id: 'soft-a-1', type: 'action', level: 'soft', text: "Montre la dernière photo de ta pellicule." },
  { id: 'soft-a-2', type: 'action', level: 'soft', text: "Imite l'accent québécois pendant 1 minute." },
  { id: 'soft-a-3', type: 'action', level: 'soft', text: "Envoie un emoji 🍑 à la 3ème personne dans tes DM Instagram." },
  { id: 'soft-a-4', type: 'action', level: 'soft', text: "Laisse le joueur à ta droite changer ta photo de profil WhatsApp pendant 5 min." },
  { id: 'soft-a-5', type: 'action', level: 'soft', text: "Mime une scène de film culte, les autres doivent deviner." },
  { id: 'soft-a-6', type: 'action', level: 'soft', text: "Fais le tour de la pièce en marchant comme un canard." },
  { id: 'soft-a-7', type: 'action', level: 'soft', text: "Appelle un membre de ta famille et dis-lui que tu l'aimes sans contexte." },
  { id: 'soft-a-8', type: 'action', level: 'soft', text: "Bois un verre d'eau sans utiliser tes mains." },
  { id: 'soft-a-9', type: 'action', level: 'soft', text: "Parle avec la langue tirée jusqu'à ton prochain tour." },
  { id: 'soft-a-10', type: 'action', level: 'soft', text: "Masse les épaules de la personne à ta gauche pendant 1 minute." },
  { id: 'soft-a-11', type: 'action', level: 'soft', text: "Fais 10 pompes (ou essaie)." },
  { id: 'soft-a-12', type: 'action', level: 'soft', text: "Imite un influenceur qui fait un placement de produit pour un stylo." },
  { id: 'soft-a-13', type: 'action', level: 'soft', text: "Chante le refrain de ta chanson préférée à pleine voix." },
  { id: 'soft-a-14', type: 'action', level: 'soft', text: "Laisse le groupe lire ton dernier message reçu." },
  { id: 'soft-a-15', type: 'action', level: 'soft', text: "Mange une cuillère à soupe de moutarde ou de mayo." },
  { id: 'soft-a-16', type: 'action', level: 'soft', text: "Fais un compliment sincère à chaque joueur." },
  { id: 'soft-a-17', type: 'action', level: 'soft', text: "Danse la Macarena sans musique." },
  { id: 'soft-a-18', type: 'action', level: 'soft', text: "Raconte une blague nulle. Si personne ne rit, bois 1 gorgée." },
  { id: 'soft-a-19', type: 'action', level: 'soft', text: "Change ton statut WhatsApp pour 'J'adore les pieds'." },
  { id: 'soft-a-20', type: 'action', level: 'soft', text: "Fais un câlin de 10 secondes à la personne en face de toi." },
  { id: 'soft-a-21', type: 'action', level: 'soft', text: "Fais semblant d'être un chat pendant 2 minutes." },
  { id: 'soft-a-22', type: 'action', level: 'soft', text: "Épelle ton prénom à l'envers très rapidement." },
  { id: 'soft-a-23', type: 'action', level: 'soft', text: "Laisse le joueur de ton choix tweeter (ou poster) ce qu'il veut sur ton compte." },
  { id: 'soft-a-24', type: 'action', level: 'soft', text: "Fais un concours de regards avec le joueur à ta droite (le perdant boit)." },
  { id: 'soft-a-25', type: 'action', level: 'soft', text: "Imite le rire d'un des joueurs." },
  { id: 'soft-a-26', type: 'action', level: 'soft', text: "Bois une gorgée du verre de ton voisin." },
  { id: 'soft-a-27', type: 'action', level: 'soft', text: "Mime la personne de ton choix dans la pièce, on doit deviner." },
  { id: 'soft-a-28', type: 'action', level: 'soft', text: "Mets tes vêtements à l'envers jusqu'à la fin de la partie." },
  { id: 'soft-a-29', type: 'action', level: 'soft', text: "Prends un selfie avec la pire grimace possible et mets-le en story." },
  { id: 'soft-a-30', type: 'action', level: 'soft', text: "Parle comme un robot pendant tes 3 prochaines interventions." },
  { id: 'soft-a-31', type: 'action', level: 'soft', text: "Fais une déclaration d'amour à un meuble de la pièce." },
  { id: 'soft-a-32', type: 'action', level: 'soft', text: "Dessine sur ton front avec un stylo." },
  { id: 'soft-a-33', type: 'action', level: 'soft', text: "Laisse la personne à ta gauche te recoiffer." },
  { id: 'soft-a-34', type: 'action', level: 'soft', text: "Raconte l'histoire de ton premier baiser avec des bruits d'animaux." },
  { id: 'soft-a-35', type: 'action', level: 'soft', text: "Fais l'alphabet en rotant (ou essaie au moins 3 lettres)." },
  { id: 'soft-a-36', type: 'action', level: 'soft', text: "Tiens-toi sur une jambe pendant 1 minute." },
  { id: 'soft-a-37', type: 'action', level: 'soft', text: "Fais un discours de remerciement digne des Oscars pour un objet banal." },
  { id: 'soft-a-38', type: 'action', level: 'soft', text: "Mets un glaçon dans ton t-shirt." },
  { id: 'soft-a-39', type: 'action', level: 'soft', text: "Laisse le groupe choisir ta sonnerie de téléphone pour demain." },
  { id: 'soft-a-40', type: 'action', level: 'soft', text: "Envoie 'Je crois que je suis amoureux/se de toi' à ton dernier contact." },
  { id: 'soft-a-41', type: 'action', level: 'soft', text: "Fais un beatbox pendant 30 secondes." },
  { id: 'soft-a-42', type: 'action', level: 'soft', text: "Essaye de lécher ton coude." },
  { id: 'soft-a-43', type: 'action', level: 'soft', text: "Garde les yeux fermés jusqu'à ton prochain tour." },
  { id: 'soft-a-44', type: 'action', level: 'soft', text: "Imite un bébé qui pleure jusqu'à ce que quelqu'un te console." },
  { id: 'soft-a-45', type: 'action', level: 'soft', text: "Mime ton activité préférée sous la douche." },
  { id: 'soft-a-46', type: 'action', level: 'soft', text: "Chuchote tout ce que tu dis jusqu'à ton prochain tour." },
  { id: 'soft-a-47', type: 'action', level: 'soft', text: "Donne ton téléphone au joueur en face, il a 30 secondes pour regarder ce qu'il veut." },
  { id: 'soft-a-48', type: 'action', level: 'soft', text: "Mange un aliment sans utiliser tes mains." },
  { id: 'soft-a-49', type: 'action', level: 'soft', text: "Fais le poirier (ou une roulade) avec élégance." },
  { id: 'soft-a-50', type: 'action', level: 'soft', text: "Invente une chanson sur le joueur à ta droite." },
  { id: 'soft-a-51', type: 'action', level: 'soft', text: "Fais un massage de crâne à la personne à ta gauche." },
  { id: 'soft-a-52', type: 'action', level: 'soft', text: "Imite un personnage célèbre, les autres doivent deviner." },
  { id: 'soft-a-53', type: 'action', level: 'soft', text: "Parle avec un accent marseillais pendant 5 minutes." },
  { id: 'soft-a-54', type: 'action', level: 'soft', text: "Fais une demande en mariage dramatique au joueur de ton choix." },
  { id: 'soft-a-55', type: 'action', level: 'soft', text: "Mets un bandeau sur les yeux et essaie de deviner qui tu touches." },
  { id: 'soft-a-56', type: 'action', level: 'soft', text: "Laisse le joueur à ta droite te maquiller à l'aveugle." },
  { id: 'soft-a-57', type: 'action', level: 'soft', text: "Danse comme si tu étais en boîte de nuit sur de la musique classique." },
  { id: 'soft-a-58', type: 'action', level: 'soft', text: "Chante 'Joyeux Anniversaire' de façon très triste." },
  { id: 'soft-a-59', type: 'action', level: 'soft', text: "Fais semblant d'être ivre pendant 3 minutes." },
  { id: 'soft-a-60', type: 'action', level: 'soft', text: "Mime une bagarre au ralenti." },
  { id: 'soft-a-61', type: 'action', level: 'soft', text: "Prends la voix la plus grave possible jusqu'à ton prochain tour." },
  { id: 'soft-a-62', type: 'action', level: 'soft', text: "Fais une publicité pour le papier toilette." },
  { id: 'soft-a-63', type: 'action', level: 'soft', text: "Fais un poème pour le joueur qui a le moins de points." },
  { id: 'soft-a-64', type: 'action', level: 'soft', text: "Agis comme le garde du corps du joueur à ta gauche." },
  { id: 'soft-a-65', type: 'action', level: 'soft', text: "Envoie un vocal à ton ex (ou à un ami) en chantant." },
  { id: 'soft-a-66', type: 'action', level: 'soft', text: "Renifle les chaussettes du joueur à ta droite." },
  { id: 'soft-a-67', type: 'action', level: 'soft', text: "Mange un morceau d'oignon cru ou de citron." },
  { id: 'soft-a-68', type: 'action', level: 'soft', text: "Fais la roue (ou essaie)." },
  { id: 'soft-a-69', type: 'action', level: 'soft', text: "Invente une chorégraphie TikTok de 10 secondes et réalise-la." },
  { id: 'soft-a-70', type: 'action', level: 'soft', text: "Imite ton prof (ou patron) le plus détesté." },
  { id: 'soft-a-71', type: 'action', level: 'soft', text: "Fais un Tuto Beauté hilarant avec rien." },
  { id: 'soft-a-72', type: 'action', level: 'soft', text: "Lis tes 3 dernières recherches Google à voix haute." },
  { id: 'soft-a-73', type: 'action', level: 'soft', text: "Change le surnom d'un contact au hasard dans ton téléphone en 'Mon amour caché'." },
  { id: 'soft-a-74', type: 'action', level: 'soft', text: "Parle avec le nez bouché pendant 2 tours." },
  { id: 'soft-a-75', type: 'action', level: 'soft', text: "Fais comme si tu animais une émission de télé-achat pour vendre la table." },
  { id: 'soft-a-76', type: 'action', level: 'soft', text: "Déclare ton amour inconditionnel à un coussin." },
  { id: 'soft-a-77', type: 'action', level: 'soft', text: "Touche ton nez avec ta langue." },
  { id: 'soft-a-78', type: 'action', level: 'soft', text: "Fais 5 squats en criant une insulte à chaque fois." },
  { id: 'soft-a-79', type: 'action', level: 'soft', text: "Laisse le joueur de ton choix prendre une photo de toi." },
  { id: 'soft-a-80', type: 'action', level: 'soft', text: "Imite un animal en pleine parade nuptiale." },
  { id: 'soft-a-81', type: 'action', level: 'soft', text: "Garde un doigt dans ton oreille jusqu'à ton prochain tour." },
  { id: 'soft-a-82', type: 'action', level: 'soft', text: "Mime la préparation de ton plat préféré." },
  { id: 'soft-a-83', type: 'action', level: 'soft', text: "Appelle une pizzeria et demande s'ils vendent des hamburgers." },
  { id: 'soft-a-84', type: 'action', level: 'soft', text: "Fais une critique gastronomique de la boisson que tu bois." },
  { id: 'soft-a-85', type: 'action', level: 'soft', text: "Imite un tyrannosaure pendant 1 minute." },
  { id: 'soft-a-86', type: 'action', level: 'soft', text: "Fais un tour de magie raté." },
  { id: 'soft-a-87', type: 'action', level: 'soft', text: "Twerk pendant 10 secondes." },
  { id: 'soft-a-88', type: 'action', level: 'soft', text: "Agis comme si tu avais perdu la mémoire pendant 2 minutes." },
  { id: 'soft-a-89', type: 'action', level: 'soft', text: "Laisse le groupe choisir un mot que tu n'auras pas le droit de dire." },
  { id: 'soft-a-90', type: 'action', level: 'soft', text: "Fais un air guitar très passionné sur une chanson de ton choix." },
  { id: 'soft-a-91', type: 'action', level: 'soft', text: "Montre le dernier TikTok ou Reel que tu as liké." },
  { id: 'soft-a-92', type: 'action', level: 'soft', text: "Chante une chanson de Disney en faisant les voix de tous les personnages." },
  { id: 'soft-a-93', type: 'action', level: 'soft', text: "Mime le dernier film que tu as vu." },
  { id: 'soft-a-94', type: 'action', level: 'soft', text: "Fais un discours politique pour devenir président(e) de la soirée." },
  { id: 'soft-a-95', type: 'action', level: 'soft', text: "Laisse la personne à ta gauche te nourrir pendant 1 minute." },
  { id: 'soft-a-96', type: 'action', level: 'soft', text: "Fais une imitation d'une personne dans la pièce." },
  { id: 'soft-a-97', type: 'action', level: 'soft', text: "Mange un biscuit en faisant le plus de bruit possible." },
  { id: 'soft-a-98', type: 'action', level: 'soft', text: "Fais une pose de mannequin de haute couture et garde-la 30 sec." },
  { id: 'soft-a-99', type: 'action', level: 'soft', text: "Agis comme si tu étais le roi/la reine d'un pays imaginaire." },
  { id: 'soft-a-100', type: 'action', level: 'soft', text: "Laisse quelqu'un te dessiner une moustache avec un stylo ou du maquillage." },
  { id: 'soft-a-101', type: 'action', level: 'soft', text: "En fermant les yeux, imite ton chanteur préféré." },
  { id: 'soft-a-102', type: 'action', level: 'soft', text: "En sautant sur un pied, imite ton chanteur préféré." },
  { id: 'soft-a-103', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, imite ton chanteur préféré." },
  { id: 'soft-a-104', type: 'action', level: 'soft', text: "Avec l'accent anglais, imite ton chanteur préféré." },
  { id: 'soft-a-105', type: 'action', level: 'soft', text: "En fermant les yeux, chante une chanson paillarde." },
  { id: 'soft-a-106', type: 'action', level: 'soft', text: "En sautant sur un pied, chante une chanson paillarde." },
  { id: 'soft-a-107', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, chante une chanson paillarde." },
  { id: 'soft-a-108', type: 'action', level: 'soft', text: "Avec l'accent anglais, chante une chanson paillarde." },
  { id: 'soft-a-109', type: 'action', level: 'soft', text: "En fermant les yeux, raconte une blague de Toto." },
  { id: 'soft-a-110', type: 'action', level: 'soft', text: "En sautant sur un pied, raconte une blague de Toto." },
  { id: 'soft-a-111', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, raconte une blague de Toto." },
  { id: 'soft-a-112', type: 'action', level: 'soft', text: "Avec l'accent anglais, raconte une blague de Toto." },
  { id: 'soft-a-113', type: 'action', level: 'soft', text: "En fermant les yeux, fais 10 abdos." },
  { id: 'soft-a-114', type: 'action', level: 'soft', text: "En sautant sur un pied, fais 10 abdos." },
  { id: 'soft-a-115', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais 10 abdos." },
  { id: 'soft-a-116', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais 10 abdos." },
  { id: 'soft-a-117', type: 'action', level: 'soft', text: "En fermant les yeux, invente une rumeur sur la personne à ta droite." },
  { id: 'soft-a-118', type: 'action', level: 'soft', text: "En sautant sur un pied, invente une rumeur sur la personne à ta droite." },
  { id: 'soft-a-119', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, invente une rumeur sur la personne à ta droite." },
  { id: 'soft-a-120', type: 'action', level: 'soft', text: "Avec l'accent anglais, invente une rumeur sur la personne à ta droite." },
  { id: 'soft-a-121', type: 'action', level: 'soft', text: "En fermant les yeux, fais un discours d'excuse pour avoir mangé le dernier gâteau." },
  { id: 'soft-a-122', type: 'action', level: 'soft', text: "En sautant sur un pied, fais un discours d'excuse pour avoir mangé le dernier gâteau." },
  { id: 'soft-a-123', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais un discours d'excuse pour avoir mangé le dernier gâteau." },
  { id: 'soft-a-124', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais un discours d'excuse pour avoir mangé le dernier gâteau." },
  { id: 'soft-a-125', type: 'action', level: 'soft', text: "En fermant les yeux, mime un animal sous-marin." },
  { id: 'soft-a-126', type: 'action', level: 'soft', text: "En sautant sur un pied, mime un animal sous-marin." },
  { id: 'soft-a-127', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, mime un animal sous-marin." },
  { id: 'soft-a-128', type: 'action', level: 'soft', text: "Avec l'accent anglais, mime un animal sous-marin." },
  { id: 'soft-a-129', type: 'action', level: 'soft', text: "En fermant les yeux, fais une déclaration d'amour à la personne de ton choix." },
  { id: 'soft-a-130', type: 'action', level: 'soft', text: "En sautant sur un pied, fais une déclaration d'amour à la personne de ton choix." },
  { id: 'soft-a-131', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais une déclaration d'amour à la personne de ton choix." },
  { id: 'soft-a-132', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais une déclaration d'amour à la personne de ton choix." },
  { id: 'soft-a-133', type: 'action', level: 'soft', text: "En fermant les yeux, critique la tenue de la personne à ta gauche avec bienveillance." },
  { id: 'soft-a-134', type: 'action', level: 'soft', text: "En sautant sur un pied, critique la tenue de la personne à ta gauche avec bienveillance." },
  { id: 'soft-a-135', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, critique la tenue de la personne à ta gauche avec bienveillance." },
  { id: 'soft-a-136', type: 'action', level: 'soft', text: "Avec l'accent anglais, critique la tenue de la personne à ta gauche avec bienveillance." },
  { id: 'soft-a-137', type: 'action', level: 'soft', text: "En fermant les yeux, fais le bruit d'une voiture de course qui passe." },
  { id: 'soft-a-138', type: 'action', level: 'soft', text: "En sautant sur un pied, fais le bruit d'une voiture de course qui passe." },
  { id: 'soft-a-139', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais le bruit d'une voiture de course qui passe." },
  { id: 'soft-a-140', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais le bruit d'une voiture de course qui passe." },
  { id: 'soft-a-141', type: 'action', level: 'soft', text: "En fermant les yeux, imite une personne âgée qui traverse la rue." },
  { id: 'soft-a-142', type: 'action', level: 'soft', text: "En sautant sur un pied, imite une personne âgée qui traverse la rue." },
  { id: 'soft-a-143', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, imite une personne âgée qui traverse la rue." },
  { id: 'soft-a-144', type: 'action', level: 'soft', text: "Avec l'accent anglais, imite une personne âgée qui traverse la rue." },
  { id: 'soft-a-145', type: 'action', level: 'soft', text: "En fermant les yeux, fais une démonstration de karaté." },
  { id: 'soft-a-146', type: 'action', level: 'soft', text: "En sautant sur un pied, fais une démonstration de karaté." },
  { id: 'soft-a-147', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais une démonstration de karaté." },
  { id: 'soft-a-148', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais une démonstration de karaté." },
  { id: 'soft-a-149', type: 'action', level: 'soft', text: "En fermant les yeux, chante l'alphabet en rythme." },
  { id: 'soft-a-150', type: 'action', level: 'soft', text: "En sautant sur un pied, chante l'alphabet en rythme." },
  { id: 'soft-a-151', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, chante l'alphabet en rythme." },
  { id: 'soft-a-152', type: 'action', level: 'soft', text: "Avec l'accent anglais, chante l'alphabet en rythme." },
  { id: 'soft-a-153', type: 'action', level: 'soft', text: "En fermant les yeux, raconte ton dernier rêve comme si c'était un film d'action." },
  { id: 'soft-a-154', type: 'action', level: 'soft', text: "En sautant sur un pied, raconte ton dernier rêve comme si c'était un film d'action." },
  { id: 'soft-a-155', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, raconte ton dernier rêve comme si c'était un film d'action." },
  { id: 'soft-a-156', type: 'action', level: 'soft', text: "Avec l'accent anglais, raconte ton dernier rêve comme si c'était un film d'action." },
  { id: 'soft-a-157', type: 'action', level: 'soft', text: "En fermant les yeux, fais une météo dramatique pour demain." },
  { id: 'soft-a-158', type: 'action', level: 'soft', text: "En sautant sur un pied, fais une météo dramatique pour demain." },
  { id: 'soft-a-159', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais une météo dramatique pour demain." },
  { id: 'soft-a-160', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais une météo dramatique pour demain." },
  { id: 'soft-a-161', type: 'action', level: 'soft', text: "En fermant les yeux, mime un astronaute sur la lune." },
  { id: 'soft-a-162', type: 'action', level: 'soft', text: "En sautant sur un pied, mime un astronaute sur la lune." },
  { id: 'soft-a-163', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, mime un astronaute sur la lune." },
  { id: 'soft-a-164', type: 'action', level: 'soft', text: "Avec l'accent anglais, mime un astronaute sur la lune." },
  { id: 'soft-a-165', type: 'action', level: 'soft', text: "En fermant les yeux, fais la voix d'un animateur radio des années 80." },
  { id: 'soft-a-166', type: 'action', level: 'soft', text: "En sautant sur un pied, fais la voix d'un animateur radio des années 80." },
  { id: 'soft-a-167', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais la voix d'un animateur radio des années 80." },
  { id: 'soft-a-168', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais la voix d'un animateur radio des années 80." },
  { id: 'soft-a-169', type: 'action', level: 'soft', text: "En fermant les yeux, imite un oiseau qui essaie de séduire." },
  { id: 'soft-a-170', type: 'action', level: 'soft', text: "En sautant sur un pied, imite un oiseau qui essaie de séduire." },
  { id: 'soft-a-171', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, imite un oiseau qui essaie de séduire." },
  { id: 'soft-a-172', type: 'action', level: 'soft', text: "Avec l'accent anglais, imite un oiseau qui essaie de séduire." },
  { id: 'soft-a-173', type: 'action', level: 'soft', text: "En fermant les yeux, fais comme si tu faisais du hula-hoop." },
  { id: 'soft-a-174', type: 'action', level: 'soft', text: "En sautant sur un pied, fais comme si tu faisais du hula-hoop." },
  { id: 'soft-a-175', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais comme si tu faisais du hula-hoop." },
  { id: 'soft-a-176', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais comme si tu faisais du hula-hoop." },
  { id: 'soft-a-177', type: 'action', level: 'soft', text: "En fermant les yeux, raconte un souvenir d'enfance en pleurant à moitié." },
  { id: 'soft-a-178', type: 'action', level: 'soft', text: "En sautant sur un pied, raconte un souvenir d'enfance en pleurant à moitié." },
  { id: 'soft-a-179', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, raconte un souvenir d'enfance en pleurant à moitié." },
  { id: 'soft-a-180', type: 'action', level: 'soft', text: "Avec l'accent anglais, raconte un souvenir d'enfance en pleurant à moitié." },
  { id: 'soft-a-181', type: 'action', level: 'soft', text: "En fermant les yeux, mime une personne qui a très envie d'aller aux toilettes." },
  { id: 'soft-a-182', type: 'action', level: 'soft', text: "En sautant sur un pied, mime une personne qui a très envie d'aller aux toilettes." },
  { id: 'soft-a-183', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, mime une personne qui a très envie d'aller aux toilettes." },
  { id: 'soft-a-184', type: 'action', level: 'soft', text: "Avec l'accent anglais, mime une personne qui a très envie d'aller aux toilettes." },
  { id: 'soft-a-185', type: 'action', level: 'soft', text: "En fermant les yeux, fais semblant de jouer du piano comme un virtuose." },
  { id: 'soft-a-186', type: 'action', level: 'soft', text: "En sautant sur un pied, fais semblant de jouer du piano comme un virtuose." },
  { id: 'soft-a-187', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais semblant de jouer du piano comme un virtuose." },
  { id: 'soft-a-188', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais semblant de jouer du piano comme un virtuose." },
  { id: 'soft-a-189', type: 'action', level: 'soft', text: "En fermant les yeux, imite le cri de guerre d'un samouraï." },
  { id: 'soft-a-190', type: 'action', level: 'soft', text: "En sautant sur un pied, imite le cri de guerre d'un samouraï." },
  { id: 'soft-a-191', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, imite le cri de guerre d'un samouraï." },
  { id: 'soft-a-192', type: 'action', level: 'soft', text: "Avec l'accent anglais, imite le cri de guerre d'un samouraï." },
  { id: 'soft-a-193', type: 'action', level: 'soft', text: "En fermant les yeux, fais un bruit d'alarme jusqu'à ce qu'on te demande d'arrêter." },
  { id: 'soft-a-194', type: 'action', level: 'soft', text: "En sautant sur un pied, fais un bruit d'alarme jusqu'à ce qu'on te demande d'arrêter." },
  { id: 'soft-a-195', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, fais un bruit d'alarme jusqu'à ce qu'on te demande d'arrêter." },
  { id: 'soft-a-196', type: 'action', level: 'soft', text: "Avec l'accent anglais, fais un bruit d'alarme jusqu'à ce qu'on te demande d'arrêter." },
  { id: 'soft-a-197', type: 'action', level: 'soft', text: "En fermant les yeux, mime un chef cuisinier très stressé." },
  { id: 'soft-a-198', type: 'action', level: 'soft', text: "En sautant sur un pied, mime un chef cuisinier très stressé." },
  { id: 'soft-a-199', type: 'action', level: 'soft', text: "Avec un verre d'eau sur la tête, mime un chef cuisinier très stressé." },
  { id: 'soft-a-200', type: 'action', level: 'soft', text: "Avec l'accent anglais, mime un chef cuisinier très stressé." },
  // À SUIVRE : VAGUE 2 (MEDIUM)
];
