export interface TODQuestion {
  id: string;
  type: 'truth' | 'action';
  level: 'soft' | 'medium' | 'hard';
  text: string;
}

const truths = [
  "Quel est le dernier compte Instagram que tu as stalké en cachette ?",
  "Quelle est ta pire photo de carte d'identité ou de passeport ?",
  "As-tu déjà swipé à droite sur quelqu'un que tu connaissais juste pour voir ?",
  "Quel est le message le plus gênant que tu aies envoyé à tes parents par erreur ?",
  "As-tu déjà utilisé l'excuse du 'bug de connexion' pour fuir un appel ?",
  "Quel est ton pire date Tinder à ce jour ?",
  "Quelle est la chanson que tu mets à fond quand tu as un coup de blues ?",
  "Quel est le surnom le plus honteux qu'on t'ait donné au lycée ?",
  "As-tu déjà pleuré devant une vidéo TikTok ?",
  "Quelle est la chose la plus bizarre que tu aies faite pour attirer l'attention de ton crush ?",
  "Quel est ton plaisir coupable sur Netflix ou YouTube ?",
  "Quelle est l'anecdote la plus absurde qui te soit arrivée en cours ?",
  "As-tu déjà fouillé dans le téléphone de ton ou ta partenaire ?",
  "Quel est le pire cadeau que tu aies offert à quelqu'un en pensant bien faire ?",
  "Quelle est ta plus grande peur irrationnelle ?",
  "Quel est ton pire mensonge lors d'un entretien d'embauche ?",
  "As-tu déjà ghosté quelqu'un sans aucune raison valable ?",
  "Quel est le dernier achat inutile que tu as fait sur Internet ?",
  "Quelle est la rumeur la plus folle que tu aies entendue sur toi-même ?",
  "As-tu déjà simulé d'être malade pour sécher un événement social ?",
  "Quelle est ta pire expérience dans les transports en commun ?",
  "Quel est le plat que tu cuisines quand tu as la flemme absolue ?",
  "Quelle est ta pire gaffe lors d'un repas de famille ?",
  "As-tu déjà créé un faux profil sur les réseaux sociaux ?",
  "Quel est ton complexe physique le plus ridicule ?",
  "Quelle est la série honteuse que tu as regardée en entier ?",
  "Quel est ton pire tue-l'amour lors d'un premier rendez-vous ?",
  "As-tu déjà fouillé les affaires d'un ami quand tu étais seul(e) chez lui ?",
  "Quelle est la chose la plus enfantine que tu fasses encore aujourd'hui ?",
  "Quel est ton pire souvenir lié à l'alcool (sans être hardcore) ?",
  "As-tu déjà eu un crush inavouable pour le parent d'un pote ?",
  "Quelle est l'excuse la plus bidon que tu aies sortie pour arriver en retard ?",
  "Quel est ton pire fail en essayant de flirter ?",
  "As-tu déjà pleuré pour obtenir quelque chose ?",
  "Quelle est la tendance mode que tu regrettes d'avoir suivie ?",
  "Quel est le pire conseil que tu aies donné à un ami ?",
  "As-tu déjà été surpris(e) en train de parler tout(e) seul(e) ?",
  "Quelle est la recherche Google la plus bizarre de ton historique ?",
  "Quel est ton pire souvenir de vacances entre amis ?",
  "As-tu déjà menti sur ton âge pour paraître plus vieux/vieille ?",
  "Quelle est ta pire phobie liée aux animaux ?",
  "Quel est le dernier SMS que tu as envoyé ?",
  "As-tu déjà liké une vieille photo Instagram par erreur en stalkant ?",
  "Quelle est la célébrité qui te fait le plus fantasmer en secret ?",
  "Quel est ton pire souvenir chez le coiffeur ?",
  "As-tu déjà oublié l'anniversaire d'une personne très proche ?",
  "Quelle est la superstition la plus ridicule à laquelle tu crois ?",
  "Quel est ton talent le plus inutile en soirée ?",
  "As-tu déjà fait semblant de téléphoner pour éviter de parler à quelqu'un ?",
  "Quelle est ta pire expérience dans des toilettes publiques ?",
  "Quel est le truc le plus cliché que tu aimes faire ?",
  "As-tu déjà gâché la surprise d'une fête d'anniversaire ?",
  "Quelle est l'odeur bizarre que tu adores ?",
  "Quel est ton pire fail sportif ?",
  "As-tu déjà eu honte d'être avec l'un de tes amis en public ?",
  "Quelle est ta pire anecdote de covoiturage ?",
  "Si tu devais participer à une émission de télé-réalité, laquelle serait-ce ?",
  "As-tu déjà mangé quelque chose tombé par terre après la règle des 5 secondes ?",
  "Quel est ton mot de passe le plus ridicule (sans le donner en entier) ?",
  "Quelle est la chose la plus chère que tu aies cassée ?",
  "As-tu déjà accusé quelqu'un d'autre pour une de tes erreurs ?",
  "Quel est le pire métier que tu pourrais faire ?",
  "Quelle est ton astuce secrète de flemmard(e) au quotidien ?",
  "As-tu déjà ri au pire moment possible lors d'un événement sérieux ?",
  "Quel est le message le plus passif-agressif que tu aies écrit ?",
  "Quelle est la célébrité que tout le monde trouve belle sauf toi ?",
  "As-tu déjà menti sur tes goûts musicaux pour plaire à quelqu'un ?",
  "Quel est ton pire souvenir de rentrée scolaire ?",
  "Quelle est la chose la plus absurde que tu aies achetée en ligne la nuit ?",
  "As-tu déjà été viré(e) d'un bar ou d'une boîte de nuit ?",
  "Quel est le dernier rêve très étrange dont tu te souviens ?",
  "Quelle est ta pire expérience avec un voisin ?",
  "As-tu déjà prétendu aimer un cadeau alors que tu le détestais ?",
  "Quel est ton péché mignon en matière de junk food ?",
  "Quelle est la pire chanson que tu connaisses par cœur ?",
  "As-tu déjà fait semblant de dormir pour éviter une conversation ?",
  "Quelle est l'anecdote la plus embarrassante impliquant ton animal de compagnie ?",
  "Quel est ton plus grand regret de la semaine dernière ?",
  "As-tu déjà flirté pour obtenir un avantage gratuit (café, verre, etc.) ?",
  "Quelle est ta pire technique pour sécher les cours ?",
  "Quel est le dernier drama croustillant dans lequel tu as été impliqué(e) ?",
  "As-tu déjà caché une mauvaise note à tes parents pendant des semaines ?",
  "Quelle est la chose la plus ridicule qui t'ait fait pleurer ?",
  "Quel est ton pire souvenir de dentiste ou de médecin ?",
  "As-tu déjà envoyé un screen à la personne même que tu critiquais ?",
  "Quelle est l'application que tu ouvres en premier le matin ?",
  "Quel est le secret de beauté le plus étrange que tu utilises ?",
  "As-tu déjà menti sur ce que tu avais fait de ton week-end ?",
  "Quel est le pire plat que tu aies préparé pour quelqu'un d'autre ?",
  "Quelle est l'excuse la plus fréquente que tu utilises pour ne pas sortir ?",
  "As-tu déjà eu un crush sur un professeur ?",
  "Quelle est la chose la plus honteuse dans ta chambre en ce moment ?",
  "Quel est le dernier texto d'un(e) ex que tu as relu ?",
  "As-tu déjà volé quelque chose dans un supermarché ?",
  "Quelle est la dernière fois où tu as été vraiment jaloux(se) ?",
  "Quel est ton pire fail en tentant une trend TikTok ?",
  "As-tu déjà espionné une conversation de tes parents ?",
  "Quelle est la pire décision capillaire de ta vie ?",
  "Quel est le détail physique que tu regardes en premier chez quelqu'un ?",
  "As-tu déjà eu une amende pour une raison totalement stupide ?",
  "Quel est le dernier mensonge que tu as dit à ton/ta meilleur(e) ami(e) ?",
  "Quelle est ta réaction quand tu croises quelqu'un que tu ne veux pas voir ?",
  "As-tu déjà simulé un orgasme pour en finir plus vite ?",
  "Quelle est l'anecdote de soirée dont tes amis te parlent encore ?",
  "Quel est le film d'horreur qui t'a empêché(e) de dormir enfant ?",
  "As-tu déjà fait un faux compte pour espionner quelqu'un sur Insta ?",
  "Quelle est la chose la plus ridicule que tu aies crue étant petit(e) ?",
  "Quel est ton avis impopulaire sur une série à succès ?",
  "As-tu déjà porté les mêmes sous-vêtements deux jours de suite ?",
  "Quelle est la phrase d'accroche la plus éclatée qu'on t'ait sortie ?",
  "Quel est ton moment de solitude le plus grand de cette année ?",
  "As-tu déjà été surpris(e) en train de chanter à tue-tête dans ta voiture ?",
  "Quelle est ta phobie la plus bizarre liée à la nourriture ?",
  "Quel est le surnom affectueux que tu donnes à tes amis les plus proches ?",
  "As-tu déjà ressenti une attirance pour un personnage de dessin animé ?",
  "Quelle est la pire blague que tu aies faite et qui a mal tourné ?",
  "Quel est ton secret pour éviter de répondre à un message tout de suite ?",
  "As-tu déjà pleuré pour une rupture de célébrités ?",
  "Quelle est ton expression préférée qui est complètement ringarde ?",
  "Quel est ton pire souvenir d'auto-école ou d'examen de conduite ?",
  "As-tu déjà fait semblant de ne pas parler français à l'étranger ?",
  "Quelle est la chose la plus inutile que tu connaisses par cœur ?",
  "Quel est le dernier message reçu sur un groupe WhatsApp familial ?",
  "As-tu déjà utilisé le Wi-Fi du voisin sans lui dire ?",
  "Quelle est ta pire expérience dans une colocation ?",
  "Quel est l'emoji que tu utilises beaucoup trop ?",
  "As-tu déjà mangé l'étiquette d'un fruit par accident sans le recracher ?",
  "Quelle est la mode que tu détestes mais que tu as finie par porter ?",
  "Quel est ton dernier fail avec l'autocorrecteur de ton téléphone ?",
  "As-tu déjà menti à un médecin sur ta consommation d'alcool ?",
  "Quelle est ta tactique pour sortir d'un groupe de discussion sans vexer personne ?",
  "Quel est le moment le plus humiliant que tu aies vécu au supermarché ?",
  "As-tu déjà simulé une urgence pour fuir un date catastrophique ?",
  "Quelle est ta chanson de karaoké préférée où tu chantes faux ?",
  "Quel est le compliment le plus bizarre que tu aies reçu ?",
  "As-tu déjà fait semblant de connaître un groupe de musique pour avoir l'air cool ?",
  "Quelle est ton habitude la plus étrange avant d'aller dormir ?",
  "Quel est ton pire souvenir avec une application de rencontre ?",
  "As-tu déjà fouillé dans l'historique d'un ordinateur public ?",
  "Quelle est la rumeur la plus drôle que tu aies inventée sur quelqu'un ?",
  "Quel est le film que tu as vu le plus grand nombre de fois ?",
  "As-tu déjà ressenti de la jalousie envers un animal de compagnie ?",
  "Quelle est la chose la plus absurde que tu aies dite en dormant ?",
  "Quel est ton dernier acte de rébellion très mineur ?",
  "As-tu déjà menti sur tes compétences sur un CV de façon éhontée ?",
  "Quelle est la pire excuse que tu aies utilisée pour ne pas rendre un devoir ?",
  "Quel est l'endroit le plus bizarre où tu t'es endormi(e) ?",
  "As-tu déjà pleuré de rire à un moment totalement inapproprié ?",
  "Quelle est la chose la plus bizarre dans ton réfrigérateur actuellement ?",
  "Quel est ton pire souvenir de photo de classe ?",
  "As-tu déjà oublié ton propre âge ou ton code PIN ?",
  "Quelle est ta technique infaillible pour tricher sans te faire prendre ?",
  "Quel est le dernier objet que tu aies cassé de rage ?",
  "As-tu déjà été amoureux(se) de deux personnes en même temps ?",
  "Quelle est la phobie de ton partenaire/meilleur pote dont tu te moques secrètement ?",
  "Quel est ton souvenir de honte ultime en faisant du sport ?",
  "As-tu déjà fait semblant d'aimer la cuisine de tes beaux-parents ?",
  "Quelle est la chose la plus chère que tu aies volée à un hôtel ?",
  "Quel est ton pire fail en essayant de prendre un selfie discret ?",
  "As-tu déjà envoyé un message énervé puis réalisé que tu avais tort ?",
  "Quelle est l'anecdote la plus folle que tu aies vue dans le métro/bus ?",
  "Quel est ton record de jours passés sans sortir de chez toi ?",
  "As-tu déjà fouillé les tiroirs de tes parents étant petit(e) ?",
  "Quelle est la pire série française selon toi ?",
  "Quel est ton rituel secret quand tu as une mauvaise journée ?",
  "As-tu déjà inventé une excuse médicale pour une sortie ?",
  "Quelle est ta pire expérience avec un service client ?",
  "Quel est ton dernier achat impulsif lié à une passion éphémère ?",
  "As-tu déjà prétendu être un expert dans un domaine où tu es nul(le) ?",
  "Quelle est la chose la plus gênante que ton téléphone ait faite en public ?",
  "Quel est le dernier message lu mais ignoré volontairement dans ton téléphone ?",
  "As-tu déjà eu un fou rire à un enterrement ou une messe ?",
  "Quelle est l'habitude de tes amis que tu supportes le moins ?",
  "Quel est ton pire souvenir avec un insecte dans ta chambre ?",
  "As-tu déjà pleuré devant une publicité à la télé ?",
  "Quelle est ton astuce de pro pour paraître occupé(e) au travail/en cours ?",
  "Quel est le mensonge le plus drôle auquel tu as cru enfant ?",
  "As-tu déjà espionné l'écran du téléphone de la personne à côté de toi dans le bus ?",
  "Quelle est ta pire expérience avec un livreur UberEats ou Deliveroo ?",
  "Quel est ton plus grand moment de paranoïa irrationnelle ?",
  "As-tu déjà prétendu aimer un groupe de K-pop sans en connaître un seul ?",
  "Quelle est la dernière photo que tu as supprimée de ton téléphone et pourquoi ?",
  "Quel est le pire message d'ivresse que tu aies écrit ?",
  "As-tu déjà menti à un SDF pour ne pas lui donner d'argent ?",
  "Quelle est la chose la plus étrange que tu aies trouvée dans tes poches ?",
  "Quel est le dernier mensonge de tes parents que tu as découvert ?",
  "As-tu déjà simulé une crampe pour arrêter une activité physique ?",
  "Quelle est ta technique pour esquiver les distributeurs de flyers dans la rue ?",
  "Quel est ton pire fail en essayant d'être sexy ?",
  "As-tu déjà pleuré pour une mauvaise coupe de cheveux au salon ?",
  "Quelle est la pire excuse que tu aies sortie pour annuler un rdv galant ?",
  "Quel est l'endroit le plus bizarre où tu aies pris une photo de toi ?",
  "As-tu déjà prétendu avoir lu un livre classique pour faire intelligent(e) ?",
  "Quelle est ton anecdote de honte maximale dans une boutique de vêtements ?",
  "Quel est ton pire complexe quand tu vas à la plage ?",
  "As-tu déjà fouillé dans les médicaments de la salle de bain de quelqu'un ?",
  "Quelle est la pire chanson que tu aies mise pendant l'intimité ?",
  "Quel est le dernier objet que tu as cassé par maladresse ?",
  "As-tu déjà ri à une blague que tu n'avais pas du tout comprise ?",
  "Quelle est l'émission de télé-réalité que tu regardes secrètement ?",
  "Quel est ton pire fail avec un assistant vocal (Siri, Alexa) ?",
  "As-tu déjà envoyé un email professionnel avec une énorme faute ?",
  "Quelle est ton habitude la plus dégoûtante quand personne ne regarde ?"
];

const actions = [
  "Montre le dernier message envoyé à ta mère.",
  "Imite le rire de la personne à ta gauche pendant 10 secondes.",
  "Envoie un emoji 'aubergine' au 3ème contact de ton répertoire WhatsApp.",
  "Mets ta photo de profil Instagram ou WhatsApp à l'envers pendant 10 minutes.",
  "Laisse la personne à ta droite publier un tweet (ou thread) avec ton téléphone.",
  "Danse la Macarena sans aucune musique pendant 15 secondes.",
  "Parle avec un accent québécois jusqu'à ton prochain tour.",
  "Tente de faire un compliment romantique au mur le plus proche.",
  "Fais le tour du groupe en marchant comme un canard.",
  "Bois une gorgée d'eau sans utiliser tes mains.",
  "Mime ta scène de film préférée, les autres doivent la deviner.",
  "Reste figé(e) comme une statue pendant 30 secondes chrono.",
  "Chante le refrain de ta chanson préférée en remplaçant toutes les voyelles par 'o'.",
  "Appelle le 5ème contact de ton répertoire et raccroche immédiatement après qu'il décroche.",
  "Laisse la personne en face de toi dessiner sur ton bras avec un stylo.",
  "Fais 10 pompes ou 10 squats en criant 'Je suis le roi/la reine !'.",
  "Imite un influenceur qui fait un placement de produit pour une brosse à toilettes.",
  "Récite l'alphabet à l'envers aussi vite que possible.",
  "Fais un câlin de 5 secondes à la personne à ta gauche.",
  "Change ton statut WhatsApp pour 'À la recherche d'un sugar daddy/mommy'.",
  "Prends un selfie très laid et mets-le en story privée (ou close friends).",
  "Parle comme un robot pendant tes trois prochaines interventions.",
  "Touche ton nez avec ta langue, ou essaie pendant 15 secondes.",
  "Laisse le joueur de ton choix te recoiffer.",
  "Fais un discours politique de 30 secondes sur l'importance du fromage.",
  "Mets un glaçon dans ton t-shirt jusqu'à ce qu'il fonde.",
  "Envoie 'Je crois que j'ai fait une grosse bêtise' à un(e) ami(e) et montre la réponse.",
  "Chuchote tout ce que tu dis jusqu'à ton prochain tour.",
  "Donne ton téléphone déverrouillé au joueur à ta droite pendant 30 secondes.",
  "Mange un aliment de la table en gardant les yeux fermés et devine ce que c'est.",
  "Fais le poirier (ou essaie) contre le mur le plus proche.",
  "Invente un rap de 15 secondes sur la personne en face de toi.",
  "Masse les épaules de la personne à ta droite pendant 1 minute.",
  "Fais semblant d'être ivre jusqu'à ton prochain tour.",
  "Mime une bagarre au ralenti avec un adversaire invisible.",
  "Prends la voix la plus grave possible pour tes 3 prochaines phrases.",
  "Renifle les chaussettes (ou chaussures) de la personne à ta gauche.",
  "Mange un morceau de citron ou un aliment très acide sans faire de grimace.",
  "Invente une chorégraphie TikTok de 10 secondes et réalise-la devant tout le monde.",
  "Imite un professeur que tout le groupe connaît (ou ton patron).",
  "Fais un Tuto Beauté hilarant en utilisant des objets de la table.",
  "Lis tes 3 dernières recherches YouTube à voix haute.",
  "Fais comme si tu animais une émission de télé-achat pour vendre la table basse.",
  "Déclare ton amour inconditionnel à la plante verte ou à l'objet le plus proche.",
  "Twerk pendant 10 secondes (ou essaie au moins).",
  "Agis comme si tu avais perdu la mémoire pendant la prochaine minute.",
  "Fais un air guitar très passionné sur une chanson imaginaire.",
  "Mime un animal en pleine parade nuptiale.",
  "Chante une chanson Disney en imitant les voix des personnages.",
  "Fais une critique gastronomique de ta dernière boisson comme un grand chef.",
  "Imite un tyrannosaure pendant 30 secondes.",
  "Fais un tour de magie qui rate lamentablement.",
  "Laisse le groupe choisir un mot que tu n'auras plus le droit de prononcer ce soir.",
  "Fais une pose de mannequin de haute couture et maintiens-la 20 secondes.",
  "Laisse la personne de ton choix te mordre le doigt très légèrement.",
  "Invente une rumeur complètement absurde sur la personne en face de toi.",
  "Fais un discours d'excuse larmoyant pour avoir mangé la dernière part de pizza.",
  "Fais la météo de demain de manière extrêmement dramatique.",
  "Mime un astronaute qui marche sur la lune avec une gravité faible.",
  "Fais la voix d'un animateur radio des années 80 pour annoncer le prochain tour.",
  "Imite un oiseau qui essaie de séduire un humain.",
  "Raconte ton pire cauchemar d'enfance avec une voix de bébé.",
  "Mime une personne qui a très envie d'aller aux toilettes mais ne trouve pas la porte.",
  "Joue du piano invisible comme un virtuose en plein concert.",
  "Imite le cri de guerre d'un samouraï au moment d'attaquer.",
  "Fais un bruit de sirène d'alarme jusqu'à ce qu'un joueur te demande d'arrêter.",
  "Mime un chef cuisinier très stressé qui rate sa recette.",
  "Fais la danse de la victoire de Fortnite de ton choix.",
  "Écris 'Je suis fan de toi' en commentaire sur le dernier post Instagram de la 3ème personne de ton feed.",
  "Lèche ton coude (ou passe 10 secondes à essayer désespérément).",
  "Imite un présentateur de JT annonçant la fin du monde imminente.",
  "Fais semblant de jouer du violon sur un air très triste pendant 20 secondes.",
  "Dis 'Je t'aime' de 3 façons différentes avec 3 accents différents.",
  "Fais une roulade au sol (ou un salto imaginaire si pas d'espace).",
  "Laisse le joueur à ta droite te choisir un nouveau fond d'écran pour la soirée.",
  "Chante une chanson de rap en version berceuse.",
  "Mime une publicité pour un produit anti-chute de cheveux.",
  "Fais 5 squats en criant le nom de ton/ta crush actuel(le) ou historique.",
  "Laisse la personne à ta gauche te faire un suçon dans le cou... avec ses doigts (un faux).",
  "Prends l'objet le plus proche et essaie de le vendre au groupe pour 1 million d'euros.",
  "Agis comme un chat qui fait sa toilette pendant 30 secondes.",
  "Appelle la 2ème personne de tes contacts récents et demande-lui la recette des crêpes.",
  "Fais le bruit du modem des années 2000 qui se connecte à internet.",
  "Laisse un joueur te chatouiller pendant 10 secondes sans rire.",
  "Mime une personne qui essaie de marcher avec des talons de 15 cm pour la première fois.",
  "Fais semblant d'être possédé par un démon jusqu'à ce qu'on te 'désenvoûte'.",
  "Répète tout ce que dit le joueur à ta droite pendant 3 minutes.",
  "Fais un câlin à la personne qui a le plus de points.",
  "Mets tes chaussettes sur tes mains et garde-les pour 2 tours.",
  "Chante la Marseillaise avec la bouche fermée.",
  "Fais une imitation d'Emmanuel Macron (ou du président) qui annonce une bonne nouvelle.",
  "Tente de jongler avec 3 objets choisis par le groupe.",
  "Fais une danse du ventre sensuelle devant la personne en face de toi.",
  "Parle de toi à la troisième personne du singulier pour les 3 prochains tours.",
  "Imite un coq au lever du soleil très bruyamment.",
  "Essaie de faire pleurer le groupe avec une histoire fausse.",
  "Fais un bruit de pet avec tes aisselles.",
  "Laisse le joueur de ton choix t'attacher les poignets avec un lacet pendant 5 minutes.",
  "Lis tes 5 derniers messages reçus en prenant la voix de Dark Vador.",
  "Fais comme si tu étais un zombie cherchant des cerveaux pendant 1 minute.",
  "Mime un combat épique d'arts martiaux contre une mouche imaginaire.",
  "Fais 15 sauts en étoile en criant 'Hourra !' à chaque saut.",
  "Tente d'hypnotiser la personne à ta gauche avec tes mains et tes yeux.",
  "Mime une séance photo pour un magazine de mode ridicule.",
  "Fais un compliment à chaque joueur, mais termine par '...mais bon, c'est dommage pour le reste'.",
  "Chante a capella comme si tu étais à l'opéra.",
  "Laisse le groupe te renommer pour la soirée (tu devras répondre uniquement à ce nom).",
  "Imite une alarme de voiture qui s'emballe.",
  "Mime une personne coincée dans une boîte invisible de plus en plus petite.",
  "Fais semblant de perdre les eaux comme dans un film.",
  "Appelle un numéro au hasard (composé par tes amis) et souhaite une bonne année.",
  "Tente de toucher ton nez avec ta langue en fermant un seul œil.",
  "Mets ton pull ou ton t-shirt à l'envers et laisse-le ainsi jusqu'à la fin de la partie.",
  "Agis comme un commentateur sportif pour décrire les actions de la pièce.",
  "Mime un plongeon au ralenti comme dans Alerte à Malibu.",
  "Fais le poirier en appuyant tes pieds contre le mur.",
  "Essaie de gober un aliment jeté en l'air par le joueur en face de toi.",
  "Fais un rap d'au moins 4 rimes avec les prénoms des joueurs présents.",
  "Fais comme si tu découvrais le feu pour la première fois.",
  "Laisse la personne à ta gauche te maquiller les yeux (ou mime-le si pas de maquillage).",
  "Mime la personne la plus soûle de la soirée.",
  "Fais un discours passionnant sur l'utilité des lacets de chaussures.",
  "Imite un singe qui vient de trouver une banane géante.",
  "Parle avec un cheveu sur la langue jusqu'à ton prochain tour.",
  "Essaie de faire rire la personne en face de toi sans la toucher.",
  "Mime un joueur de tennis professionnel en plein match.",
  "Laisse le groupe t'inventer une punition si tu perds le prochain jeu.",
  "Fais une déclaration d'amour digne d'une telenovela au balai ou à la serpillière.",
  "Chante une chanson de Noël au milieu du salon.",
  "Fais le bruit d'une moto qui démarre et qui cale.",
  "Fais comme si ton doigt était une baguette magique et jette des sorts.",
  "Imite le rire de Gollum dans le Seigneur des Anneaux.",
  "Parle avec les dents serrées pendant 3 tours.",
  "Mime une personne qui marche sur des braises ardentes.",
  "Laisse le joueur à ta droite te choisir une nouvelle coupe de cheveux (avec les mains).",
  "Tente de faire du breakdance au sol.",
  "Fais une imitation d'un professeur d'yoga très spirituel.",
  "Imite un avion en plein décollage avec les bruits.",
  "Mime un cambrioleur qui se fait surprendre.",
  "Chante une berceuse en fixant la personne à ta droite.",
  "Agis comme si tu avais une puce géante dans le dos et essaie de t'en débarrasser.",
  "Fais un poème en alexandrins sur ton dernier repas.",
  "Imite un enfant de 4 ans qui fait un caprice au supermarché.",
  "Laisse le groupe choisir ta sonnerie de téléphone pour demain matin.",
  "Mime la personne de ton choix dans la pièce, on doit deviner.",
  "Enlève une de tes chaussettes avec tes dents.",
  "Fais une scène de jalousie au joueur de ton choix pour une raison absurde.",
  "Agis comme un robot dont la batterie est faible.",
  "Chante le générique d'un dessin animé culte.",
  "Fais une publicité pour un produit de beauté invisible.",
  "Laisse la personne à ta gauche te donner à manger à la cuillère.",
  "Mime un personnage de jeu vidéo en pleine action.",
  "Imite une sirène de police française.",
  "Parle sans bouger les lèvres comme un ventriloque.",
  "Essaie de deviner la marque des sous-vêtements de 3 personnes (si faux, bois 1 gorgée).",
  "Fais la roue (ou essaie) sans rien casser.",
  "Mime une personne qui vient de gagner au Loto.",
  "Imite une poule qui pond un œuf d'or.",
  "Chante une chanson de variété française en pleurant.",
  "Fais un concours de grimaces avec le joueur en face (le perdant boit).",
  "Laisse le groupe lire ton historique de recherche Google récent.",
  "Agis comme si tu étais dans un film muet en noir et blanc.",
  "Mime un western duel au soleil avec ton voisin.",
  "Fais une démonstration de magie avec un stylo.",
  "Fais 5 burpees en criant 'Je suis une machine !'.",
  "Imite un pigeon dans un parc public.",
  "Laisse la personne de ton choix te dessiner un tatouage au stylo sur le bras.",
  "Chante une chanson de rock avec une voix aiguë.",
  "Agis comme si tu étais le présentateur d'une émission de télé-achat.",
  "Mime un personnage de Star Wars.",
  "Fais semblant d'être une statue de musée.",
  "Imite un chien qui demande une friandise.",
  "Laisse la personne à ta droite prendre le contrôle de ton compte Insta pendant 1 minute.",
  "Mime la préparation d'un cocktail sophistiqué.",
  "Fais une imitation d'un animal marin de ton choix.",
  "Chante une chanson en anglais avec un très fort accent français.",
  "Agis comme si tu étais le roi ou la reine d'un pays inventé.",
  "Mime un super-héros qui découvre ses pouvoirs.",
  "Laisse le groupe te poser une question gênante supplémentaire.",
  "Imite un chat qui demande des caresses.",
  "Fais un discours pour sauver le monde d'une invasion extraterrestre.",
  "Mime un danseur de ballet maladroit.",
  "Chante une chanson de Britney Spears avec passion.",
  "Agis comme si tu étais un espion infiltré dans la soirée.",
  "Laisse la personne à ta gauche te raconter une blague sans rire.",
  "Mime un DJ en plein set dans un club.",
  "Fais semblant d'être un fantôme gentil.",
  "Imite un loup qui hurle à la lune.",
  "Chante le générique des Pokémon avec conviction.",
  "Agis comme si tu étais le leader d'une secte amicale.",
  "Laisse le groupe te choisir un nouveau style vestimentaire avec tes vêtements actuels.",
  "Mime un astronaute en train de réparer une fusée.",
  "Fais une imitation d'une personne célèbre de ton choix.",
  "Chante une chanson romantique au joueur de ton choix.",
  "Agis comme si tu étais un chef d'orchestre passionné.",
  "Mime un personnage de conte de fées.",
  "Laisse la personne à ta droite te choisir une nouvelle photo de profil.",
  "Imite un présentateur de jeu télévisé très enthousiaste.",
  "Fais semblant d'être une horloge coucou.",
  "Chante une chanson de comédie musicale avec chorégraphie.",
  "Agis comme si tu étais un détective privé.",
  "Mime un joueur de baseball qui frappe un home run.",
  "Laisse le groupe choisir ta prochaine action.",
  "Imite un perroquet qui répète tout.",
  "Fais un discours de motivation pour le joueur de ton choix.",
  "Mime un personnage de manga.",
  "Chante une chanson avec la bouche pleine (d'eau ou d'air).",
  "Agis comme si tu étais un vampire qui a peur du sang.",
  "Laisse la personne à ta gauche te faire un massage des épaules.",
  "Mime un pirate qui cherche un trésor.",
  "Fais une imitation d'un animateur de colonie de vacances.",
  "Chante une chanson d'amour à une chaussure."
];

export const TOD_QUESTIONS: TODQuestion[] = [
  ...truths.map((text, i) => ({
    id: `soft-v-${i + 1}`,
    type: 'truth' as const,
    level: 'soft' as const,
    text
  })),
  ...actions.map((text, i) => ({
    id: `soft-a-${i + 1}`,
    type: 'action' as const,
    level: 'soft' as const,
    text
  })),
  // À SUIVRE : VAGUE 2 (MEDIUM)
];
